# Generated by Django 5.0.6 on 2024-06-20 06:07

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LookUpIntegerationNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("name", models.CharField(max_length=2000)),
                (
                    "integeration_type",
                    models.CharField(
                        choices=[
                            ("email", "email"),
                            ("sms", "sms"),
                            ("whatsapp", "whatsapp"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "keys",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=600),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("icon_url", models.CharField(max_length=600)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="NotificationIntegeration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("name", models.CharField(max_length=200)),
                ("data", models.JSONField()),
                ("icon_url", models.CharField(max_length=600)),
                (
                    "integeration_type",
                    models.CharField(
                        choices=[
                            ("email", "email"),
                            ("sms", "sms"),
                            ("whatsapp", "whatsapp"),
                        ],
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"abstract": False,},
        ),
    ]
