# Generated by Django 5.0.6 on 2024-06-20 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notification", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationintegeration",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_country",
                to="users.country",
            ),
        ),
        migrations.AddField(
            model_name="notificationintegeration",
            name="look_up",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="notification.lookupintegerationnotification",
            ),
        ),
    ]
