# Generated by Django 5.0.6 on 2024-06-20 07:34

from django.db import migrations

def add_default_values(apps, schema_editor):
    LookUpNotificationKeys = apps.get_model('notification', 'LookUpIntegerationNotification')
    LookUpNotificationKeys.objects.create(name='sms_buddy', integeration_type='sms',keys=["secret_key","sms_type","sender_id","sms_template_id"], icon_url="https://cdnl.iconscout.com/lottie/premium/thumb/sms-marketing-5696012-4740958.gif")
    LookUpNotificationKeys.objects.create(name='smtp_go', integeration_type='email',keys=["sender_email","email_server","email_port","email_username","email_password"], icon_url="https://cdn.dribbble.com/users/767222/screenshots/2149436/mail-animation.gif")
    
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
    ]

    operations = [
         migrations.RunPython(add_default_values),
    ]
