# Generated by Django 5.0.6 on 2024-06-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_look_up_notifications'),
    ]

    operations = [
    ]
