# Generated by Django 5.0.6 on 2024-06-24 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_look_up_notification_data'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lookupintegerationnotification',
            table='lookup_integeration_notification',
        ),
        migrations.AlterModelTable(
            name='notificationintegeration',
            table='notification_integeration',
        ),
    ]
