# Generated by Django 5.0.6 on 2024-06-24 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_lookupintegerationnotification_table_and_more'),
        ('template', '0006_delete_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.lookupnotificationkeys')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='template.notificationtemplates')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
