# Generated by Django 5.0.6 on 2024-06-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_notifications'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notifications',
            table='notifications',
        ),
    ]
