# Generated by Django 5.0.6 on 2024-07-03 11:20

from django.db import migrations
from integrations.notification.models import LookUpIntegerationNotification

def create_lookup_notification_integration(apps, schema_editor):
    lookup_notification_model  = apps.get_model('notification', 'LookUpIntegerationNotification')
    lookup_notification_model.objects.create(
        name = LookUpIntegerationNotification.Keywords.EMAIL_NOTIFICATION,
        integeration_type = 'email',
        keys = ['api_key'],
        icon_url = 'https://cdn.dribbble.com/users/159009/screenshots/1601852/airplane-flight-animation.gif'

    )
class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0007_alter_notifications_table"),
    ]

    operations = [
        # migrations.RunPython(create_lookup_notification_integration),
    ]
