# Generated by Django 5.0.6 on 2024-07-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0008_create_lookup_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationintegeration",
            name="name",
            field=models.CharField(
                choices=[("email_notification", "EMAIL_NOTIFICATION")], max_length=200
            ),
        ),
    ]
