# Generated by Django 5.0.6 on 2024-07-23 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0009_alter_notificationintegeration_name"),
        ("users", "0015_lookupairports_nearest"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.organization",
            ),
            preserve_default=False,
        ),
    ]
