# Generated by Django 5.0.6 on 2024-07-26 08:41

from django.db import migrations


def add_default_values(apps, schema_editor):
    LookUpNotificationKeys = apps.get_model('notification', 'LookUpIntegerationNotification')
    is_exiting = LookUpNotificationKeys.objects.filter(name='Amazon SES')
    if is_exiting:
        for obj in is_exiting:
            obj.delete()
    LookUpNotificationKeys.objects.create(name='Amazon SES', integeration_type='email',keys=["smtp_server","smtp_port","smtp_username","smtp_password","sender_email"], icon_url="https://miro.medium.com/v2/resize:fit:679/0*FJJugDwO6kMmcIpz.gif")



class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0012_auto_20240726_0902"),
    ]

    operations = []
