# Generated by Django 5.0.6 on 2024-08-07 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0013_auto_20240731_0635"),
        ("users", "0023_lookuppermission_admin1space1panel_delete_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="users.organization"
            ),
        ),
    ]
