# Generated by Django 5.0.6 on 2024-08-07 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0014_alter_notifications_organization"),
        ("template", "0013_auto_20240801_1128"),
        ("users", "0023_lookuppermission_admin1space1panel_delete_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="template.lookupnotificationkeys",
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.organization",
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="template.notificationtemplates",
            ),
        ),
    ]
