# Generated by Django 5.0.6 on 2024-08-07 11:11

from django.db import migrations


from django.db import migrations, models

def populate_organization(apps, schema_editor):
    Notification = apps.get_model('notification', 'Notifications')
    Organization = apps.get_model('users', 'Organization')
    default_organization = Organization.objects.first()  # Choose a valid default organization

    for notification in Notification.objects.filter(organization__isnull=True):
        notification.organization = default_organization
        notification.save()

class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0015_alter_notifications_event_and_more"),
    ]

    
    operations = [
        migrations.RunPython(populate_organization),
    ]
