# Generated by Django 5.0.6 on 2024-08-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0016_auto_20240807_1111"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notifications",
            name="event",
        ),
        migrations.RemoveField(
            model_name="notifications",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="notifications",
            name="template",
        ),
    ]
