# Generated by Django 5.0.6 on 2024-08-10 10:25

from django.db import migrations


def add_default_values(apps, schema_editor):
    LookUpNotificationKeys = apps.get_model('notification', 'LookUpIntegerationNotification')
    LookUpNotificationKeys.objects.create(name='Amazon SES', integeration_type='email',keys=["smtp_server","smtp_port","smtp_username","smtp_password"], icon_url="https://miro.medium.com/v2/resize:fit:679/0*FJJugDwO6kMmcIpz.gif")




class Migration(migrations.Migration):

    dependencies = [
        (
            "notification",
            "0018_notifications_event_notifications_organization_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(add_default_values)
    ]
