# Generated by Django 5.0.6 on 2024-09-05 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0019_auto_20240810_1025'),
        ('template', '0015_auto_20240810_1038'),
        ('users', '0030_alter_lookuporganizationtypes_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='template.notificationtemplates'),
        ),
    ]
