# Generated by Django 5.0.6 on 2024-09-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0020_alter_notifications_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationintegeration',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
