# Generated by Django 5.0.6 on 2024-10-09 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0021_alter_notificationintegeration_name'),
    ]

    operations = [
    ]
