# Generated by Django 5.0.6 on 2024-11-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0022_auto_20241009_0527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lookupintegerationnotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notificationintegeration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-created_at']},
        ),
    ]
