# Generated by Django 5.0.6 on 2024-10-09 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0012_alter_organizationsupplierintegeration_table'),
        ('users', '0049_lookupairline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineDeals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('source', models.CharField(blank=True, max_length=2000, null=True)),
                ('destination', models.CharField(blank=True, max_length=2000, null=True)),
                ('sector', models.BooleanField()),
                ('cabin', models.TextField()),
                ('class_included', models.TextField()),
                ('class_excluded', models.TextField()),
                ('deal_type', models.CharField(choices=[('dom', 'dom'), ('int', 'int')], max_length=2000)),
                ('iata_commission', models.FloatField(default=0.0)),
                ('basic', models.CharField(max_length=2000, null=True)),
                ('basic_yq', models.CharField(max_length=2000, null=True)),
                ('basic_yr', models.CharField(max_length=2000, null=True)),
                ('valid_till', models.BigIntegerField(null=True)),
                ('country_applicability', models.BooleanField()),
                ('source_country_code', models.CharField(blank=True, max_length=2000, null=True)),
                ('destination_country_code', models.CharField(blank=True, max_length=2000, null=True)),
                ('soto', models.BooleanField()),
                ('basic_after_valid_date', models.BigIntegerField(null=True)),
                ('yq_after_valid_date', models.BigIntegerField(null=True)),
                ('code_sharing', models.BooleanField()),
                ('status', models.BooleanField(default=True)),
                ('airline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.lookupairline')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplierintegration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
