# Generated by Django 5.0.6 on 2024-10-18 06:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlinedeals',
            name='basic',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='airlinedeals',
            name='basic_yq',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='airlinedeals',
            name='basic_yr',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='airlinedeals',
            name='class_excluded',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='airlinedeals',
            name='class_included',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='airlinedeals',
            name='code_sharing',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='airlinedeals',
            name='destination',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='airlinedeals',
            name='destination_country_code',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='airlinedeals',
            name='source',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='airlinedeals',
            name='source_country_code',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
