# Generated by Django 5.0.6 on 2024-10-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_accounting', '0002_alter_airlinedeals_basic_alter_airlinedeals_basic_yq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlinedeals',
            name='discount_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='airlinedeals',
            name='yr_after_valid_date',
            field=models.BigIntegerField(null=True),
        ),
    ]
