# Generated by Django 5.0.6 on 2024-11-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_accounting', '0003_airlinedeals_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlinedeals',
            name='deal_type',
            field=models.CharField(choices=[('DOM', 'DOM'), ('INT', 'INT')], max_length=2000),
        ),
    ]
