# Generated by Django 5.0.6 on 2024-11-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_accounting', '0004_alter_airlinedeals_deal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlinedeals',
            name='basic_after_valid_date',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airlinedeals',
            name='class_excluded',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airlinedeals',
            name='class_included',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airlinedeals',
            name='code_sharing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airlinedeals',
            name='yq_after_valid_date',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airlinedeals',
            name='yr_after_valid_date',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
