# Generated by Django 5.0.6 on 2024-11-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_accounting', '0005_alter_airlinedeals_basic_after_valid_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlinedeals',
            name='basic',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='airlinedeals',
            name='basic_yq',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='airlinedeals',
            name='basic_yr',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='airlinedeals',
            name='country_applicability',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airlinedeals',
            name='iata_commission',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
