# Generated by Django 5.0.6 on 2024-11-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_accounting', '0006_alter_airlinedeals_basic_alter_airlinedeals_basic_yq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlinedeals',
            name='iata_commission',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
