# Generated by Django 5.0.6 on 2024-11-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_accounting', '0007_alter_airlinedeals_iata_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlinedeals',
            name='basic_after_valid_date',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airlinedeals',
            name='yq_after_valid_date',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airlinedeals',
            name='yr_after_valid_date',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
