# Generated by Django 5.0.6 on 2024-11-19 05:44

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_accounting', '0009_supplierairlinedeals'),
        ('suppliers', '0016_alter_lookupsupplierintegration_options_and_more'),
        ('users', '0072_lookuppermission_admin1space1panel_supplier1space1deal1space1manager_create_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDealManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('source', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('destination', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('sector', models.BooleanField()),
                ('cabin', models.TextField()),
                ('class_included', models.TextField(blank=True, null=True)),
                ('class_excluded', models.TextField(blank=True, null=True)),
                ('deal_type', models.CharField(choices=[('DOM', 'DOM'), ('INT', 'INT')], max_length=2000)),
                ('iata_commission', models.FloatField(blank=True, default=0.0, null=True)),
                ('basic', models.FloatField(blank=True, default=0.0, null=True)),
                ('basic_yq', models.FloatField(blank=True, default=0.0, null=True)),
                ('basic_yr', models.FloatField(blank=True, default=0.0, null=True)),
                ('valid_till', models.BigIntegerField(null=True)),
                ('country_applicability', models.BooleanField(blank=True, null=True)),
                ('source_country_code', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('destination_country_code', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('soto', models.BooleanField()),
                ('basic_after_valid_date', models.FloatField(blank=True, null=True)),
                ('yq_after_valid_date', models.FloatField(blank=True, null=True)),
                ('yr_after_valid_date', models.FloatField(blank=True, null=True)),
                ('discount_percentage', models.FloatField(default=0.0)),
                ('code_sharing', models.BooleanField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('gst_inclusive', models.BooleanField()),
                ('service_charge', models.FloatField(blank=True, null=True)),
                ('airline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.lookupairline')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplierintegration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SupplierAirlineDeals',
        ),
    ]
