# Generated by Django 5.0.6 on 2024-11-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_accounting', '0010_supplierdealmanagement_delete_supplierairlinedeals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierdealmanagement',
            name='service_charge',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
