# Generated by Django 5.0.6 on 2025-02-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_accounting", "0011_alter_supplierdealmanagement_service_charge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airlinedeals",
            name="cabin",
            field=models.TextField(blank=True, null=True),
        ),
    ]
