# Generated by Django 5.0.6 on 2025-02-28 10:14

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_accounting", "0012_alter_airlinedeals_cabin"),
        ("suppliers", "0021_remove_supplierintegration_custom_filter"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightSupplierAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("heading", models.CharField(blank=True, max_length=600, null=True)),
                (
                    "sector_from",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "sector_to",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "country_from",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "country_to",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("dom", models.BooleanField()),
                ("int", models.BooleanField()),
                ("round_int", models.BooleanField()),
                ("lcc", models.BooleanField()),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suppliers.supplierintegration",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
