# Generated by Django 5.0.6 on 2025-03-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "flight_accounting",
            "0014_remove_flightsupplieravailability_country_from_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="flightsupplieravailability",
            name="country_from",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flightsupplieravailability",
            name="country_to",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flightsupplieravailability",
            name="sector_from",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flightsupplieravailability",
            name="sector_to",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
