# Generated by Django 5.0.6 on 2025-03-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flight_accounting", "0015_flightsupplieravailability_country_from_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flightsupplieravailability", name="country_from",
        ),
        migrations.RemoveField(
            model_name="flightsupplieravailability", name="country_to",
        ),
        migrations.RemoveField(
            model_name="flightsupplieravailability", name="sector_from",
        ),
        migrations.RemoveField(
            model_name="flightsupplieravailability", name="sector_to",
        ),
    ]
