# Generated by Django 5.0.6 on 2025-03-03 12:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "flight_accounting",
            "0016_remove_flightsupplieravailability_country_from_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="flightsupplieravailability",
            name="airline",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="flightsupplieravailability",
            name="country_from",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="flightsupplieravailability",
            name="country_to",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="flightsupplieravailability",
            name="sector_from",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="flightsupplieravailability",
            name="sector_to",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
