# Generated by Django 5.0.6 on 2025-03-24 10:11

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_accounting", "0017_flightsupplieravailability_airline_and_more"),
        ("suppliers", "0024_alter_supplierintegration_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightSupplierFilters",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("heading", models.CharField(blank=True, max_length=600, null=True)),
                (
                    "sector_from",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "sector_to",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "country_from",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "country_to",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "airline",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("dom", models.BooleanField()),
                ("int", models.BooleanField()),
                ("round_int", models.BooleanField()),
                ("lcc", models.BooleanField()),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suppliers.supplierintegration",
                    ),
                ),
            ],
            options={
                "db_table": "flight_supplier_filters",
                "ordering": ["-created_at"],
            },
        ),
    ]
