# Generated by Django 5.0.6 on 2025-03-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_accounting", "0018_flightsupplierfilters"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightsupplierfilters",
            name="gds",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="flightsupplierfilters",
            name="dom",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="flightsupplierfilters",
            name="int",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="flightsupplierfilters",
            name="lcc",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="flightsupplierfilters",
            name="round_int",
            field=models.BooleanField(default=True),
        ),
    ]
