# Generated by Django 5.0.6 on 2025-03-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_accounting", "0019_flightsupplierfilters_gds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightsupplierfilters",
            name="regular_fare",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="flightsupplierfilters",
            name="senior_citizen_fare",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="flightsupplierfilters",
            name="sudent_fare",
            field=models.BooleanField(default=True),
        ),
    ]
