# Generated by Django 5.0.6 on 2025-03-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flight_accounting", "0020_flightsupplierfilters_regular_fare_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flightsupplierfilters",
            old_name="sudent_fare",
            new_name="student_fare",
        ),
    ]
