# Generated by Django 5.0.6 on 2024-12-24 05:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GiataCountry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("country_name", models.CharField(max_length=500)),
                ("country_code", models.CharField(max_length=500)),
            ],
            options={"db_table": "giata_country", "ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="GiataDestination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("destination_name", models.CharField(max_length=500)),
                ("destination_id", models.CharField(max_length=500)),
                (
                    "country_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="giata.giatacountry",
                    ),
                ),
            ],
            options={"db_table": "giata_destination", "ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="GiataCity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("city_name", models.CharField(max_length=500)),
                ("city_id", models.CharField(max_length=500)),
                (
                    "destination_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="giata.giatadestination",
                    ),
                ),
            ],
            options={"db_table": "giata_city", "ordering": ["-created_at"],},
        ),
    ]
