# Generated by Django 5.0.6 on 2024-12-30 10:32

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="giatacity", options={},),
        migrations.AlterModelOptions(name="giatacountry", options={},),
        migrations.AlterModelOptions(name="giatadestination", options={},),
        migrations.CreateModel(
            name="GiataProperties",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("giata_id", models.CharField(max_length=300)),
                (
                    "last_updated",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("name", models.CharField(max_length=500)),
                ("street", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "address",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=1000, null=True
                        ),
                        size=None,
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("po_box", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "phone",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=200, null=True
                        ),
                        size=None,
                    ),
                ),
                (
                    "email",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=200, null=True
                        ),
                        size=None,
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("chain_name", models.CharField(blank=True, max_length=500, null=True)),
                ("chain_id", models.CharField(blank=True, max_length=500, null=True)),
                ("chain_code", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "city_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="giata.giatacity",
                    ),
                ),
            ],
            options={"db_table": "giata_properties",},
        ),
    ]
