# Generated by Django 5.0.6 on 2024-12-30 11:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0002_alter_giatacity_options_alter_giatacountry_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giataproperties",
            name="address",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1000),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
