# Generated by Django 5.0.6 on 2024-12-30 11:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0003_alter_giataproperties_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giataproperties",
            name="email",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="giataproperties",
            name="phone",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
