# Generated by Django 5.0.6 on 2024-12-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0004_alter_giataproperties_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giataproperties",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="giataproperties",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
