# Generated by Django 5.0.6 on 2024-12-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0005_alter_giataproperties_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giataproperties",
            name="last_updated",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
