# Generated by Django 5.0.6 on 2024-12-31 09:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0006_alter_giataproperties_last_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiataProviderCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                (
                    "provider_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "provider_type",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "provider_code",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "property_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="giata.giataproperties",
                    ),
                ),
            ],
            options={"db_table": "giata_provider_code",},
        ),
    ]
