# Generated by Django 5.0.6 on 2025-01-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0007_giataprovidercode"),
    ]

    operations = [
        migrations.RemoveField(model_name="giataprovidercode", name="provider_code",),
    ]
