# Generated by Django 5.0.6 on 2025-01-01 06:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0008_remove_giataprovidercode_provider_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="giataprovidercode",
            name="provider_code",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
