# Generated by Django 5.0.6 on 2025-01-01 10:02

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0009_giataprovidercode_provider_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiataPropertyImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("image_type", models.CharField(blank=True, max_length=400, null=True)),
                (
                    "image_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "propert_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="giata.giataproperties",
                    ),
                ),
            ],
            options={"db_table": "giata_property_image",},
        ),
    ]
