# Generated by Django 5.0.6 on 2025-01-02 06:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0010_giatapropertyimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiataErrorLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("traceback", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "giata_error_log",},
        ),
        migrations.CreateModel(
            name="GiataFactsheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                (
                    "last_updated",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "property_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="giata.giataproperties",
                    ),
                ),
            ],
            options={"db_table": "giata_factsheet",},
        ),
        migrations.CreateModel(
            name="GiataTexts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("type", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("paragraph", models.TextField(blank=True, null=True)),
                (
                    "propert_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="giata.giataproperties",
                    ),
                ),
            ],
            options={"db_table": "giata_texts",},
        ),
    ]
