# Generated by Django 5.0.6 on 2025-01-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0011_giataerrorlog_giatafactsheet_giatatexts"),
    ]

    operations = [
        migrations.AddField(
            model_name="giataerrorlog",
            name="base_url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="giataerrorlog",
            name="giata_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
