# Generated by Django 5.0.6 on 2025-01-16 04:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0012_giataerrorlog_base_url_giataerrorlog_giata_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="giataproperties", name="chain_code",),
        migrations.RemoveField(model_name="giataproperties", name="chain_id",),
        migrations.RemoveField(model_name="giataproperties", name="chain_name",),
        migrations.CreateModel(
            name="GiataChain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("chain_name", models.CharField(blank=True, max_length=500, null=True)),
                ("chain_id", models.CharField(blank=True, max_length=500, null=True)),
                ("chain_code", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "propert_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="giata.giataproperties",
                    ),
                ),
            ],
            options={"db_table": "giata_chain",},
        ),
    ]
