# Generated by Django 5.0.6 on 2025-01-16 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0013_remove_giataproperties_chain_code_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="giatachain", old_name="propert_id", new_name="property_id",
        ),
    ]
