# Generated by Django 5.0.6 on 2025-01-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0014_rename_propert_id_giatachain_property_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="giatacity",
            name="sync_epoch",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="giatacountry",
            name="sync_epoch",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="giatadestination",
            name="sync_epoch",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="giataproperties",
            name="sync_epoch",
            field=models.BigIntegerField(null=True),
        ),
    ]
