# Generated by Django 5.0.6 on 2025-01-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0015_giatacity_sync_epoch_giatacountry_sync_epoch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giatacity",
            name="sync_epoch",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="giatacountry",
            name="sync_epoch",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="giatadestination",
            name="sync_epoch",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="giataproperties",
            name="sync_epoch",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
