# Generated by Django 5.0.6 on 2025-01-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0016_alter_giatacity_sync_epoch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="giatacity",
            name="tbo_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
