# Generated by Django 5.0.6 on 2025-01-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0017_giatacity_tbo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="giataerrorlog",
            name="des_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="giataerrorlog",
            name="des_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
