# Generated by Django 5.0.6 on 2025-01-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0018_giataerrorlog_des_id_giataerrorlog_des_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="giataerrorlog", name="des_id",),
        migrations.RemoveField(model_name="giataerrorlog", name="des_name",),
        migrations.AddField(
            model_name="giataerrorlog",
            name="variables",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
