# Generated by Django 5.0.6 on 2025-01-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0019_remove_giataerrorlog_des_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="giatacity", name="sync_epoch",),
        migrations.RemoveField(model_name="giatacountry", name="sync_epoch",),
        migrations.RemoveField(model_name="giatadestination", name="sync_epoch",),
        migrations.RemoveField(model_name="giataproperties", name="sync_epoch",),
    ]
