# Generated by Django 5.0.6 on 2025-02-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0020_remove_giatacity_sync_epoch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="giatacity",
            name="lastupdated_epoch",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="giatacountry",
            name="lastupdated_epoch",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="giatadestination",
            name="lastupdated_epoch",
            field=models.BigIntegerField(default=0),
        ),
    ]
