# Generated by Django 5.0.6 on 2025-02-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0021_giatacity_lastupdated_epoch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="giataproperties",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
