# Generated by Django 5.0.6 on 2025-04-16 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("giata", "0022_giataproperties_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="giataerrorlog", old_name="timestamp", new_name="time_date",
        ),
    ]
