# Generated by Django 5.0.6 on 2024-06-20 06:07

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LookupIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("name", models.CharField(max_length=600, unique=True)),
                (
                    "keys",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=600),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("icon_url", models.CharField(max_length=600)),
            ],
            options={"db_table": "lookup_integration",},
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("name", models.CharField(max_length=1000, unique=True)),
                ("icon_url", models.CharField(max_length=600)),
                ("data", models.JSONField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "lookup_integration",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="general.lookupintegration",
                    ),
                ),
            ],
            options={"db_table": "integration",},
        ),
    ]
