# Generated by Django 5.0.6 on 2024-07-02 12:12

from django.db import migrations
from integrations.general.models import Integration, LookupIntegration
from django.contrib.auth import get_user_model

def create_lookup_integration(apps, schema_editor):
    LookupIntegration_model = apps.get_model('general', 'LookupIntegration')
    LookupIntegration_model.objects.create(
        name=LookupIntegration.Keywords.SMTPGO,
        keys=['a'],
        icon_url="dsfsd",
    )

class Migration(migrations.Migration):

    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        # migrations.RunPython(create_lookup_integration)
    ]
