# Generated by Django 5.0.6 on 2024-07-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0002_create_lookup_general_integration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="name",
            field=models.CharField(
                choices=[("smtpgo", "SMTPGO")], max_length=1000, unique=True
            ),
        ),
    ]
