# Generated by Django 5.0.6 on 2024-09-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_integration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='name',
            field=models.CharField(choices=[('integration1', 'integration1')], max_length=1000, unique=True),
        ),
    ]
