# Generated by Django 5.0.6 on 2024-09-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0005_add_lookup_integration_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="name",
            field=models.CharField(
                choices=[("Smtpgo", "Smtpgo")], max_length=1000, unique=True
            ),
        ),
    ]
