# Generated by Django 5.0.6 on 2024-09-10 04:50

from django.db import migrations

def add_default_values(apps, schema_editor):
    general = apps.get_model('general', 'LookupIntegration')
    if not  general.objects.filter(name='Smtpgo'):  
        general.objects.create(name='Smtpgo',keys=["smtp_server", "smtp_port","smtp_username", "smtp_password"], icon_url="https://cdn-images.himalayas.app/4dooqejgn2sccsfdm5ed4ihcfu97")
    # general.objects.create(name='trip_pro',keys=["base_url", "search_access_token","api_provider_code"], icon_url="https://book-staging-bucket.s3.amazonaws.com/media/btob/gallery/WhatsApp_Image_2024-09-05_at_6.22.24_PM.jpeg")
    # supplier.objects.create(name='trip_jack', integeration_type='Flights',keys=["base_url", "api_key","api_provider_code"], icon_url="https://book-staging-bucket.s3.amazonaws.com/media/btob/gallery/WhatsApp_Image_2024-09-05_at_6.22.24_PM.jpeg")


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0006_alter_integration_name"),
    ]

    operations = [
     migrations.RunPython(add_default_values)
    ]
