# Generated by Django 5.0.6 on 2024-09-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0007_auto_create_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lookupintegration",
            name="name",
            field=models.CharField(
                choices=[("Smtpgo", "SMTPGO")], max_length=600, unique=True
            ),
        ),
    ]
