# Generated by Django 5.0.6 on 2024-09-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0008_alter_lookupintegration_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lookupintegration",
            name="name",
            field=models.CharField(
                choices=[("Smtpgo", "Smtpgo")], max_length=600, unique=True
            ),
        ),
    ]
