# Generated by Django 5.0.6 on 2024-09-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0009_alter_lookupintegration_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="name",
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name="lookupintegration",
            name="name",
            field=models.CharField(max_length=600, unique=True),
        ),
    ]
