# Generated by Django 5.0.6 on 2024-09-17 05:29

from django.db import migrations



def add_default_values(apps, schema_editor):
    general = apps.get_model('general', 'LookupIntegration')
    general.objects.create(name='easy-link  backoffice suit',keys=["url", "branch_code","portal_reference_code"], icon_url="https://book-staging-bucket.s3.amazonaws.com/media/gallery/easy-link-logo_swbfscl.png")


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_alter_integration_name_alter_lookupintegration_name'),
    ]

    operations = [
        migrations.RunPython(add_default_values)
    ]


