# Generated by Django 5.0.6 on 2024-10-24 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_auto_20240917_0529'),
        ('users', '0056_organization_rand_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.country'),
        ),
    ]
