# Generated by Django 5.0.6 on 2024-10-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_integration_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
