# Generated by Django 5.0.6 on 2024-11-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_alter_integration_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='lookupintegration',
            options={'ordering': ['-created_at']},
        ),
    ]
