# Generated by Django 5.0.6 on 2024-11-13 07:31

from django.db import migrations


def add_default_values(apps, schema_editor):
    general = apps.get_model('general', 'LookupIntegration')
    general.objects.create(name='razorpay',keys=["api_key","api_secret"], icon_url="https://book-staging-bucket.s3.amazonaws.com/media/btob/gallery/113434735.webp")


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_alter_integration_options_and_more'),
    ]

    operations = [
         migrations.RunPython(add_default_values)
    ]
