# Generated by Django 5.0.6 on 2024-06-20 05:22

from django.db import migrations


def add_default_values(apps, schema_editor):
    pass
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_values),
    ]