# Generated by Django 5.0.6 on 2024-06-20 05:23

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_default_notification_key'),
    ]

    operations = [
    ]
