# Generated by Django 5.0.6 on 2024-06-20 09:32

from django.db import migrations


 
def default_countries(app,schema):
    default_countries = ['India', 'United Kingdom' , 'United States', 'United Arab Emirates', 'Canada']
    country_obj = app.get_model('users', 'Country')
    for country in default_countries:
        obj = country_obj.objects.filter(country_name=country)
        if obj:
            obj.is_active = True
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_country"),
    ]

    operations = [
         migrations.RunPython(default_countries)
    ]
