# Generated by Django 5.0.6 on 2024-06-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_organizationtheme_whitelabel_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="OrganizationTheme",),
    ]
