# Generated by Django 5.0.6 on 2024-06-21 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_delete_organizationtheme"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationTheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("primary_color", models.CharField(max_length=2000, null=True)),
                ("secondary_color", models.CharField(max_length=2000, null=True)),
                ("tertiary_color", models.CharField(max_length=2000, null=True)),
                ("success_color", models.CharField(max_length=2000, null=True)),
                ("failure_color", models.CharField(max_length=2000, null=True)),
                ("sidebar_color", models.CharField(max_length=2000, null=True)),
                ("topbar_color", models.CharField(max_length=2000, null=True)),
                ("background_color", models.CharField(max_length=2000, null=True)),
                ("logo", models.CharField(max_length=2000, null=True)),
                ("loader", models.IntegerField(default=0)),
                (
                    "organization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.organization",
                    ),
                ),
                (
                    "template_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.lookuptemplate",
                    ),
                ),
            ],
            options={"db_table": "organization_theme",},
        ),
    ]
