# Generated by Django 5.0.6 on 2024-07-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_organizationtheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookuppermission',
            name='flight_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lookuppermission',
            name='flight_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lookuppermission',
            name='flight_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lookuppermission',
            name='flight_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='flight_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='flight_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='flight_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='flight_view',
            field=models.BooleanField(default=False),
        ),
    ]
