# Generated by Django 5.0.6 on 2024-07-02 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_organizationtheme"),
    ]

    operations = [
        migrations.DeleteModel(name="Tickets",),
    ]
