# Generated by Django 5.0.6 on 2024-07-02 06:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_delete_tickets"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tickets",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[("Open", "Open"), ("Close", "Close")], max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Register", "New Customer Registration"),
                            (
                                "Limit_Reached",
                                "Customer Inactive - Max Retry Limit Reached",
                            ),
                        ],
                        max_length=400,
                    ),
                ),
                ("data", models.JSONField(null=True)),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
