# Generated by Django 5.0.6 on 2024-07-03 06:09

from django.db import migrations
from django.contrib.auth import get_user_model

def create_new_user(apps, schema_editor):
    user = apps.get_model('users' , 'UserDetails')
    user.objects.create(
        username="newuser",
        email="newuser@example.com",
        phone_number="1234567890",

    )

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_tickets"),
    ]

    operations = [
        migrations.RunPython(create_new_user)
    ]
