# Generated by Django 5.0.6 on 2024-07-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_lookuppermission_flight_delete_and_more"),
        ("users", "0010_create_new_user"),
    ]

    operations = []
