# Generated by Django 5.0.6 on 2024-07-10 05:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_merge_20240703_1722"),
    ]

    operations = [
        migrations.CreateModel(
            name="LookupCountry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("country_name", models.CharField(max_length=200)),
                ("country_code", models.CharField(max_length=300)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"db_table": "lookup_country",},
        ),
        migrations.CreateModel(
            name="LookupAirports",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("name", models.CharField(max_length=300)),
                ("code", models.CharField(max_length=300)),
                ("city", models.CharField(max_length=300)),
                ("index", models.IntegerField()),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.lookupcountry",
                    ),
                ),
            ],
            options={"db_table": "lookup_airports",},
        ),
    ]
