# Generated by Django 5.0.6 on 2024-07-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_lookupcountry_lookupairports"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lookupairports",
            name="city",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="lookupairports",
            name="code",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="lookupairports",
            name="index",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="lookupairports",
            name="name",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
