# Generated by Django 5.0.6 on 2024-07-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_lookupairports_city_alter_lookupairports_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookupairports",
            name="common",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="lookupairports",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="lookupairports",
            name="longitude",
            field=models.FloatField(null=True),
        ),
    ]
