# Generated by Django 5.0.6 on 2024-07-18 12:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_lookupairports_common_lookupairports_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookupairports",
            name="nearest",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=2000), null=True, size=None
            ),
        ),
    ]
