# Generated by Django 5.0.6 on 2024-07-26 05:29

from django.db import migrations

def delete_all_countries(apps, schema_editor):
    organization = apps.get_model('users', 'Organization')
    organization.objects.all().delete()
    
    Country = apps.get_model('users', 'Country')
    countries_deleted, _ = Country.objects.all().delete()
    

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_create_lookup_country"),
    ]

    operations = [
        migrations.RunPython(delete_all_countries),
    ]
