# Generated by Django 5.0.6 on 2024-07-26 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_delete_country_table_values"),
    ]

    operations = [
        migrations.RemoveField(model_name="country", name="calling_code",),
        migrations.RemoveField(model_name="country", name="country_code",),
        migrations.RemoveField(model_name="country", name="country_name",),
        migrations.AddField(
            model_name="country",
            name="currency_symbol",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="country",
            name="lookup",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.lookupcountry",
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(name="country", table=None,),
    ]
