# Generated by Django 5.0.6 on 2024-07-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_remove_country_calling_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookupcountry",
            name="calling_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
