# Generated by Django 5.0.6 on 2024-07-29 10:48

from django.db import migrations

import pycountry
import phonenumbers

def get_calling_code(apps, schema_editor):
    lookupcountry = apps.get_model('users', 'LookupCountry')
    country_instances = lookupcountry.objects.all()
    for country_instance in country_instances:
        try:
            country = pycountry.countries.get(alpha_2=country_instance.country_code)
            if country is None:
                continue
            calling_code = phonenumbers.country_code_for_region(country.alpha_2)
            if calling_code is None:
                continue
            country_instance.calling_code = '+' + str(calling_code)
            country_instance.save()
        except KeyError:
            continue
class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_lookupcountry_calling_code"),
    ]

    operations = [
        migrations.RunPython(get_calling_code),
    ]
