# Generated by Django 5.0.6 on 2024-07-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_create_lookupcountry_callingcode"),
    ]

    operations = [
        migrations.RemoveField(model_name="organization", name="organization_state",),
        migrations.RemoveField(model_name="userdetails", name="base_country",),
        migrations.RemoveField(model_name="userdetails", name="state",),
    ]
