# Generated by Django 5.0.6 on 2024-08-02 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_remove_organization_organization_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="base_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.country",
            ),
        ),
    ]
