# Generated by Django 5.0.6 on 2024-08-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_userdetails_base_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_update",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_update",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_view",
            field=models.BooleanField(default=False),
        ),
    ]
