# Generated by Django 5.0.6 on 2024-08-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0027_rename_accounts_update_lookuppermission_accounts_billing_create_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="company_address",
            new_name="address",
        ),
        migrations.AddField(
            model_name="organization",
            name="iata_or_arc_code",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_iata_or_arc",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="state",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
