# Generated by Django 5.0.6 on 2024-09-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_lookuppermission_control1space1panel_supplier_visa1space1category_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookuporganizationtypes',
            name='name',
            field=models.CharField(choices=[('master', 'master'), ('agency', 'agency'), ('distibutor', 'distributor'), ('enterprises', 'enterprises'), ('out_api', 'out_api'), ('supplier', 'supplier')], max_length=500),
        ),
        migrations.AlterField(
            model_name='lookuproles',
            name='name',
            field=models.CharField(choices=[('super_admin', 'super_admin'), ('admin', 'admin'), ('operations', 'operations'), ('finance', 'finance'), ('sales', 'sales'), ('agency_owner', 'agency_owner'), ('agency_staff', 'agency_staff'), ('distributor_owner', 'distributor_owner'), ('distributor_staff', 'distributor_staff'), ('distributor_agent', 'distributor_agent'), ('out_api', 'out_api'), ('enterprise_owner', 'enterprise_owner'), ('supplier', 'supplier')], max_length=500),
        ),
    ]
