# Generated by Django 5.0.6 on 2024-09-06 05:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_lookuppermission_admin1space1panel_api1space1management_create_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('module', models.TextField()),
                ('erros', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
