# Generated by Django 5.0.6 on 2024-09-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_countrydefault"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countrydefault",
            name="flights",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="countrydefault",
            name="hotels",
            field=models.JSONField(null=True),
        ),
    ]
