# Generated by Django 5.0.6 on 2024-09-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_alter_countrydefault_flights_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="countrydefault",
            name="holiday",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="countrydefault", name="visa", field=models.JSONField(null=True),
        ),
    ]
