# Generated by Django 5.0.6 on 2024-09-12 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0035_countrydefault_holiday_countrydefault_visa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countrydefault",
            name="country_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.country",
            ),
        ),
    ]
