# Generated by Django 5.0.6 on 2024-09-17 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_countrydefault_country_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='account_code',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='easy_link_account_named',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.lookuproles'),
        ),
        migrations.AlterField(
            model_name='lookuporganizationtypes',
            name='name',
            field=models.CharField(choices=[('master', 'master'), ('agency', 'agency'), ('distributor', 'distributor'), ('enterprises', 'enterprises'), ('out_api', 'out_api'), ('supplier', 'supplier')], max_length=500),
        ),
    ]
