# Generated by Django 5.0.6 on 2024-09-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_organization_account_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='account_code',
            new_name='easy_link_account_code',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='easy_link_account_named',
            new_name='easy_link_account_name',
        ),
    ]
