# Generated by Django 5.0.6 on 2024-09-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_errorlogadvanced'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlogadvanced',
            name='device_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='errorlogadvanced',
            name='meta_info',
            field=models.JSONField(null=True),
        ),
    ]
