# Generated by Django 5.0.6 on 2024-09-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_errorlogadvanced_device_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlogadvanced',
            name='os_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='errorlogadvanced',
            name='user_agent',
            field=models.TextField(null=True),
        ),
    ]
