# Generated by Django 5.0.6 on 2024-09-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0041_errorlogadvanced_os_name_errorlogadvanced_user_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_holiday_favourites_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_holiday_favourites_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_holiday_favourites_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_holiday_favourites_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_visa_favourites_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_visa_favourites_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_visa_favourites_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_visa_favourites_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_holiday_favourites_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_holiday_favourites_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_holiday_favourites_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_holiday_favourites_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_visa_favourites_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_visa_favourites_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_visa_favourites_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_visa_favourites_view",
            field=models.BooleanField(default=False),
        ),
    ]
