# Generated by Django 5.0.6 on 2024-09-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_lookuppermission_admin1space1panel_holiday_favourites_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive'), ('pending', 'pending')], default='pending', max_length=2000, null=True),
        ),
    ]
