# Generated by Django 4.2.6 on 2024-09-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0043_organization_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="control1space1panel_markup1space1management_create",
            new_name="admin1space1panel_deal1space1manager_create",
        ),
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="control1space1panel_markup1space1management_delete",
            new_name="admin1space1panel_deal1space1manager_delete",
        ),
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="control1space1panel_markup1space1management_edit",
            new_name="admin1space1panel_deal1space1manager_edit",
        ),
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="control1space1panel_markup1space1management_view",
            new_name="admin1space1panel_deal1space1manager_view",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="control1space1panel_markup1space1management_create",
            new_name="admin1space1panel_deal1space1manager_create",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="control1space1panel_markup1space1management_delete",
            new_name="admin1space1panel_deal1space1manager_delete",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="control1space1panel_markup1space1management_edit",
            new_name="admin1space1panel_deal1space1manager_edit",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="control1space1panel_markup1space1management_view",
            new_name="admin1space1panel_deal1space1manager_view",
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_markup1space1management_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_markup1space1management_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_markup1space1management_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_markup1space1management_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_markup1space1management_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_markup1space1management_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_markup1space1management_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_markup1space1management_view",
            field=models.BooleanField(default=False),
        ),
    ]
