# Generated by Django 4.2.6 on 2024-09-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0044_rename_control1space1panel_markup1space1management_create_lookuppermission_admin1space1panel_deal1sp",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_holiday_queue_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_holiday_queue_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_holiday_queue_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_holiday_queue_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_holiday_queue_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_holiday_queue_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_holiday_queue_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_holiday_queue_view",
            field=models.BooleanField(default=False),
        ),
    ]
