# Generated by Django 5.0.6 on 2024-09-27 09:52

from django.db import migrations


def add_default_values(apps, schema_editor):
    obj = apps.get_model('template', 'LookUpNotificationKeys')
    obj.objects.create(name="Approve_Agency_Master", type="event")

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_lookuppermission_admin1space1panel_holiday_queue_create_and_more'),
    ]

    operations = [
        #  migrations.RunPython(add_default_values)
    ]






