# Generated by Django 5.0.6 on 2024-10-07 11:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0046_auto_20240927_0952"),
    ]
try:
    operations = [
        migrations.CreateModel(
            name="LookupAirline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("name", models.CharField(max_length=500, null=True)),
                ("code", models.CharField(max_length=500, null=True)),
            ],
            options={"db_table": "lookup_airline",},
        ),
    ]
except:
    pass
