# Generated by Django 5.0.6 on 2024-10-08 05:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0047_lookupairline"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryTax",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("tax", models.FloatField(default=0)),
                ("tds", models.FloatField(default=0)),
                (
                    "country_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.country",
                    ),
                ),
            ],
            options={"db_table": "country_tax",},
        ),
    ]
