# Generated by Django 5.0.6 on 2024-10-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_lookupairline'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_client_proxy',
            field=models.BooleanField(default=False),
        ),
    ]
