# Generated by Django 5.0.6 on 2024-10-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_userdetails_is_client_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookuppermission',
            name='operations_client1space1proxy_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lookuppermission',
            name='operations_client1space1proxy_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lookuppermission',
            name='operations_client1space1proxy_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lookuppermission',
            name='operations_client1space1proxy_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='operations_client1space1proxy_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='operations_client1space1proxy_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='operations_client1space1proxy_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='operations_client1space1proxy_view',
            field=models.BooleanField(default=False),
        ),
    ]
