# Generated by Django 5.0.6 on 2024-10-15 09:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_lookuppermission_operations_client1space1proxy_create_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('operation_team_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_team_user', to=settings.AUTH_USER_MODEL)),
                ('proxy_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
