# Generated by Django 5.0.6 on 2024-10-15 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_proxylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxylog',
            name='additional_log',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='proxylog',
            name='end_time',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='proxylog',
            name='end_time_epoch',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='proxylog',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 15, 10, 50, 10, 527556, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proxylog',
            name='start_time_epoch',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='proxylog',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 15, 10, 50, 13, 923531, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proxylog',
            name='valid_till_epoch',
            field=models.BigIntegerField(editable=False, null=True),
        ),
    ]
