# Generated by Django 5.0.6 on 2024-10-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_proxylog_additional_log_proxylog_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proxylog',
            table='proxy_log',
        ),
    ]
