# Generated by Django 5.0.6 on 2024-10-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_alter_proxylog_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxylog',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='proxylog',
            name='valid_till',
            field=models.DateTimeField(null=True),
        ),
    ]
