# Generated by Django 5.0.6 on 2024-10-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_alter_proxylog_start_time_alter_proxylog_valid_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='rand_code',
            field=models.TextField(null=True),
        ),
    ]
