# Generated by Django 5.0.6 on 2024-10-29 06:49

from django.db import migrations




def add_default_values(apps, schema_editor):
    # obj = apps.get_model('template', 'LookUpNotificationKeys')
    obj = apps.get_model('integrations.template', 'LookUpNotificationKeys')

    obj.objects.create(name="APPROVE_AGENCY_MASTER", type="event")

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_organization_rand_code'),
    ]

    operations = [
         migrations.RunPython(add_default_values)
    ]
