# Generated by Django 5.0.6 on 2024-10-30 17:01

from django.db import migrations

def add_default_values(apps, schema_editor):
    obj = apps.get_model('template', 'LookUpNotificationKeys')
    obj.objects.create(name="FLIGHT_CANCELLATION_REQUEST", type="event")
    obj.objects.create(name="request_date", type="memory")
    obj.objects.create(name="booking_reference", type="memory")
    obj.objects.create(name="flight_segments", type="memory")
    obj.objects.create(name="passenger_list", type="memory")
    obj.objects.create(name="cancellation_reason", type="memory")
    obj.objects.create(name="error_message", type="memory")
    obj.objects.create(name="FLIGHT_BOOKING_FAILED", type="event")
    
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20241029_0649'),
    ]

    operations = [
        migrations.RunPython(add_default_values)
    ]
