# Generated by Django 5.0.6 on 2024-10-31 09:52

from django.db import migrations
def add_default_values(apps, schema_editor):
    obj = apps.get_model('template', 'LookUpNotificationKeys')
    obj.objects.create(name="FLIGHT_BOOKING_MODIFICATION", type="event")

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_auto_20241030_1701'),
    ]

    operations = [
         migrations.RunPython(add_default_values)
    ]
