# Generated by Django 5.0.6 on 2024-10-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_auto_20241031_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lookuppermission',
            old_name='operations_import1space1and1space1ticketing_create',
            new_name='operations_import1space1pnr_create',
        ),
        migrations.RenameField(
            model_name='lookuppermission',
            old_name='operations_import1space1and1space1ticketing_delete',
            new_name='operations_import1space1pnr_delete',
        ),
        migrations.RenameField(
            model_name='lookuppermission',
            old_name='operations_import1space1and1space1ticketing_edit',
            new_name='operations_import1space1pnr_edit',
        ),
        migrations.RenameField(
            model_name='lookuppermission',
            old_name='operations_import1space1and1space1ticketing_view',
            new_name='operations_import1space1pnr_view',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='operations_import1space1and1space1ticketing_create',
            new_name='operations_import1space1pnr_create',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='operations_import1space1and1space1ticketing_delete',
            new_name='operations_import1space1pnr_delete',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='operations_import1space1and1space1ticketing_edit',
            new_name='operations_import1space1pnr_edit',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='operations_import1space1and1space1ticketing_view',
            new_name='operations_import1space1pnr_view',
        ),
        migrations.AddField(
            model_name='lookuppermission',
            name='operations_ofline1space1ticketing_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lookuppermission',
            name='operations_ofline1space1ticketing_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lookuppermission',
            name='operations_ofline1space1ticketing_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lookuppermission',
            name='operations_ofline1space1ticketing_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='operations_ofline1space1ticketing_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='operations_ofline1space1ticketing_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='operations_ofline1space1ticketing_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='operations_ofline1space1ticketing_view',
            field=models.BooleanField(default=False),
        ),
    ]
