# Generated by Django 5.0.6 on 2024-10-31 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_rename_operations_import1space1and1space1ticketing_create_lookuppermission_operations_import1space1p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lookuppermission',
            old_name='operations_ofline1space1ticketing_create',
            new_name='operations_offline1space1ticketing_create',
        ),
        migrations.RenameField(
            model_name='lookuppermission',
            old_name='operations_ofline1space1ticketing_delete',
            new_name='operations_offline1space1ticketing_delete',
        ),
        migrations.RenameField(
            model_name='lookuppermission',
            old_name='operations_ofline1space1ticketing_edit',
            new_name='operations_offline1space1ticketing_edit',
        ),
        migrations.RenameField(
            model_name='lookuppermission',
            old_name='operations_ofline1space1ticketing_view',
            new_name='operations_offline1space1ticketing_view',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='operations_ofline1space1ticketing_create',
            new_name='operations_offline1space1ticketing_create',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='operations_ofline1space1ticketing_delete',
            new_name='operations_offline1space1ticketing_delete',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='operations_ofline1space1ticketing_edit',
            new_name='operations_offline1space1ticketing_edit',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='operations_ofline1space1ticketing_view',
            new_name='operations_offline1space1ticketing_view',
        ),
    ]
