# Generated by Django 5.0.6 on 2024-10-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0061_rename_operations_ofline1space1ticketing_create_lookuppermission_operations_offline1space1ticketing_",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="countrydefault",
            name="flights",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="countrydefault",
            name="holiday",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="countrydefault",
            name="hotels",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="countrydefault",
            name="visa",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
