# Generated by Django 5.0.6 on 2024-10-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_alter_countrydefault_flights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='btob/gallery'),
        ),
    ]
