# Generated by Django 5.0.6 on 2024-11-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_organization_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['-created_at']},
        ),
    ]
