# Generated by Django 5.0.6 on 2024-11-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_alter_organization_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxylog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='userdetails',
            name='user_internal_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
