# Generated by Django 5.0.6 on 2024-11-07 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_lookuppermission_admin1space1panel_visa_category_create_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lookuppermission',
            old_name='admin1space1panel_holiday_queue_create',
            new_name='admin1space1panel_holiday_theme_create',
        ),
        migrations.RenameField(
            model_name='lookuppermission',
            old_name='admin1space1panel_holiday_queue_delete',
            new_name='admin1space1panel_holiday_theme_delete',
        ),
        migrations.RenameField(
            model_name='lookuppermission',
            old_name='admin1space1panel_holiday_queue_edit',
            new_name='admin1space1panel_holiday_theme_edit',
        ),
        migrations.RenameField(
            model_name='lookuppermission',
            old_name='admin1space1panel_holiday_queue_view',
            new_name='admin1space1panel_holiday_theme_view',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='admin1space1panel_holiday_queue_create',
            new_name='admin1space1panel_holiday_theme_create',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='admin1space1panel_holiday_queue_delete',
            new_name='admin1space1panel_holiday_theme_delete',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='admin1space1panel_holiday_queue_edit',
            new_name='admin1space1panel_holiday_theme_edit',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='admin1space1panel_holiday_queue_view',
            new_name='admin1space1panel_holiday_theme_view',
        ),
    ]
