# Generated by Django 5.0.6 on 2024-11-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_rename_admin1space1panel_holiday_queue_create_lookuppermission_admin1space1panel_holiday_theme_creat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='user_internal_id',
            new_name='user_external_id',
        ),
    ]
