# Generated by Django 5.0.6 on 2024-11-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0068_rename_user_internal_id_userdetails_user_external_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="countrydefault", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="countrytax", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="lookupairline", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="lookupairports", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="lookupcountry", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="lookuporganizationtypes", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="lookuppermission", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="lookuproles", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="notificationtemplate",
            options={"managed": False, "ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="organizationtheme", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="otpdetails", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="userdetails", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="usergroup", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="whitelabel", options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="admin1space1panel_holiday_theme_create",
            new_name="admin1space1panel_holiday_queue_create",
        ),
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="admin1space1panel_holiday_theme_delete",
            new_name="admin1space1panel_holiday_queue_delete",
        ),
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="admin1space1panel_holiday_theme_edit",
            new_name="admin1space1panel_holiday_queue_edit",
        ),
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="admin1space1panel_holiday_theme_view",
            new_name="admin1space1panel_holiday_queue_view",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="admin1space1panel_holiday_theme_create",
            new_name="admin1space1panel_holiday_queue_create",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="admin1space1panel_holiday_theme_delete",
            new_name="admin1space1panel_holiday_queue_delete",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="admin1space1panel_holiday_theme_edit",
            new_name="admin1space1panel_holiday_queue_edit",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="admin1space1panel_holiday_theme_view",
            new_name="admin1space1panel_holiday_queue_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="admin1space1panel_visa_category_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="admin1space1panel_visa_category_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="admin1space1panel_visa_category_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="admin1space1panel_visa_category_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="admin1space1panel_visa_products_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="admin1space1panel_visa_products_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="admin1space1panel_visa_products_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="admin1space1panel_visa_products_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="admin1space1panel_visa_type_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="admin1space1panel_visa_type_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="admin1space1panel_visa_type_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="admin1space1panel_visa_type_view",
        ),
        migrations.RemoveField(
            model_name="permission", name="admin1space1panel_visa_category_create",
        ),
        migrations.RemoveField(
            model_name="permission", name="admin1space1panel_visa_category_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="admin1space1panel_visa_category_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="admin1space1panel_visa_category_view",
        ),
        migrations.RemoveField(
            model_name="permission", name="admin1space1panel_visa_products_create",
        ),
        migrations.RemoveField(
            model_name="permission", name="admin1space1panel_visa_products_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="admin1space1panel_visa_products_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="admin1space1panel_visa_products_view",
        ),
        migrations.RemoveField(
            model_name="permission", name="admin1space1panel_visa_type_create",
        ),
        migrations.RemoveField(
            model_name="permission", name="admin1space1panel_visa_type_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="admin1space1panel_visa_type_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="admin1space1panel_visa_type_view",
        ),
        migrations.RemoveField(model_name="userdetails", name="user_external_id",),
    ]
