# Generated by Django 5.0.6 on 2024-11-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_alter_countrydefault_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_external_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
