# Generated by Django 5.0.6 on 2024-11-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_lookuppermission_admin1space1panel_supplier1space1deal1space1manager_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookuppermission',
            name='operations_queas_cancelled1space1bookings_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lookuppermission',
            name='operations_queas_cancelled1space1bookings_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lookuppermission',
            name='operations_queas_cancelled1space1bookings_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lookuppermission',
            name='operations_queas_cancelled1space1bookings_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='operations_queas_cancelled1space1bookings_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='operations_queas_cancelled1space1bookings_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='operations_queas_cancelled1space1bookings_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='operations_queas_cancelled1space1bookings_view',
            field=models.BooleanField(default=False),
        ),
    ]
