# Generated by Django 5.0.6 on 2024-11-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0073_lookuppermission_operations_queas_cancelled1space1bookings_create_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_booking1space1history_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_booking1space1history_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="operations_booking1space1history_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="operations_booking1space1history_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="operations_queas_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="operations_queas_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="operations_queas_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_failed1space1bookings_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_failed1space1bookings_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_failed1space1bookings_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_failed1space1bookings_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_hold1space1bookings_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_hold1space1bookings_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_hold1space1bookings_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_hold1space1bookings_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_passenger1space1calender_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_passenger1space1calender_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_passenger1space1calender_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_passenger1space1calender_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="operations_queas_view",
        ),
    ]
