# Generated by Django 5.0.6 on 2024-11-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0076_lookuppermission_flight_search_create_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookuppermission",
            name="accounts_branch1space1allocation_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="accounts_branch1space1allocation_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="accounts_branch1space1allocation_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="accounts_branch1space1allocation_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="accounts_branch1space1allocation_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="accounts_branch1space1allocation_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="accounts_branch1space1allocation_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="accounts_branch1space1allocation_view",
            field=models.BooleanField(default=False),
        ),
    ]
