# Generated by Django 5.0.6 on 2024-11-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0078_organization_easy_link_billing_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization", name="easy_link_billing_account",
        ),
    ]
