# Generated by Django 5.0.6 on 2024-11-21 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0015_auto_20241113_0731"),
        ("users", "0079_remove_organization_easy_link_billing_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="easy_link_billing_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="general.integration",
            ),
        ),
    ]
