# Generated by Django 5.0.6 on 2024-11-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0080_organization_easy_link_billing_account"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="admin1space1panel_markup1space1management_create",
            new_name="flight_queas_cancelled1space1bookings_create",
        ),
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="admin1space1panel_markup1space1management_delete",
            new_name="flight_queas_cancelled1space1bookings_delete",
        ),
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="admin1space1panel_markup1space1management_edit",
            new_name="flight_queas_cancelled1space1bookings_edit",
        ),
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="admin1space1panel_markup1space1management_view",
            new_name="flight_queas_cancelled1space1bookings_view",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="admin1space1panel_markup1space1management_create",
            new_name="flight_queas_cancelled1space1bookings_create",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="admin1space1panel_markup1space1management_delete",
            new_name="flight_queas_cancelled1space1bookings_delete",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="admin1space1panel_markup1space1management_edit",
            new_name="flight_queas_cancelled1space1bookings_edit",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="admin1space1panel_markup1space1management_view",
            new_name="flight_queas_cancelled1space1bookings_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="control1space1panel_supplier_holidays1space1products_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="control1space1panel_supplier_holidays1space1products_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="control1space1panel_supplier_holidays1space1products_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="control1space1panel_supplier_holidays1space1products_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="control1space1panel_supplier_visa1space1category_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="control1space1panel_supplier_visa1space1category_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="control1space1panel_supplier_visa1space1category_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="control1space1panel_supplier_visa1space1category_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="control1space1panel_supplier_visa1space1products_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="control1space1panel_supplier_visa1space1products_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="control1space1panel_supplier_visa1space1products_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="control1space1panel_supplier_visa1space1products_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="control1space1panel_supplier_visa1space1type_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="control1space1panel_supplier_visa1space1type_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="control1space1panel_supplier_visa1space1type_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="control1space1panel_supplier_visa1space1type_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_booking1space1for1space1agency_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_booking1space1for1space1agency_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_booking1space1for1space1agency_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_booking1space1for1space1agency_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_cancelled1space1bookings_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_cancelled1space1bookings_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_cancelled1space1bookings_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_cancelled1space1bookings_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_confirmed1space1bookings_cancellation1space1request_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_confirmed1space1bookings_cancellation1space1request_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_confirmed1space1bookings_cancellation1space1request_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_confirmed1space1bookings_cancellation1space1request_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_confirmed1space1bookings_change1space1request_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_confirmed1space1bookings_change1space1request_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_confirmed1space1bookings_change1space1request_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_confirmed1space1bookings_change1space1request_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_confirmed1space1bookings_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_confirmed1space1bookings_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_confirmed1space1bookings_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_queas_confirmed1space1bookings_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="reports_logs1space1search1space1errors_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="reports_logs1space1search1space1errors_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="reports_logs1space1search1space1errors_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="reports_logs1space1search1space1errors_view",
        ),
        migrations.RemoveField(model_name="lookuppermission", name="settings_create",),
        migrations.RemoveField(model_name="lookuppermission", name="settings_delete",),
        migrations.RemoveField(model_name="lookuppermission", name="settings_edit",),
        migrations.RemoveField(
            model_name="lookuppermission", name="settings_integrations_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="settings_integrations_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="settings_integrations_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="settings_integrations_general_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="settings_integrations_general_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="settings_integrations_general_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="settings_integrations_general_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="settings_integrations_notification_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="settings_integrations_notification_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="settings_integrations_notification_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="settings_integrations_notification_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="settings_integrations_supplier_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="settings_integrations_supplier_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="settings_integrations_supplier_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="settings_integrations_supplier_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="settings_integrations_template_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="settings_integrations_template_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="settings_integrations_template_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="settings_integrations_template_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="settings_integrations_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="settings_teams_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="settings_teams_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="settings_teams_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="settings_teams_view",
        ),
        migrations.RemoveField(model_name="lookuppermission", name="settings_view",),
        migrations.RemoveField(
            model_name="permission",
            name="control1space1panel_supplier_holidays1space1products_create",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="control1space1panel_supplier_holidays1space1products_delete",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="control1space1panel_supplier_holidays1space1products_edit",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="control1space1panel_supplier_holidays1space1products_view",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="control1space1panel_supplier_visa1space1category_create",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="control1space1panel_supplier_visa1space1category_delete",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="control1space1panel_supplier_visa1space1category_edit",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="control1space1panel_supplier_visa1space1category_view",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="control1space1panel_supplier_visa1space1products_create",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="control1space1panel_supplier_visa1space1products_delete",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="control1space1panel_supplier_visa1space1products_edit",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="control1space1panel_supplier_visa1space1products_view",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="control1space1panel_supplier_visa1space1type_create",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="control1space1panel_supplier_visa1space1type_delete",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="control1space1panel_supplier_visa1space1type_edit",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="control1space1panel_supplier_visa1space1type_view",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_booking1space1for1space1agency_create",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_booking1space1for1space1agency_delete",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_booking1space1for1space1agency_edit",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_booking1space1for1space1agency_view",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_booking1space1history_create",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_booking1space1history_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_booking1space1history_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_booking1space1history_view",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_cancelled1space1bookings_create",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_cancelled1space1bookings_delete",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_cancelled1space1bookings_edit",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_cancelled1space1bookings_view",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_confirmed1space1bookings_cancellation1space1request_create",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_confirmed1space1bookings_cancellation1space1request_delete",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_confirmed1space1bookings_cancellation1space1request_edit",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_confirmed1space1bookings_cancellation1space1request_view",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_confirmed1space1bookings_change1space1request_create",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_confirmed1space1bookings_change1space1request_delete",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_confirmed1space1bookings_change1space1request_edit",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_confirmed1space1bookings_change1space1request_view",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_confirmed1space1bookings_create",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_confirmed1space1bookings_delete",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_confirmed1space1bookings_edit",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_confirmed1space1bookings_view",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_queas_create",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_queas_delete",
        ),
        migrations.RemoveField(model_name="permission", name="operations_queas_edit",),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_failed1space1bookings_create",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_failed1space1bookings_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_queas_failed1space1bookings_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_queas_failed1space1bookings_view",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_queas_hold1space1bookings_create",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_queas_hold1space1bookings_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_queas_hold1space1bookings_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_queas_hold1space1bookings_view",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_passenger1space1calender_create",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_passenger1space1calender_delete",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_passenger1space1calender_edit",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="operations_queas_passenger1space1calender_view",
        ),
        migrations.RemoveField(model_name="permission", name="operations_queas_view",),
        migrations.RemoveField(
            model_name="permission",
            name="reports_logs1space1search1space1errors_create",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="reports_logs1space1search1space1errors_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="reports_logs1space1search1space1errors_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="reports_logs1space1search1space1errors_view",
        ),
        migrations.RemoveField(model_name="permission", name="settings_create",),
        migrations.RemoveField(model_name="permission", name="settings_delete",),
        migrations.RemoveField(model_name="permission", name="settings_edit",),
        migrations.RemoveField(
            model_name="permission", name="settings_integrations_create",
        ),
        migrations.RemoveField(
            model_name="permission", name="settings_integrations_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="settings_integrations_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="settings_integrations_general_create",
        ),
        migrations.RemoveField(
            model_name="permission", name="settings_integrations_general_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="settings_integrations_general_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="settings_integrations_general_view",
        ),
        migrations.RemoveField(
            model_name="permission", name="settings_integrations_notification_create",
        ),
        migrations.RemoveField(
            model_name="permission", name="settings_integrations_notification_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="settings_integrations_notification_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="settings_integrations_notification_view",
        ),
        migrations.RemoveField(
            model_name="permission", name="settings_integrations_supplier_create",
        ),
        migrations.RemoveField(
            model_name="permission", name="settings_integrations_supplier_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="settings_integrations_supplier_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="settings_integrations_supplier_view",
        ),
        migrations.RemoveField(
            model_name="permission", name="settings_integrations_template_create",
        ),
        migrations.RemoveField(
            model_name="permission", name="settings_integrations_template_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="settings_integrations_template_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="settings_integrations_template_view",
        ),
        migrations.RemoveField(
            model_name="permission", name="settings_integrations_view",
        ),
        migrations.RemoveField(model_name="permission", name="settings_teams_create",),
        migrations.RemoveField(model_name="permission", name="settings_teams_delete",),
        migrations.RemoveField(model_name="permission", name="settings_teams_edit",),
        migrations.RemoveField(model_name="permission", name="settings_teams_view",),
        migrations.RemoveField(model_name="permission", name="settings_view",),
    ]
