# Generated by Django 5.0.6 on 2024-11-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0081_rename_admin1space1panel_markup1space1management_create_lookuppermission_flight_queas_cancelled1spac",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lookuppermission",
            name="admin1space1panel_deal1space1manager_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="admin1space1panel_deal1space1manager_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="admin1space1panel_deal1space1manager_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="admin1space1panel_deal1space1manager_view",
        ),
        migrations.RemoveField(
            model_name="permission", name="admin1space1panel_deal1space1manager_create",
        ),
        migrations.RemoveField(
            model_name="permission", name="admin1space1panel_deal1space1manager_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="admin1space1panel_deal1space1manager_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="admin1space1panel_deal1space1manager_view",
        ),
    ]
