# Generated by Django 5.0.6 on 2024-11-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0082_remove_lookuppermission_admin1space1panel_deal1space1manager_create_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_customer1space1deal1space1manager_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_customer1space1deal1space1manager_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_customer1space1deal1space1manager_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_customer1space1deal1space1manager_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_customer1space1deal1space1manager_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_customer1space1deal1space1manager_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_customer1space1deal1space1manager_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_customer1space1deal1space1manager_view",
            field=models.BooleanField(default=False),
        ),
    ]
