# Generated by Django 5.0.6 on 2024-11-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0083_lookuppermission_admin1space1panel_customer1space1deal1space1manager_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='support_email',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='support_phone',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='virtual_ac_no',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
