# Generated by Django 5.0.6 on 2024-11-26 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0083_lookuppermission_admin1space1panel_customer1space1deal1space1manager_create_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_offline1space1ticketing_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_offline1space1ticketing_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_offline1space1ticketing_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_offline1space1ticketing_view",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_offline1space1ticketing_create",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_offline1space1ticketing_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_offline1space1ticketing_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_offline1space1ticketing_view",
        ),
    ]
