# Generated by Django 5.0.6 on 2024-11-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0084_remove_lookuppermission_operations_offline1space1ticketing_create_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lookuppermission",
            name="accounts_offline1space1ticketing_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="accounts_offline1space1ticketing_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="accounts_offline1space1ticketing_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="accounts_offline1space1ticketing_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="accounts_offline1space1ticketing_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="accounts_offline1space1ticketing_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="accounts_offline1space1ticketing_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="accounts_offline1space1ticketing_view",
            field=models.BooleanField(default=False),
        ),
    ]
