# Generated by Django 5.0.6 on 2024-11-26 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_organization_support_email_and_more'),
        ('users', '0086_lookuppermission_holidays_enquiry1space1history_create_and_more'),
    ]

    operations = [
    ]
