# Generated by Django 5.0.6 on 2024-11-27 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0087_merge_20241126_0537"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="sales_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_as_sales_agent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
