# Generated by Django 5.0.6 on 2024-12-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0088_organization_sales_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorlog',
            options={'ordering': ['-created_at']},
        ),
    ]
