# Generated by Django 5.0.6 on 2024-12-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0089_alter_errorlog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="easy_link_billing_code",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
