# Generated by Django 5.0.6 on 2024-12-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0090_organization_easy_link_billing_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookuppermission",
            name="accounts_ledger1space1and1space1statement_agent1space1statement_create",
            field=models.BooleanField(
                db_column="agent_statement_create", default=False
            ),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="accounts_ledger1space1and1space1statement_agent1space1statement_delete",
            field=models.BooleanField(
                db_column="agent_statement_delete", default=False
            ),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="accounts_ledger1space1and1space1statement_agent1space1statement_edit",
            field=models.BooleanField(db_column="agent_statement_edit", default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="accounts_ledger1space1and1space1statement_agent1space1statement_view",
            field=models.BooleanField(db_column="agent_statement_view", default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="accounts_ledger1space1and1space1statement_agent1space1statement_create",
            field=models.BooleanField(
                db_column="agent_statement_create", default=False
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="accounts_ledger1space1and1space1statement_agent1space1statement_delete",
            field=models.BooleanField(
                db_column="agent_statement_delete", default=False
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="accounts_ledger1space1and1space1statement_agent1space1statement_edit",
            field=models.BooleanField(db_column="agent_statement_edit", default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="accounts_ledger1space1and1space1statement_agent1space1statement_view",
            field=models.BooleanField(db_column="agent_statement_view", default=False),
        ),
    ]
