# Generated by Django 5.0.6 on 2024-12-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0091_lookuppermission_accounts_ledger1space1and1space1statement_agent1space1statement_create_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="organization_zipcode",
            field=models.CharField(blank=True, null=True),
        ),
    ]
