# Generated by Django 5.0.6 on 2024-12-12 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0092_alter_organization_organization_zipcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_details",
                to="users.organization",
            ),
        ),
    ]
