# Generated by Django 5.0.6 on 2024-12-13 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0093_alter_userdetails_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_details",
                to="users.organization",
            ),
        ),
    ]
