# Generated by Django 5.0.6 on 2024-12-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0094_alter_userdetails_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='last_login_ip',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
