# Generated by Django 5.0.6 on 2024-12-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0095_userdetails_last_login_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='last_login_ip',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
