# Generated by Django 5.0.6 on 2024-12-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0096_alter_userdetails_last_login_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookuppermission",
            name="accounts_credit1space1notes_agent_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="accounts_credit1space1notes_agent_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="accounts_credit1space1notes_agent_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="accounts_credit1space1notes_agent_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="accounts_credit1space1notes_own_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="accounts_credit1space1notes_own_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="accounts_credit1space1notes_own_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="accounts_credit1space1notes_own_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="accounts_credit1space1notes_agent_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="accounts_credit1space1notes_agent_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="accounts_credit1space1notes_agent_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="accounts_credit1space1notes_agent_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="accounts_credit1space1notes_own_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="accounts_credit1space1notes_own_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="accounts_credit1space1notes_own_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="accounts_credit1space1notes_own_view",
            field=models.BooleanField(default=False),
        ),
    ]
