# Generated by Django 5.0.6 on 2024-12-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0097_lookuppermission_accounts_credit1space1notes_agent_create_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lookuppermission",
            name="flight_queas_cancelled1space1bookings_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="flight_queas_cancelled1space1bookings_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="flight_queas_cancelled1space1bookings_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="flight_queas_cancelled1space1bookings_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="flight_queas_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="flight_queas_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="flight_queas_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="flight_queas_failed1space1bookings_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="flight_queas_failed1space1bookings_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="flight_queas_failed1space1bookings_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="flight_queas_failed1space1bookings_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="flight_queas_hold1space1bookings_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="flight_queas_hold1space1bookings_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="flight_queas_hold1space1bookings_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="flight_queas_hold1space1bookings_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="flight_queas_passenger1space1calender_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="flight_queas_passenger1space1calender_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="flight_queas_passenger1space1calender_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="flight_queas_passenger1space1calender_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="flight_queas_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_holidays1space1queas_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="operations_holidays1space1queas_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="operations_holidays1space1queas_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="operations_holidays1space1queas_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="operations_visa1space1queas_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="operations_visa1space1queas_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="operations_visa1space1queas_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="operations_visa1space1queas_view",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="flight_queas_cancelled1space1bookings_create",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="flight_queas_cancelled1space1bookings_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="flight_queas_cancelled1space1bookings_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="flight_queas_cancelled1space1bookings_view",
        ),
        migrations.RemoveField(model_name="permission", name="flight_queas_create",),
        migrations.RemoveField(model_name="permission", name="flight_queas_delete",),
        migrations.RemoveField(model_name="permission", name="flight_queas_edit",),
        migrations.RemoveField(
            model_name="permission", name="flight_queas_failed1space1bookings_create",
        ),
        migrations.RemoveField(
            model_name="permission", name="flight_queas_failed1space1bookings_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="flight_queas_failed1space1bookings_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="flight_queas_failed1space1bookings_view",
        ),
        migrations.RemoveField(
            model_name="permission", name="flight_queas_hold1space1bookings_create",
        ),
        migrations.RemoveField(
            model_name="permission", name="flight_queas_hold1space1bookings_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="flight_queas_hold1space1bookings_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="flight_queas_hold1space1bookings_view",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="flight_queas_passenger1space1calender_create",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="flight_queas_passenger1space1calender_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="flight_queas_passenger1space1calender_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="flight_queas_passenger1space1calender_view",
        ),
        migrations.RemoveField(model_name="permission", name="flight_queas_view",),
        migrations.RemoveField(
            model_name="permission", name="operations_holidays1space1queas_create",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_holidays1space1queas_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_holidays1space1queas_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_holidays1space1queas_view",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_visa1space1queas_create",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_visa1space1queas_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_visa1space1queas_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="operations_visa1space1queas_view",
        ),
    ]
