# Generated by Django 5.0.6 on 2024-12-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0099_lookuppermission_flight_queues_cancelled1space1bookings_create_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="markup",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
