# Generated by Django 5.0.6 on 2024-12-31 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0100_userdetails_markup"),
    ]

    operations = [
        migrations.RemoveField(model_name="userdetails", name="zip_code",),
    ]
