# Generated by Django 5.0.6 on 2024-12-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0101_remove_userdetails_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="zip_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
