# Generated by Django 5.0.6 on 2025-01-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0102_userdetails_zip_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lookuppermission",
            name="reports_agency1space1registrations_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="reports_agency1space1registrations_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="reports_agency1space1registrations_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="reports_agency1space1registrations_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="reports_product1space1wise1space1daily1space1sale_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="reports_product1space1wise1space1daily1space1sale_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="reports_product1space1wise1space1daily1space1sale_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="reports_product1space1wise1space1daily1space1sale_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="reports_product1space1wise1space1monthly1space1sale_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="reports_product1space1wise1space1monthly1space1sale_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="reports_product1space1wise1space1monthly1space1sale_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission",
            name="reports_product1space1wise1space1monthly1space1sale_view",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="reports_travel1space1calendar_create",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="reports_travel1space1calendar_delete",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="reports_travel1space1calendar_edit",
        ),
        migrations.RemoveField(
            model_name="lookuppermission", name="reports_travel1space1calendar_view",
        ),
        migrations.RemoveField(
            model_name="permission", name="reports_agency1space1registrations_create",
        ),
        migrations.RemoveField(
            model_name="permission", name="reports_agency1space1registrations_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="reports_agency1space1registrations_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="reports_agency1space1registrations_view",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="reports_product1space1wise1space1daily1space1sale_create",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="reports_product1space1wise1space1daily1space1sale_delete",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="reports_product1space1wise1space1daily1space1sale_edit",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="reports_product1space1wise1space1daily1space1sale_view",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="reports_product1space1wise1space1monthly1space1sale_create",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="reports_product1space1wise1space1monthly1space1sale_delete",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="reports_product1space1wise1space1monthly1space1sale_edit",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="reports_product1space1wise1space1monthly1space1sale_view",
        ),
        migrations.RemoveField(
            model_name="permission", name="reports_travel1space1calendar_create",
        ),
        migrations.RemoveField(
            model_name="permission", name="reports_travel1space1calendar_delete",
        ),
        migrations.RemoveField(
            model_name="permission", name="reports_travel1space1calendar_edit",
        ),
        migrations.RemoveField(
            model_name="permission", name="reports_travel1space1calendar_view",
        ),
    ]
