# Generated by Django 5.0.6 on 2025-01-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0103_remove_lookuppermission_reports_agency1space1registrations_create_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lookuppermission",
            name="reports_sales1space1performance_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="reports_sales1space1performance_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="reports_sales1space1performance_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="reports_sales1space1performance_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="reports_sales1space1performance_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="reports_sales1space1performance_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="reports_sales1space1performance_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="reports_sales1space1performance_view",
            field=models.BooleanField(default=False),
        ),
    ]
