# Generated by Django 5.0.6 on 2025-01-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0104_lookuppermission_reports_sales1space1performance_create_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="userdetails", name="markup",),
    ]
