# Generated by Django 5.0.6 on 2025-01-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0105_remove_userdetails_markup"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="dom_markup",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="int_markup",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
