# Generated by Django 5.0.6 on 2025-01-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0106_userdetails_dom_markup_userdetails_int_markup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lookuproles",
            name="name",
            field=models.CharField(
                choices=[
                    ("super_admin", "super_admin"),
                    ("admin", "admin"),
                    ("operations", "operations"),
                    ("finance", "finance"),
                    ("sales", "sales"),
                    ("agency_owner", "agency_owner"),
                    ("agency_staff", "agency_staff"),
                    ("distributor_owner", "distributor_owner"),
                    ("distributor_staff", "distributor_staff"),
                    ("distributor_agent", "distributor_agent"),
                    ("out_api_owner", "out_api_owner"),
                    ("out_api_staff", "out_api_staff"),
                    ("enterprise_owner", "enterprise_owner"),
                    ("supplier", "supplier"),
                ],
                max_length=500,
            ),
        ),
    ]
