# Generated by Django 5.0.6 on 2025-01-10 07:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0107_alter_lookuproles_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutApiDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Pending", "Pending"),
                        ],
                        max_length=200,
                    ),
                ),
                ("token", models.CharField(max_length=1000)),
                ("exp_time_epoch", models.BigIntegerField(editable=False, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.organization",
                    ),
                ),
            ],
            options={"db_table": "out_api_detail", "ordering": ["-created_at"],},
        ),
    ]
