# Generated by Django 5.0.6 on 2025-01-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0108_outapidetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outapidetail",
            name="exp_time_epoch",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="outapidetail",
            name="token",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
