# Generated by Django 5.0.6 on 2025-01-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0109_alter_outapidetail_exp_time_epoch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outapidetail",
            name="exp_time_epoch",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
