# Generated by Django 5.0.6 on 2025-01-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0110_alter_outapidetail_exp_time_epoch"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookuppermission",
            name="control1space1panel_outapi1space1management_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="control1space1panel_outapi1space1management_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="control1space1panel_outapi1space1management_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="control1space1panel_outapi1space1management_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="control1space1panel_outapi1space1management_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="control1space1panel_outapi1space1management_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="control1space1panel_outapi1space1management_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="control1space1panel_outapi1space1management_view",
            field=models.BooleanField(default=False),
        ),
    ]
