# Generated by Django 5.0.6 on 2025-01-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0111_lookuppermission_control1space1panel_outapi1space1management_create_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="lookuptheme", name="failure_color",),
        migrations.RemoveField(model_name="lookuptheme", name="loader",),
        migrations.RemoveField(model_name="lookuptheme", name="logo",),
        migrations.RemoveField(model_name="lookuptheme", name="primary_color",),
        migrations.RemoveField(model_name="lookuptheme", name="secondary_color",),
        migrations.RemoveField(model_name="lookuptheme", name="sidebar_color",),
        migrations.RemoveField(model_name="lookuptheme", name="success_color",),
        migrations.RemoveField(model_name="lookuptheme", name="template",),
        migrations.RemoveField(model_name="lookuptheme", name="tertiary_color",),
        migrations.RemoveField(model_name="lookuptheme", name="topbar_color",),
        migrations.RemoveField(model_name="organizationtheme", name="failure_color",),
        migrations.RemoveField(model_name="organizationtheme", name="loader",),
        migrations.RemoveField(model_name="organizationtheme", name="logo",),
        migrations.RemoveField(model_name="organizationtheme", name="primary_color",),
        migrations.RemoveField(model_name="organizationtheme", name="secondary_color",),
        migrations.RemoveField(model_name="organizationtheme", name="sidebar_color",),
        migrations.RemoveField(model_name="organizationtheme", name="success_color",),
        migrations.RemoveField(model_name="organizationtheme", name="template_id",),
        migrations.RemoveField(model_name="organizationtheme", name="tertiary_color",),
        migrations.RemoveField(model_name="organizationtheme", name="topbar_color",),
        migrations.AddField(
            model_name="lookuppermission",
            name="reports_user1space1journey1space1tracker_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="reports_user1space1journey1space1tracker_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="reports_user1space1journey1space1tracker_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="reports_user1space1journey1space1tracker_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuptheme",
            name="customer_journey_button_first_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="lookuptheme",
            name="customer_journey_button_second_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="lookuptheme",
            name="general_button_first_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="lookuptheme",
            name="general_button_second_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="lookuptheme",
            name="loader_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="lookuptheme",
            name="nav_bar_bg_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="lookuptheme",
            name="nav_bar_drop_down_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="lookuptheme",
            name="nav_bar_selected_bg_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="lookuptheme",
            name="nav_bar_selected_text_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="lookuptheme",
            name="nav_bar_text_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organizationtheme",
            name="customer_journey_button_first_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organizationtheme",
            name="customer_journey_button_second_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organizationtheme",
            name="general_button_first_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organizationtheme",
            name="general_button_second_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organizationtheme",
            name="loader_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organizationtheme",
            name="nav_bar_bg_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organizationtheme",
            name="nav_bar_drop_down_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organizationtheme",
            name="nav_bar_selected_bg_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organizationtheme",
            name="nav_bar_selected_text_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organizationtheme",
            name="nav_bar_text_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="permission",
            name="reports_user1space1journey1space1tracker_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="reports_user1space1journey1space1tracker_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="reports_user1space1journey1space1tracker_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="reports_user1space1journey1space1tracker_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lookuptheme",
            name="background_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="organizationtheme",
            name="background_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
