# Generated by Django 5.0.6 on 2025-01-15 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0112_remove_lookuptheme_failure_color_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="control1space1panel_outapi1space1management_create",
            new_name="control1space1panel_out_api1space1management_create",
        ),
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="control1space1panel_outapi1space1management_delete",
            new_name="control1space1panel_out_api1space1management_delete",
        ),
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="control1space1panel_outapi1space1management_edit",
            new_name="control1space1panel_out_api1space1management_edit",
        ),
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="control1space1panel_outapi1space1management_view",
            new_name="control1space1panel_out_api1space1management_view",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="control1space1panel_outapi1space1management_create",
            new_name="control1space1panel_out_api1space1management_create",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="control1space1panel_outapi1space1management_delete",
            new_name="control1space1panel_out_api1space1management_delete",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="control1space1panel_outapi1space1management_edit",
            new_name="control1space1panel_out_api1space1management_edit",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="control1space1panel_outapi1space1management_view",
            new_name="control1space1panel_out_api1space1management_view",
        ),
        migrations.AddField(
            model_name="lookuptheme",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.lookuptemplate",
            ),
        ),
        migrations.AddField(
            model_name="organizationtheme",
            name="template_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.lookuptemplate",
            ),
        ),
    ]
