# Generated by Django 5.0.6 on 2025-01-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0113_rename_control1space1panel_outapi1space1management_create_lookuppermission_control1space1panel_out_a",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="control1space1panel_out_api1space1management_create",
            new_name="control1space1panel_outapi1space1management_create",
        ),
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="control1space1panel_out_api1space1management_delete",
            new_name="control1space1panel_outapi1space1management_delete",
        ),
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="control1space1panel_out_api1space1management_edit",
            new_name="control1space1panel_outapi1space1management_edit",
        ),
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="control1space1panel_out_api1space1management_view",
            new_name="control1space1panel_outapi1space1management_view",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="control1space1panel_out_api1space1management_create",
            new_name="control1space1panel_outapi1space1management_create",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="control1space1panel_out_api1space1management_delete",
            new_name="control1space1panel_outapi1space1management_delete",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="control1space1panel_out_api1space1management_edit",
            new_name="control1space1panel_outapi1space1management_edit",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="control1space1panel_out_api1space1management_view",
            new_name="control1space1panel_outapi1space1management_view",
        ),
    ]
