# Generated by Django 5.0.6 on 2025-01-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0115_rename_control1space1panel_outapi1space1management_create_lookuppermission_control1space1panel_out1h",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lookuptheme",
            name="customer_journey_text_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="lookuptheme",
            name="general_button_text_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organizationtheme",
            name="customer_journey_text_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organizationtheme",
            name="general_button_text_color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
