# Generated by Django 5.0.6 on 2025-01-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0116_lookuptheme_customer_journey_text_color_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lookuptheme", old_name="template", new_name="template_id",
        ),
    ]
