# Generated by Django 5.0.6 on 2025-01-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0117_rename_template_lookuptheme_template_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookuppermission",
            name="reports_finance1space1team1space1performance_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="reports_finance1space1team1space1performance_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="reports_finance1space1team1space1performance_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="reports_finance1space1team1space1performance_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="reports_finance1space1team1space1performance_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="reports_finance1space1team1space1performance_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="reports_finance1space1team1space1performance_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="reports_finance1space1team1space1performance_view",
            field=models.BooleanField(default=False),
        ),
    ]
