# Generated by Django 5.0.6 on 2025-02-07 04:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0118_lookuppermission_reports_finance1space1team1space1performance_create_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="APICriticalTransactionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("url", models.CharField(blank=True, max_length=400, null=True)),
                ("type", models.CharField(blank=True, max_length=400, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "api_critical_transaction_log",},
        ),
    ]
