# Generated by Django 5.0.6 on 2025-02-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0119_apicriticaltransactionlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apicriticaltransactionlog", options={"ordering": ["-created_at"]},
        ),
    ]
