# Generated by Django 5.0.6 on 2025-02-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0120_alter_apicriticaltransactionlog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicriticaltransactionlog",
            name="created_time",
            field=models.BigIntegerField(editable=False, null=True),
        ),
    ]
