# Generated by Django 5.0.6 on 2025-02-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0121_apicriticaltransactionlog_created_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookupairports",
            name="timezone",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
