# Generated by Django 5.0.6 on 2025-02-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0123_lookuppermission_flight_queues_others_create_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="flight_queues_others_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="flight_queues_others_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="flight_queues_others_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="flight_queues_others_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="reports_operation1space1performance_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="reports_operation1space1performance_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="reports_operation1space1performance_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="reports_operation1space1performance_view",
            field=models.BooleanField(default=False),
        ),
    ]
