# Generated by Django 5.0.6 on 2025-03-03 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0124_permission_flight_queues_others_create_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicriticaltransactionlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
