# Generated by Django 5.0.6 on 2025-03-07 04:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0126_alter_apicriticaltransactionlog_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhiteLabelPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("slug_url", models.CharField(max_length=500)),
                ("heading", models.CharField(max_length=1000)),
                ("html_content", models.TextField()),
                ("css_style", models.TextField()),
                ("js_code", models.TextField()),
                ("page_content", models.TextField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.organization",
                    ),
                ),
            ],
            options={"db_table": "white_label_page", "ordering": ["-created_at"],},
        ),
    ]
