# Generated by Django 5.0.6 on 2025-03-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0127_whitelabelpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whitelabelpage",
            name="css_style",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="whitelabelpage",
            name="js_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
