# Generated by Django 5.0.6 on 2025-03-10 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0128_alter_whitelabelpage_css_style_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookuppermission",
            name="control1space1panel_whitelabel1space1management_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="control1space1panel_whitelabel1space1management_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="control1space1panel_whitelabel1space1management_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="control1space1panel_whitelabel1space1management_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_white_label",
            field=models.CharField(
                choices=[
                    ("not_requested", "not_requested"),
                    ("pending", "pending"),
                    ("active", "active"),
                ],
                default="not_requested",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="control1space1panel_whitelabel1space1management_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="control1space1panel_whitelabel1space1management_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="control1space1panel_whitelabel1space1management_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="control1space1panel_whitelabel1space1management_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="whitelabel",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="whitelabelpage",
            name="whitelabel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.whitelabel",
            ),
        ),
    ]
