# Generated by Django 5.0.6 on 2025-03-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0129_lookuppermission_control1space1panel_whitelabel1space1management_create_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="whitelabelpage", name="whitelabel",),
    ]
