# Generated by Django 5.0.6 on 2025-03-11 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0130_remove_whitelabelpage_whitelabel"),
    ]

    operations = [
        migrations.AddField(
            model_name="whitelabelpage",
            name="whitelabel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.whitelabel",
            ),
        ),
    ]
