# Generated by Django 5.0.6 on 2025-03-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0131_whitelabelpage_whitelabel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="cab_create",
            new_name="transfers_create",
        ),
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="cab_delete",
            new_name="transfers_delete",
        ),
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="cab_edit",
            new_name="transfers_edit",
        ),
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="cab_view",
            new_name="transfers_view",
        ),
        migrations.RenameField(
            model_name="permission", old_name="cab_create", new_name="transfers_create",
        ),
        migrations.RenameField(
            model_name="permission", old_name="cab_delete", new_name="transfers_delete",
        ),
        migrations.RenameField(
            model_name="permission", old_name="cab_edit", new_name="transfers_edit",
        ),
        migrations.RenameField(
            model_name="permission", old_name="cab_view", new_name="transfers_view",
        ),
    ]
