# Generated by Django 5.0.6 on 2025-03-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0132_rename_cab_create_lookuppermission_transfers_create_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookuppermission",
            name="cab_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="cab_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="cab_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="cab_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="cab_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="cab_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="cab_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="cab_view",
            field=models.BooleanField(default=False),
        ),
    ]
