# Generated by Django 5.0.6 on 2025-03-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0134_lookuppermission_transfers_booking1space1history_create_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lookuppermission",
            name="transfers_search_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="transfers_search_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="transfers_search_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="transfers_search_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="transfers_search_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="transfers_search_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="transfers_search_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="transfers_search_view",
            field=models.BooleanField(default=False),
        ),
    ]
