# Generated by Django 5.0.6 on 2025-03-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0135_lookuppermission_transfers_search_create_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookuppermission",
            name="control1space1panel_rail1space1management_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="control1space1panel_rail1space1management_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="control1space1panel_rail1space1management_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="control1space1panel_rail1space1management_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="control1space1panel_rail1space1management_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="control1space1panel_rail1space1management_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="control1space1panel_rail1space1management_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="control1space1panel_rail1space1management_view",
            field=models.BooleanField(default=False),
        ),
    ]
