# Generated by Django 5.0.6 on 2025-03-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0136_lookuppermission_control1space1panel_rail1space1management_create_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="eurail_create",
            new_name="rail_create",
        ),
        migrations.RenameField(
            model_name="lookuppermission",
            old_name="eurail_delete",
            new_name="rail_delete",
        ),
        migrations.RenameField(
            model_name="lookuppermission", old_name="eurail_edit", new_name="rail_edit",
        ),
        migrations.RenameField(
            model_name="lookuppermission", old_name="eurail_view", new_name="rail_view",
        ),
        migrations.RenameField(
            model_name="permission", old_name="eurail_create", new_name="rail_create",
        ),
        migrations.RenameField(
            model_name="permission", old_name="eurail_delete", new_name="rail_delete",
        ),
        migrations.RenameField(
            model_name="permission", old_name="eurail_edit", new_name="rail_edit",
        ),
        migrations.RenameField(
            model_name="permission", old_name="eurail_view", new_name="rail_view",
        ),
    ]
