# Generated by Django 5.0.6 on 2025-03-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0137_rename_eurail_create_lookuppermission_rail_create_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_fare1space1management_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_fare1space1management_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_fare1space1management_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="admin1space1panel_fare1space1management_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_fare1space1management_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_fare1space1management_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_fare1space1management_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="admin1space1panel_fare1space1management_view",
            field=models.BooleanField(default=False),
        ),
    ]
