# Generated by Django 5.0.6 on 2025-03-20 09:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0024_alter_supplierintegration_token"),
        (
            "users",
            "0138_lookuppermission_admin1space1panel_fare1space1management_create_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FareManagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("supplier_fare_name", models.CharField(max_length=500)),
                ("brand_name", models.CharField(max_length=500)),
                ("priority", models.IntegerField()),
                (
                    "supplier_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suppliers.supplierintegration",
                    ),
                ),
            ],
            options={"db_table": "fare_management", "ordering": ["-created_at"],},
        ),
        migrations.AddConstraint(
            model_name="faremanagement",
            constraint=models.UniqueConstraint(
                fields=("supplier_id", "supplier_fare_name"),
                name="unique_supplier_id_fare_name",
            ),
        ),
    ]
