# Generated by Django 5.0.6 on 2025-03-20 10:06

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0024_alter_supplierintegration_token"),
        ("users", "0139_faremanagement_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="faremanagement", name="unique_supplier_id_fare_name",
        ),
        migrations.AddConstraint(
            model_name="faremanagement",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("supplier_fare_name"),
                models.F("supplier_id"),
                name="unique_supplier_id_fare_name_ci",
            ),
        ),
    ]
