# Generated by Django 5.0.6 on 2025-03-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0140_remove_faremanagement_unique_supplier_id_fare_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faremanagement",
            name="brand_name",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
