# Generated by Django 5.0.6 on 2025-03-21 06:11

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0024_alter_supplierintegration_token"),
        ("users", "0141_alter_faremanagement_brand_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="faremanagement", name="unique_supplier_id_fare_name_ci",
        ),
        migrations.AlterField(
            model_name="faremanagement",
            name="brand_name",
            field=models.CharField(max_length=500),
        ),
        migrations.AddConstraint(
            model_name="faremanagement",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("supplier_fare_name"),
                models.F("supplier_id"),
                models.F("brand_name"),
                name="unique_supplier_id_fare_name_brand_name",
            ),
        ),
    ]
