# Generated by Django 5.0.6 on 2025-03-28 07:02

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0145_lookuppermission_bus_booking1space1history_create_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="whitelabelpage",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("slug_url"),
                models.F("whitelabel"),
                name="unique_slug_url_whitelabel_host",
            ),
        ),
    ]
