# Generated by Django 5.0.6 on 2025-04-02 04:44

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0025_alter_lookupsupplierintegration_integration_type_and_more"),
        ("users", "0146_whitelabelpage_unique_slug_url_whitelabel_host"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="faremanagement",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("brand_name"),
                models.F("priority"),
                name="unique_UniqueConstraint_priority",
            ),
        ),
    ]
