# Generated by Django 5.0.6 on 2025-04-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0148_lookuppermission_hotel_search_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='hotel_search_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='hotel_search_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='hotel_search_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='hotel_search_view',
            field=models.BooleanField(default=False),
        ),
    ]
