# Generated by Django 5.0.6 on 2025-04-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0147_faremanagement_unique_uniqueconstraint_priority"),
        ("users", "0149_permission_hotel_search_create_and_more"),
    ]

    operations = []
