# Generated by Django 5.0.6 on 2025-04-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0150_merge_20250402_1046"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookuppermission",
            name="transfers_queues_cancelled1space1bookings_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="transfers_queues_cancelled1space1bookings_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="transfers_queues_cancelled1space1bookings_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="transfers_queues_cancelled1space1bookings_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="transfers_queues_cancelled1space1bookings_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="transfers_queues_cancelled1space1bookings_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="transfers_queues_cancelled1space1bookings_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="transfers_queues_cancelled1space1bookings_view",
            field=models.BooleanField(default=False),
        ),
    ]
