# Generated by Django 5.0.6 on 2025-04-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0151_lookuppermission_transfers_queues_cancelled1space1bookings_create_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="faremanagement",
            name="unique_UniqueConstraint_priority",
        ),
    ]
