# Generated by Django 5.0.6 on 2025-04-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0153_lookuppermission_insurance_booking1space1history_create_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lookuppermission",
            name="hotel_queues_cancelled1space1bookings_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="hotel_queues_cancelled1space1bookings_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="hotel_queues_cancelled1space1bookings_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lookuppermission",
            name="hotel_queues_cancelled1space1bookings_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="hotel_queues_cancelled1space1bookings_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="hotel_queues_cancelled1space1bookings_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="hotel_queues_cancelled1space1bookings_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="hotel_queues_cancelled1space1bookings_view",
            field=models.BooleanField(default=False),
        ),
    ]
