# Generated by Django 5.0.6 on 2024-10-13 21:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0001_initial'),
        ('suppliers', '0015_alter_organizationsupplierintegeration_table'),
        ('users', '0049_lookupairline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Flight Booking'},
        ),
        migrations.AlterModelOptions(
            name='easylinkdetails',
            options={'verbose_name': 'easy_link_details'},
        ),
        migrations.AlterModelOptions(
            name='flightbookingjourneydetails',
            options={'verbose_name': 'Flight Booking Journey Details'},
        ),
        migrations.AlterModelOptions(
            name='flightbookingpaymentdetails',
            options={'verbose_name': 'Flight Booking Payment Details'},
        ),
        migrations.AlterModelOptions(
            name='flightbookingsearchdetails',
            options={'verbose_name': 'Flight Booking Search Detail'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='details',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='fare_details',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='itinerary_details',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='new_booking_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pax_details',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pnr',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='easylinkdetails',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='easylinkdetails',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='flightbookingjourneydetails',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flightbookingjourneydetails',
            name='flight_booking_search_details',
        ),
        migrations.RemoveField(
            model_name='flightbookingjourneydetails',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='flightbookingpaymentdetails',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flightbookingpaymentdetails',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='flightbookingsearchdetails',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flightbookingsearchdetails',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='flightbookingjourneydetails',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_booking.booking'),
        ),
        migrations.AddField(
            model_name='flightbookingjourneydetails',
            name='journey_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cancelled_at',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contact',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='booking',
            name='display_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gst_details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='modified_at',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='session_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='easylinkdetails',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flightbookingjourneydetails',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flightbookingjourneydetails',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flightbookingjourneydetails',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flightbookingjourneydetails',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flightbookingpaymentdetails',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flightbookingpaymentdetails',
            name='payment_type',
            field=models.CharField(choices=[('wallet', 'wallet'), ('stripe', 'stripe'), ('razor_pay', 'razor_pay')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flightbookingpaymentdetails',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flightbookingsearchdetails',
            name='cabin_class',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='flightbookingsearchdetails',
            name='fare_type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='flightbookingsearchdetails',
            name='flight_type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='flightbookingsearchdetails',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flightbookingsearchdetails',
            name='journey_type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='flightbookingsearchdetails',
            name='passenger_details',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='FlightBookingItineraryDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('itinerary_key', models.CharField(max_length=100)),
                ('segment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=100)),
                ('pnr', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_booking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_booking.booking')),
                ('old_itinerary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_itineraries', to='flight_booking.flightbookingitinerarydetails')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplierintegration')),
            ],
            options={
                'verbose_name': 'Flight Booking Itinerary Details',
                'db_table': 'flight_booking_itinerary_details',
            },
        ),
        migrations.CreateModel(
            name='FlightBookingFareDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('published_fare', models.DecimalField(decimal_places=4, max_digits=10)),
                ('offered_fare', models.DecimalField(decimal_places=4, max_digits=10)),
                ('organization_discount', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('dist_agent_markup', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('dist_agent_cashback', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_booking.flightbookingitinerarydetails')),
            ],
            options={
                'verbose_name': 'Flight Booking Fare Details',
                'db_table': 'flight_booking_fare_details',
            },
        ),
        migrations.AddField(
            model_name='flightbookingjourneydetails',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_booking.flightbookingitinerarydetails'),
        ),
        migrations.CreateModel(
            name='FlightBookingPaxDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pax_type', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.CharField(blank=True, max_length=100, null=True)),
                ('passport', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_expiry', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_issue_date', models.CharField(blank=True, max_length=100, null=True)),
                ('address_1', models.CharField(blank=True, max_length=300, null=True)),
                ('address_2', models.CharField(blank=True, max_length=300, null=True)),
                ('is_lead_pax', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_booking.booking')),
                ('passport_issue_country_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.lookupcountry')),
            ],
            options={
                'verbose_name': 'Flight Booking Pax Details',
                'db_table': 'flight_booking_pax_details',
            },
        ),
        migrations.CreateModel(
            name='FlightBookingSSRDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_baggage', models.BooleanField(default=False)),
                ('is_meals', models.BooleanField(default=False)),
                ('is_seats', models.BooleanField(default=False)),
                ('baggage_ssr', models.CharField(blank=True, max_length=500, null=True)),
                ('meals_ssr', models.CharField(blank=True, max_length=500, null=True)),
                ('seats_ssr', models.CharField(blank=True, max_length=500, null=True)),
                ('ssr_id', models.CharField(blank=True, max_length=50, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_booking.flightbookingitinerarydetails')),
                ('pax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_booking.flightbookingpaxdetails')),
            ],
            options={
                'verbose_name': 'Flight Booking SSR Details',
                'db_table': 'flight_booking_ssr_details',
            },
        ),
    ]
