# Generated by Django 5.0.6 on 2024-10-13 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0002_alter_booking_options_alter_easylinkdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_booking.flightbookingpaymentdetails'),
        ),
    ]
