# Generated by Django 5.0.6 on 2024-10-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0003_alter_booking_payment_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightbookingitinerarydetails',
            old_name='pnr',
            new_name='airlin_pnr',
        ),
        migrations.AddField(
            model_name='flightbookingitinerarydetails',
            name='gds_pnr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
