# Generated by Django 5.0.6 on 2024-10-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0004_rename_pnr_flightbookingitinerarydetails_airlin_pnr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightbookingitinerarydetails',
            old_name='airlin_pnr',
            new_name='airline_pnr',
        ),
    ]
