# Generated by Django 5.0.6 on 2024-10-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0005_rename_airlin_pnr_flightbookingitinerarydetails_airline_pnr'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='easylinkdetails',
            name='created_at',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='easylinkdetails',
            name='modified_at',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingfaredetails',
            name='created_at',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingfaredetails',
            name='modified_at',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingitinerarydetails',
            name='created_at',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingitinerarydetails',
            name='modified_at',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingjourneydetails',
            name='created_at',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingjourneydetails',
            name='modified_at',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingpaxdetails',
            name='created_at',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingpaxdetails',
            name='modified_at',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingpaymentdetails',
            name='created_at',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingpaymentdetails',
            name='modified_at',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingsearchdetails',
            name='created_at',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingsearchdetails',
            name='modified_at',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingssrdetails',
            name='created_at',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingssrdetails',
            name='modified_at',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='easylinkdetails',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='flightbookingfaredetails',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='flightbookingitinerarydetails',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='flightbookingjourneydetails',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='flightbookingpaxdetails',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='flightbookingpaymentdetails',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='flightbookingsearchdetails',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='flightbookingssrdetails',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
