# Generated by Django 5.0.6 on 2024-10-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0006_booking_created_at_easylinkdetails_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbookingitinerarydetails',
            name='invoice_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flightbookingitinerarydetails',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingitinerarydetails',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
