# Generated by Django 5.0.6 on 2024-10-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0007_flightbookingitinerarydetails_invoice_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbookingssrdetails',
            name='supplier_pax_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingssrdetails',
            name='supplier_ticket_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingssrdetails',
            name='supplier_ticket_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
