# Generated by Django 5.0.6 on 2024-10-22 08:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0008_flightbookingssrdetails_supplier_pax_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightBookingSegmentDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                (
                    "airline_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "airline_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "airline_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "flight_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "equipment_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("duration", models.PositiveIntegerField()),
                ("origin", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "origin_terminal",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("departure_datetime", models.PositiveBigIntegerField()),
                ("destination", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "destination_terminal",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("arrival_datetime", models.PositiveBigIntegerField()),
                ("index", models.IntegerField()),
                (
                    "itinerary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flight_booking.flightbookingitinerarydetails",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flight Booking Segment Details",
                "db_table": "flight_booking_segment_details",
            },
        ),
    ]
