# Generated by Django 5.0.6 on 2024-10-22 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0009_flightbookingsegmentdetails"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flightbookingsegmentdetails",
            name="itinerary",
        ),
        migrations.AddField(
            model_name="flightbookingsegmentdetails",
            name="journey",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="flight_booking.flightbookingjourneydetails",
            ),
        ),
    ]
