# Generated by Django 5.0.6 on 2024-10-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "flight_booking",
            "0010_remove_flightbookingsegmentdetails_itinerary_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["timestamp"], "verbose_name": "Flight Booking"},
        ),
        migrations.AlterModelOptions(
            name="easylinkdetails",
            options={"ordering": ["timestamp"], "verbose_name": "easy_link_details"},
        ),
        migrations.AlterModelOptions(
            name="flightbookingfaredetails",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Flight Booking Fare Details",
            },
        ),
        migrations.AlterModelOptions(
            name="flightbookingitinerarydetails",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Flight Booking Itinerary Details",
            },
        ),
        migrations.AlterModelOptions(
            name="flightbookingjourneydetails",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Flight Booking Journey Details",
            },
        ),
        migrations.AlterModelOptions(
            name="flightbookingpaxdetails",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Flight Booking Pax Details",
            },
        ),
        migrations.AlterModelOptions(
            name="flightbookingpaymentdetails",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Flight Booking Payment Details",
            },
        ),
        migrations.AlterModelOptions(
            name="flightbookingsearchdetails",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Flight Booking Search Detail",
            },
        ),
        migrations.AlterModelOptions(
            name="flightbookingsegmentdetails",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Flight Booking Segment Details",
            },
        ),
        migrations.AlterModelOptions(
            name="flightbookingssrdetails",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Flight Booking SSR Details",
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="timestamp",
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="easylinkdetails",
            name="timestamp",
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="flightbookingfaredetails",
            name="timestamp",
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="flightbookingitinerarydetails",
            name="timestamp",
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="flightbookingjourneydetails",
            name="timestamp",
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="flightbookingpaxdetails",
            name="timestamp",
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="flightbookingpaymentdetails",
            name="timestamp",
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="flightbookingsearchdetails",
            name="timestamp",
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="flightbookingsegmentdetails",
            name="timestamp",
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="flightbookingssrdetails",
            name="timestamp",
            field=models.BigIntegerField(editable=False, null=True),
        ),
    ]
