# Generated by Django 5.0.6 on 2024-10-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "flight_booking",
            "0011_alter_booking_options_alter_easylinkdetails_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="flightbookingfaredetails",
            name="fare_breakdown",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
