# Generated by Django 5.0.6 on 2024-10-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0012_flightbookingfaredetails_fare_breakdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightbookingitinerarydetails",
            name="itinerary_index",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="flightbookingitinerarydetails",
            name="misc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
