# Generated by Django 5.0.6 on 2024-10-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0013_flightbookingitinerarydetails_itinerary_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbookingpaxdetails',
            name='passport_issue_country_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
