# Generated by Django 5.0.6 on 2024-11-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0014_alter_flightbookingpaxdetails_passport_issue_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='easylinkdetails',
            name='billnarration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='easylinkdetails',
            name='billnote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='easylinkdetails',
            name='receiptamt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightbookingitinerarydetails',
            name='error',
            field=models.TextField(null=True),
        ),
    ]
