# Generated by Django 5.0.6 on 2024-11-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0015_easylinkdetails_billnarration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbookingsegmentdetails',
            name='destination_terminal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flightbookingsegmentdetails',
            name='origin_terminal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
