# Generated by Django 5.0.6 on 2024-11-14 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "flight_booking",
            "0016_alter_flightbookingsegmentdetails_destination_terminal_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-created_at"], "verbose_name": "Flight Booking"},
        ),
        migrations.AlterModelOptions(
            name="flightbookingitinerarydetails",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Flight Booking Itinerary Details",
            },
        ),
        migrations.AlterModelOptions(
            name="flightbookingjourneydetails",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Flight Booking Journey Details",
            },
        ),
    ]
