# Generated by Django 5.0.6 on 2024-11-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0017_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['timestamp'], 'verbose_name': 'Flight Booking'},
        ),
        migrations.AlterModelOptions(
            name='flightbookingitinerarydetails',
            options={'ordering': ['timestamp'], 'verbose_name': 'Flight Booking Itinerary Details'},
        ),
        migrations.AlterModelOptions(
            name='flightbookingjourneydetails',
            options={'ordering': ['timestamp'], 'verbose_name': 'Flight Booking Journey Details'},
        ),
    ]
