# Generated by Django 5.0.6 on 2024-12-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0018_alter_booking_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="EasyLinkDetails",),
    ]
