# Generated by Django 5.0.6 on 2024-12-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0020_easylinkdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="source",
            field=models.CharField(default="Online", max_length=25),
        ),
    ]
