# Generated by Django 5.0.6 on 2024-12-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0021_booking_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbookingpaymentdetails',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
