# Generated by Django 5.0.6 on 2024-12-18 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight_booking", "0022_flightbookingpaymentdetails_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightbookingitinerarydetails",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flight_booking_itenary_Details",
                to="flight_booking.booking",
            ),
        ),
    ]
