# Generated by Django 5.0.6 on 2024-12-18 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight_booking", "0024_alter_flightbookingitinerarydetails_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightbookingitinerarydetails",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="flight_booking.booking"
            ),
        ),
    ]
