# Generated by Django 5.0.6 on 2024-12-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0026_flightitineraryaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightbookingitinerarydetails",
            name="hold_till",
            field=models.CharField(blank=True, default="N/A", max_length=30, null=True),
        ),
    ]
