# Generated by Django 5.0.6 on 2024-12-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0027_flightbookingitinerarydetails_hold_till"),
    ]

    operations = [
        migrations.DeleteModel(name="FlightItineraryAccess",),
    ]
