# Generated by Django 5.0.6 on 2024-12-19 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0028_delete_flightitineraryaccess"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightBookingAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("expiry_time", models.BigIntegerField(editable=False, null=True)),
                (
                    "bookingid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flight_booking.booking",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "flight_booking_access",},
        ),
    ]
