# Generated by Django 5.0.6 on 2024-12-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0029_flightbookingaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightbookingitinerarydetails",
            name="default_baggage",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
