# Generated by Django 5.0.6 on 2024-12-30 10:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0030_flightbookingitinerarydetails_default_baggage"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightBookingUnifiedDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("itinerary_data_unified", models.JSONField(default=dict)),
                ("created_at", models.BigIntegerField(blank=True, null=True)),
                (
                    "itinerary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flight_booking.flightbookingitinerarydetails",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flight Booking Unified Details",
                "db_table": "flight_booking_unified_details",
                "ordering": ["created_at"],
            },
        ),
    ]
