# Generated by Django 5.0.6 on 2024-12-30 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0031_flightbookingunifieddetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightbookingunifieddetails",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="flight_booking.booking",
            ),
        ),
    ]
