# Generated by Django 5.0.6 on 2025-01-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0032_flightbookingunifieddetails_booking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flightbookingpaymentdetails",
            old_name="amount",
            new_name="new_published_fare",
        ),
    ]
