# Generated by Django 5.0.6 on 2025-01-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "flight_booking",
            "0033_rename_amount_flightbookingpaymentdetails_new_published_fare",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="flightbookingpaymentdetails",
            name="new_offered_fare",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="flightbookingpaymentdetails",
            name="supplier_offered_fare",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="flightbookingpaymentdetails",
            name="supplier_published_fare",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="flightbookingpaymentdetails",
            name="new_published_fare",
            field=models.FloatField(default=0),
        ),
    ]
