# Generated by Django 5.0.6 on 2025-01-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "flight_booking",
            "0034_flightbookingpaymentdetails_new_offered_fare_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="flightbookingunifieddetails",
            name="fare_details",
            field=models.JSONField(default=dict),
        ),
    ]
