# Generated by Django 5.0.6 on 2025-01-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0035_flightbookingunifieddetails_fare_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightbookingfaredetails",
            name="fare_breakdown",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
