# Generated by Django 5.0.6 on 2025-01-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0036_alter_flightbookingfaredetails_fare_breakdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightbookingpaymentdetails",
            name="ssr_price",
            field=models.FloatField(default=0),
        ),
    ]
