# Generated by Django 5.0.6 on 2025-02-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0037_flightbookingpaymentdetails_ssr_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightbookingunifieddetails",
            name="fare_quote",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="flightbookingunifieddetails",
            name="ssr_raw",
            field=models.JSONField(default=dict),
        ),
    ]
