# Generated by Django 5.0.6 on 2025-02-04 05:26
# Generated by Django 5.0.6 on 2025-02-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0038_flightbookingunifieddetails_fare_quote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightbookingunifieddetails",
            name="misc",
            field=models.JSONField(default=dict),
        ),
    ]
