# Generated by Django 5.0.6 on 2025-02-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0039_flightbookingunifieddetails_misc"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightbookingssrdetails",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
