# Generated by Django 5.0.6 on 2025-02-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0040_flightbookingssrdetails_is_cancelled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightbookingsegmentdetails",
            name="airline_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="flightbookingsegmentdetails",
            name="airline_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="flightbookingsegmentdetails",
            name="destination",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="flightbookingsegmentdetails",
            name="equipment_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="flightbookingsegmentdetails",
            name="flight_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="flightbookingsegmentdetails",
            name="origin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
