# Generated by Django 5.0.6 on 2025-02-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "flight_booking",
            "0041_alter_flightbookingsegmentdetails_airline_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightbookingssrdetails",
            name="is_cancelled",
            field=models.CharField(
                blank=True, default="Not Requested", max_length=500, null=True
            ),
        ),
    ]
