# Generated by Django 5.0.6 on 2025-02-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0042_alter_flightbookingssrdetails_is_cancelled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flightbookingssrdetails",
            old_name="is_cancelled",
            new_name="cancellation_status",
        ),
    ]
