# Generated by Django 5.0.6 on 2025-02-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "flight_booking",
            "0043_rename_is_cancelled_flightbookingssrdetails_cancellation_status",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightbookingssrdetails",
            name="cancellation_status",
            field=models.CharField(
                blank=True, default="Confirmed", max_length=500, null=True
            ),
        ),
    ]
