# Generated by Django 5.0.6 on 2025-02-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0044_alter_flightbookingssrdetails_cancellation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightbookingssrdetails",
            name="cancellation_status",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
