# Generated by Django 5.0.6 on 2025-02-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0045_alter_flightbookingssrdetails_cancellation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightbookingssrdetails",
            name="cancellation_fee",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
