# Generated by Django 5.0.6 on 2025-03-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0046_flightbookingssrdetails_cancellation_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightbookingitinerarydetails",
            name="soft_fail",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
