# Generated by Django 5.0.6 on 2025-03-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0047_flightbookingitinerarydetails_soft_fail"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_direct_booking",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
