# Generated by Django 5.0.6 on 2025-03-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0048_booking_is_direct_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightbookingssrdetails",
            name="cancellation_info",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
