# Generated by Django 5.0.6 on 2025-03-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0049_flightbookingssrdetails_cancellation_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightbookingssrdetails",
            name="cancellation_info",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
