# Generated by Django 5.0.6 on 2025-04-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0050_alter_flightbookingssrdetails_cancellation_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="frequent_flier_number",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
