# Generated by Django 5.0.6 on 2025-04-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0051_booking_frequent_flier_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="frequent_flier_number",
        ),
        migrations.AddField(
            model_name="flightbookingitinerarydetails",
            name="frequent_flyer_number",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
