# Generated by Django 5.0.6 on 2025-04-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_booking", "0052_remove_booking_frequent_flier_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flightbookingitinerarydetails",
            name="frequent_flyer_number",
        ),
        migrations.AddField(
            model_name="flightbookingpaxdetails",
            name="frequent_flyer_number",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
