# Generated by Django 5.0.6 on 2024-06-20 06:07

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LookupSupplierIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("name", models.CharField(max_length=600)),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("Flights", "Flights"),
                            ("Hotels", "Hotels"),
                            ("Rail", "Rail"),
                            ("Payment", "Payment"),
                        ],
                        max_length=500,
                    ),
                ),
                (
                    "keys",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=600),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("icon_url", models.CharField(max_length=600)),
            ],
            options={"db_table": "lookup_supplier_integration",},
        ),
        migrations.CreateModel(
            name="SupplierIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("name", models.CharField(max_length=600)),
                ("data", models.JSONField()),
                ("icon_url", models.CharField(max_length=1000)),
                ("integration_type", models.CharField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"db_table": "supplier_integration",},
        ),
    ]
