# Generated by Django 5.0.6 on 2024-06-20 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("suppliers", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierintegration",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.country"
            ),
        ),
        migrations.AddField(
            model_name="supplierintegration",
            name="lookup_supplier",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="suppliers.lookupsupplierintegration",
            ),
        ),
    ]
