# Generated by Django 5.0.6 on 2024-07-03 09:11

from django.db import migrations
from integrations.suppliers.models import SupplierIntegration, LookupSupplierIntegration

def create_lookup_supplier(apps, schema_editor):
    supplier_model = apps.get_model('suppliers' , 'LookupSupplierIntegration')
    supplier_model.objects.create(
        name = LookupSupplierIntegration.Keywords.FLIGHT_GETFARE,
        integration_type = 'Flight',
        keys = ['token'],
        icon_url = 'https://cdn.dribbble.com/users/159009/screenshots/1601852/airplane-flight-animation.gif'

    )
class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0002_initial"),
    ]

    operations = [
        # migrations.RunPython(create_lookup_supplier)
    ]
