# Generated by Django 5.0.6 on 2024-07-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0003_create_lookup_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierintegration",
            name="name",
            field=models.CharField(
                choices=[("flight_getfare", "FLIGHT_GETFARE")], max_length=600
            ),
        ),
    ]
