# Generated by Django 5.0.6 on 2024-09-05 12:20
from django.db import migrations

def add_default_values(apps, schema_editor):
    supplier = apps.get_model('suppliers', 'LookupSupplierIntegration')
    supplier.objects.create(name='get_fares', integration_type='Flights',keys=["base_url", "username","api_provider_code", "password"], icon_url="https://book-staging-bucket.s3.amazonaws.com/media/btob/gallery/getfares2.gif")
    supplier.objects.create(name='trip_pro', integration_type='Flights',keys=["base_url", "search_access_token","api_provider_code"], icon_url="https://book-staging-bucket.s3.amazonaws.com/media/btob/gallery/WhatsApp_Image_2024-09-05_at_6.22.24_PM.jpeg")
    # supplier.objects.create(name='trip_jack', integeration_type='Flights',keys=["base_url", "api_key","api_provider_code"], icon_url="https://book-staging-bucket.s3.amazonaws.com/media/btob/gallery/WhatsApp_Image_2024-09-05_at_6.22.24_PM.jpeg")



class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_alter_supplierintegration_name'),
    ]

    operations = [
        migrations.RunPython(add_default_values)
    ]
