# Generated by Django 5.0.6 on 2024-09-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_auto_20240905_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierintegration',
            name='name',
            field=models.CharField(choices=[('get_fares', 'get_fares')], max_length=600),
        ),
    ]
