# Generated by Django 5.0.6 on 2024-09-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0007_alter_supplierintegration_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierintegration",
            name="name",
            field=models.CharField(
                choices=[("get_fares", "get_fares"), ("trip_pro", "trip_pro")],
                max_length=600,
            ),
        ),
    ]
