# Generated by Django 5.0.6 on 2024-09-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0008_alter_supplierintegration_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierintegration",
            name="integration_type",
            field=models.CharField(
                choices=[
                    ("Flights", "Flights"),
                    ("Hotels", "Hotels"),
                    ("Rail", "Rail"),
                    ("Payment", "Payment"),
                ],
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="supplierintegration",
            name="name",
            field=models.CharField(max_length=600),
        ),
    ]
