# Generated by Django 5.0.6 on 2024-10-01 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_alter_supplierintegration_integration_type_and_more'),
        ('users', '0046_auto_20240927_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSupplierIntegeration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
                ('supplier_integeration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplierintegration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
