# Generated by Django 5.0.6 on 2024-10-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_organizationsupplierintegeration'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsupplierintegeration',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
