# Generated by Django 5.0.6 on 2024-10-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0011_organizationsupplierintegeration_is_enabled"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="organizationsupplierintegeration",
            table="supplier_organization_integeration",
        ),
    ]
