# Generated by Django 5.0.6 on 2024-10-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0012_alter_organizationsupplierintegeration_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierintegration',
            name='expired_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierintegration',
            name='token',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
