# Generated by Django 5.0.6 on 2024-10-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0013_supplierintegration_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierintegration',
            name='expired_at',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
