# Generated by Django 5.0.6 on 2024-10-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0014_alter_supplierintegration_expired_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organizationsupplierintegeration',
            table='supplier_organization_integration',
        ),
    ]
