# Generated by Django 5.0.6 on 2024-11-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0015_alter_organizationsupplierintegeration_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lookupsupplierintegration", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="organizationsupplierintegeration",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="supplierintegration", options={"ordering": ["-created_at"]},
        ),
    ]
