# Generated by Django 5.0.6 on 2025-01-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0016_alter_lookupsupplierintegration_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierintegration",
            name="is_init",
            field=models.BooleanField(default=False),
        ),
    ]
