# Generated by Django 5.0.6 on 2025-01-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0017_supplierintegration_is_init"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lookupsupplierintegration",
            name="integration_type",
            field=models.CharField(
                choices=[
                    ("Flights", "Flights"),
                    ("Hotels", "Hotels"),
                    ("Rail", "Rail"),
                    ("Payment", "Payment"),
                    ("Transfers", "Transfers"),
                ],
                max_length=500,
            ),
        ),
    ]
