# Generated by Django 5.0.6 on 2025-01-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0018_alter_lookupsupplierintegration_integration_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierintegration",
            name="integration_type",
            field=models.CharField(
                choices=[
                    ("Flights", "Flights"),
                    ("Hotels", "Hotels"),
                    ("Rail", "Rail"),
                    ("Payment", "Payment"),
                    ("Transfers", "Transfers"),
                ],
                max_length=500,
            ),
        ),
    ]
