# Generated by Django 5.0.6 on 2025-02-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0019_alter_supplierintegration_integration_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierintegration",
            name="custom_filter",
            field=models.JSONField(default={}, null=True),
        ),
    ]
