# Generated by Django 5.0.6 on 2025-02-24 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0020_supplierintegration_custom_filter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplierintegration",
            name="custom_filter",
        ),
    ]
