# Generated by Django 5.0.6 on 2025-03-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0021_remove_supplierintegration_custom_filter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierintegration",
            name="integration_type",
            field=models.CharField(
                choices=[
                    ("Flights", "Flights"),
                    ("Hotels", "Hotels"),
                    ("Rail", "Rail"),
                    ("Payment", "Payment"),
                    ("Transfers", "Transfers"),
                    ("Bus", "Bus"),
                ],
                max_length=500,
            ),
        ),
    ]
