# Generated by Django 5.0.6 on 2025-03-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0022_alter_supplierintegration_integration_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lookupsupplierintegration",
            name="integration_type",
            field=models.CharField(
                choices=[
                    ("Flights", "Flights"),
                    ("Hotels", "Hotels"),
                    ("Rail", "Rail"),
                    ("Payment", "Payment"),
                    ("Transfers", "Transfers"),
                    ("Bus", "Bus"),
                ],
                max_length=500,
            ),
        ),
    ]
