# Generated by Django 5.0.6 on 2025-03-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0023_alter_lookupsupplierintegration_integration_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierintegration",
            name="token",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
