# Generated by Django 5.0.6 on 2024-08-08 07:32

import ckeditor.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0023_lookuppermission_admin1space1panel_delete_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [


        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("name", models.CharField(max_length=500)),
                ("url", models.ImageField(upload_to="gallery")),
                ("module", models.CharField(max_length=400)),
            ],
            options={"db_table": "gallery",},
        ),
        migrations.CreateModel(
            name="HolidaySKU",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("slug", models.SlugField(max_length=500, null=True, unique=True)),
                ("name", models.CharField(max_length=500)),
                ("location", models.CharField(max_length=500)),
                ("days", models.IntegerField()),
                ("nights", models.IntegerField()),
                (
                    "inclusions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500), size=None
                    ),
                ),
                (
                    "exclusion",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500), size=None
                    ),
                ),
                ("itinerary", models.JSONField()),
                ("overview", ckeditor.fields.RichTextField()),
                ("terms", ckeditor.fields.RichTextField()),
                ("status", models.BooleanField(default=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.lookupcountry",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_holiday_sku",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_holiday_sku",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "holiday_sku",},
        ),
        migrations.CreateModel(
            name="HolidaySKUImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                (
                    "gallery_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.gallery",
                    ),
                ),
                (
                    "sku_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holiday_app.holidaysku",
                    ),
                ),
            ],
            options={"db_table": "holiday_sku_image",},
        ),
        migrations.CreateModel(
            name="HolidaySKUInclusion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("flight", models.BooleanField(default=False)),
                ("hotel", models.BooleanField(default=False)),
                ("transfer", models.BooleanField(default=False)),
                ("meals", models.BooleanField(default=False)),
                ("visa", models.BooleanField(default=False)),
                ("sight_seeing", models.BooleanField(default=False)),
                (
                    "sku_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holiday_app.holidaysku",
                    ),
                ),
            ],
            options={"db_table": "holiday_sku_inclusion",},
        ),
        migrations.CreateModel(
            name="HolidaySKUPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "country_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.lookupcountry",
                    ),
                ),
                (
                    "sku_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holiday_app.holidaysku",
                    ),
                ),
            ],
            options={"db_table": "holiday_sku_price",},
        ),
        migrations.CreateModel(
            name="HolidayThemeMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("name", models.CharField(max_length=500)),
                ("status", models.BooleanField(default=True)),
                (
                    "icon_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.gallery",
                    ),
                ),
            ],
            options={"db_table": "holiday_theme_master",},
        ),
        migrations.CreateModel(
            name="HolidaySKUTheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                (
                    "sku_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holiday_app.holidaysku",
                    ),
                ),
                (
                    "theme_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holiday_app.holidaythememaster",
                    ),
                ),
            ],
            options={"db_table": "holiday_sku_theme",},
        ),
    ]
