# Generated by Django 5.0.6 on 2024-08-13 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holiday_app", "0001_initial"),
        (
            "users",
            "0025_lookuppermission_admin1space1panel_holiday_product_delete_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="holidayskuprice",
            name="country_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.country"
            ),
        ),
    ]
