# Generated by Django 5.0.6 on 2024-08-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holiday_app", "0002_alter_holidayskuprice_country_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="holidaysku", name="status",),
    ]
