# Generated by Django 5.0.6 on 2024-08-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holiday_app", "0003_remove_holidaysku_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="holidaysku",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Pending", "Pending"),
                    ("Inactive", "Inactive"),
                    ("Rejected", "Rejected"),
                ],
                max_length=300,
                null=True,
            ),
        ),
    ]
