# Generated by Django 5.0.6 on 2024-08-13 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holiday_app", "0004_holidaysku_status"),
        (
            "users",
            "0025_lookuppermission_admin1space1panel_holiday_product_delete_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="holidaysku",
            name="organization_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.organization",
            ),
        ),
    ]
