# Generated by Django 4.2.6 on 2024-08-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holiday_app", "0005_holidaysku_organization_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="module",
            field=models.CharField(
                choices=[
                    ("flight", "flight"),
                    ("hotel", "hotel"),
                    ("holiday", "holiday"),
                ],
                max_length=400,
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="url",
            field=models.ImageField(upload_to="btob/gallery"),
        ),
    ]
