# Generated by Django 4.2.6 on 2024-08-19 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("holiday_app", "0006_alter_gallery_module_alter_gallery_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holidayskuimage",
            name="gallery_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.gallery"
            ),
        ),
        migrations.AlterField(
            model_name="holidaythememaster",
            name="icon_url",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.gallery"
            ),
        ),
        migrations.DeleteModel(
            name="Gallery",
        ),
    ]
