# Generated by Django 4.2.6 on 2024-08-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holiday_app", "0007_alter_holidayskuimage_gallery_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="holidaysku",
            name="place",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
