# Generated by Django 4.2.6 on 2024-08-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holiday_app", "0008_holidaysku_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="holidaysku",
            name="duration_max",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="holidaysku",
            name="duration_min",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
