# Generated by Django 4.2.6 on 2024-08-29 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("holiday_app", "0009_holidaysku_duration_max_holidaysku_duration_min"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="holidaysku",
            name="duration_max",
        ),
        migrations.RemoveField(
            model_name="holidaysku",
            name="duration_min",
        ),
    ]
