# Generated by Django 4.2.6 on 2024-09-03 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("holiday_app", "0010_remove_holidaysku_duration_max_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HolidayEnquiry",
            fields=[
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=200)),
                ("date_of_travel", models.DateField()),
                ("pax_count", models.IntegerField()),
                ("enquiry_reference_id", models.TextField(null=True)),
                (
                    "holiday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holiday_app.holidaysku",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "holiday_enquiry",
            },
        ),
        migrations.CreateModel(
            name="HolidayEnquiryStatus",
            fields=[
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=5000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "holiday_enquiry_status",
            },
        ),
        migrations.CreateModel(
            name="HolidayEnquiryHistory",
            fields=[
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("enquiry_reference_id", models.TextField(null=True)),
                (
                    "holiday_enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holiday_app.holidayenquiry",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holiday_app.holidayenquirystatus",
                    ),
                ),
            ],
            options={
                "db_table": "holiday_enquiry_history",
            },
        ),
    ]
