# Generated by Django 4.2.6 on 2024-09-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holiday_app", "0011_holidayenquiry_holidayenquirystatus_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="holidayenquiry",
            old_name="enquiry_reference_id",
            new_name="enquiry_ref_id",
        ),
        migrations.RenameField(
            model_name="holidayenquiry",
            old_name="holiday",
            new_name="holiday_id",
        ),
        migrations.RenameField(
            model_name="holidayenquiry",
            old_name="user",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="holidayenquiryhistory",
            old_name="holiday_enquiry",
            new_name="holiday_enquiry_id",
        ),
        migrations.RemoveField(
            model_name="holidayenquiryhistory",
            name="enquiry_reference_id",
        ),
        migrations.AddField(
            model_name="holidayenquiryhistory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
