# Generated by Django 4.2.6 on 2024-09-04 06:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "holiday_app",
            "0012_rename_enquiry_reference_id_holidayenquiry_enquiry_ref_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="holidayenquiry",
            old_name="user_id",
            new_name="user",
        ),
    ]
