# Generated by Django 5.0.6 on 2024-09-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holiday_app", "0014_holidayfavourite"),
    ]

    operations = [
        migrations.DeleteModel(name="HolidayFavourite",),
    ]
