# Generated by Django 5.0.6 on 2024-09-10 04:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holiday_app", "0015_delete_holidayfavourite"),
        ("users", "0032_errorlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="HolidayFavourite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                (
                    "country_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.country"
                    ),
                ),
                (
                    "sku_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="holiday_app.holidaysku",
                    ),
                ),
            ],
            options={"db_table": "holiday_favourite",},
        ),
    ]
