# Generated by Django 5.0.6 on 2024-09-10 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holiday_app", "0016_holidayfavourite"),
        ("users", "0032_errorlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holidayfavourite",
            name="country_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.lookupcountry"
            ),
        ),
    ]