# Generated by Django 5.0.6 on 2024-09-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holiday_app", "0017_alter_holidayfavourite_country_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="holidaysku",
            name="sub_heading",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
