# Generated by Django 5.0.6 on 2024-09-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holiday_app", "0018_holidaysku_sub_heading"),
    ]

    operations = [
        migrations.RemoveField(model_name="holidayfavourite", name="country_id",),
    ]
