# Generated by Django 5.0.6 on 2024-09-17 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holiday_app", "0019_remove_holidayfavourite_country_id"),
        (
            "users",
            "0038_rename_account_code_organization_easy_link_account_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="holidayfavourite",
            name="country_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.country",
            ),
        ),
    ]
