# Generated by Django 4.2.6 on 2024-09-26 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("holiday_app", "0020_holidayfavourite_country_id"),
    ]

    operations = [
        
    ]
