# Generated by Django 5.0.6 on 2024-09-27 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_app', '0021_rename_holidayenquirystatus_lookupholidayenquirystatus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HolidayEnquiryStatus',
            new_name='LookUpHolidayEnquiryStatus',
        ),
        migrations.AddField(
            model_name='holidayenquiryhistory',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_holiday_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='holidayenquiryhistory',
            name='holiday_enquiry_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='holiday_app.holidayenquiry'),
        ),
migrations.AlterField(
    model_name='holidayenquiryhistory',
    name='status',
    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='holiday_app.lookupholidayenquirystatus'),
)
    ]
