# Generated by Django 5.0.6 on 2024-10-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "holiday_app",
            "0022_rename_holidayenquirystatus_lookupholidayenquirystatus_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="holidayskuprice",
            name="b2b_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
