# Generated by Django 5.0.6 on 2024-10-01 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holiday_app", "0023_holidayskuprice_b2b_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="holidayskuprice", old_name="b2b_price", new_name="bta_price",
        ),
    ]
