# Generated by Django 5.0.6 on 2024-11-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_app', '0024_rename_b2b_price_holidayskuprice_bta_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidayenquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='holidayenquiryhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='holidayfavourite',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='holidaysku',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='holidayskuimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='holidayskuinclusion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='holidayskuprice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='holidayskutheme',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='holidaythememaster',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='lookupholidayenquirystatus',
            options={'ordering': ['-created_at']},
        ),
    ]
