# Generated by Django 5.0.6 on 2024-11-11 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holiday_app", "0025_alter_holidayenquiry_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holidayskutheme",
            name="sku_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holidayskutheme",
                to="holiday_app.holidaysku",
            ),
        ),
    ]
