# Generated by Django 5.0.6 on 2024-11-11 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holiday_app", "0026_alter_holidayskutheme_sku_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holidayskuimage",
            name="sku_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holidayskuimage",
                to="holiday_app.holidaysku",
            ),
        ),
    ]
