# Generated by Django 5.0.6 on 2024-11-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_app', '0027_alter_holidayskuimage_sku_id'),
        ('users', '0076_lookuppermission_flight_search_create_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaysku',
            name='country',
        ),
        migrations.AddField(
            model_name='holidaysku',
            name='country',
            field=models.ManyToManyField(to='users.lookupcountry'),
        ),
    ]
