# Generated by Django 5.0.6 on 2024-11-22 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holiday_app", "0028_remove_holidaysku_country_holidaysku_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holidayskuprice",
            name="sku_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holidaysku_price",
                to="holiday_app.holidaysku",
            ),
        ),
    ]
