# Generated by Django 5.0.6 on 2024-11-25 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holiday_app", "0029_alter_holidayskuprice_sku_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holidayskuinclusion",
            name="sku_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holidayskuinclusion",
                to="holiday_app.holidaysku",
            ),
        ),
    ]
