# Generated by Django 5.0.6 on 2024-11-28 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holiday_app", "0031_alter_holidayskuprice_sku_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holidayenquiryhistory",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="holiday_app.lookupholidayenquirystatus",
            ),
        ),
    ]
