# Generated by Django 5.0.6 on 2024-12-03 05:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("holiday_app", "0032_alter_holidayenquiryhistory_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="holidayskuprice",
            old_name="bta_price",
            new_name="company_markup",
        ),
    ]
