# Generated by Django 5.0.6 on 2024-12-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holiday_app", "0033_rename_bta_price_holidayskuprice_company_markup"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookupholidayenquirystatus",
            name="progression_order",
            field=models.IntegerField(default=0),
        ),
    ]
