# Generated by Django 5.0.6 on 2024-09-27 04:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=200)),
                ('currency_code', models.CharField(max_length=200)),
                ('currency_symbol', models.CharField(max_length=200)),
                ('inr_conversion_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LookupAirports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('code', models.CharField(max_length=300, null=True)),
                ('city', models.CharField(max_length=300, null=True)),
                ('index', models.IntegerField(null=True)),
                ('common', models.CharField(max_length=400, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('nearest', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), null=True, size=None)),
            ],
            options={
                'db_table': 'lookup_airports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LookupCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('calling_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'lookup_country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LookupOrganizationTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('master', 'master'), ('agency', 'agency'), ('distributor', 'distributor'), ('enterprises', 'enterprises'), ('out_api', 'out_api'), ('supplier', 'supplier')], max_length=500)),
            ],
            options={
                'db_table': 'lookup_organization_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=2000)),
                ('is_iata_or_arc', models.BooleanField()),
                ('iata_or_arc_code', models.CharField(blank=True, max_length=2000, null=True)),
                ('address', models.TextField()),
                ('state', models.CharField(blank=True, max_length=2000, null=True)),
                ('organization_zipcode', models.IntegerField()),
                ('organization_pan_number', models.CharField(blank=True, max_length=2000, null=True)),
                ('organization_gst_number', models.CharField(blank=True, max_length=2000, null=True)),
                ('organization_tax_number', models.CharField(blank=True, max_length=2000, null=True)),
                ('organization_currency', models.CharField(max_length=200)),
                ('easy_link_account_code', models.CharField(blank=True, max_length=2000, null=True)),
                ('easy_link_account_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive'), ('pending', 'pending')], default='pending', max_length=2000, null=True)),
            ],
            options={
                'db_table': 'organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('phone_code', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_first_time', models.BooleanField(default=True)),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('agency_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'user_details',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
