# Generated by Django 5.0.6 on 2025-03-14 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0024_alter_supplierintegration_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.CharField(blank=True, max_length=500, null=True)),
                ('city_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.FloatField(blank=True, null=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplierintegration')),
            ],
            options={
                'db_table': 'bus_cities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city_name'], name='bus_cities_city_na_8f2bd0_idx')],
            },
        ),
    ]
