# Generated by Django 5.0.6 on 2025-03-19 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0001_initial"),
        ("users", "0135_lookuppermission_transfers_search_create_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buscity",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.lookupcountry",
            ),
        ),
    ]
