# Generated by Django 5.0.6 on 2025-03-25 07:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0002_buscity_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("session_id", models.CharField(max_length=100)),
                ("display_id", models.CharField(max_length=30)),
                ("segment_id", models.CharField(default="", max_length=100)),
                (
                    "gst_details",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("pax_count", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(max_length=50)),
                ("error", models.CharField(blank=True, max_length=4000, null=True)),
                ("contact", models.CharField(max_length=500)),
            ],
            options={"db_table": "bus_booking", "managed": False,},
        ),
        migrations.CreateModel(
            name="BusBookingFareDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("published_fare", models.FloatField(default=0)),
                ("offered_fare", models.FloatField(default=0)),
                ("organization_discount", models.FloatField(default=0)),
                ("dist_agent_markup", models.FloatField(default=0)),
                ("dist_agent_cashback", models.FloatField(default=0)),
                (
                    "fare_breakdown",
                    models.CharField(blank=True, max_length=4000, null=True),
                ),
                ("tax", models.FloatField(default=0)),
            ],
            options={"db_table": "bus_booking_fare_detail", "managed": False,},
        ),
        migrations.CreateModel(
            name="BusBookingPaxDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("pax_id", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("first_name", models.CharField(blank=True, max_length=300, null=True)),
                ("last_name", models.CharField(blank=True, max_length=300, null=True)),
                ("dob", models.CharField(blank=True, max_length=300, null=True)),
                ("seat_id", models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={"db_table": "bus_booking_pax_detail", "managed": False,},
        ),
        migrations.CreateModel(
            name="BusBookingPaymentDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("wallet", "wallet"),
                            ("stripe", "stripe"),
                            ("razor_pay", "razor_pay"),
                        ],
                        max_length=100,
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("timestamp", models.BigIntegerField(editable=False, null=True)),
                ("new_published_fare", models.FloatField(default=0)),
                ("new_offered_fare", models.FloatField(default=0)),
                ("supplier_published_fare", models.FloatField(default=0)),
                ("supplier_offered_fare", models.FloatField(default=0)),
            ],
            options={"db_table": "bus_booking_payment_detail", "managed": False,},
        ),
        migrations.CreateModel(
            name="BusBookingSearchDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("travel_date", models.CharField(blank=True, max_length=50, null=True)),
                ("pickup_id", models.CharField(max_length=100)),
                ("pickup_name", models.CharField(max_length=100)),
                ("pickup_time", models.CharField(max_length=100)),
                ("pickup_address", models.CharField(max_length=100)),
                ("pickup_contact", models.CharField(max_length=100)),
                ("dropoff_id", models.CharField(max_length=100)),
                ("dropoff_name", models.CharField(max_length=100)),
                ("dropoff_time", models.CharField(max_length=100)),
                ("dropoff_address", models.CharField(max_length=100)),
                ("dropoff_contact", models.CharField(max_length=100)),
            ],
            options={"db_table": "bus_booking_search_detail", "managed": False,},
        ),
    ]
