# Generated by Django 5.0.6 on 2025-03-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0003_busbooking_busbookingfaredetail_busbookingpaxdetail_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="BusBooking",),
        migrations.DeleteModel(name="BusBookingFareDetail",),
        migrations.DeleteModel(name="BusBookingPaxDetail",),
        migrations.DeleteModel(name="BusBookingPaymentDetail",),
        migrations.DeleteModel(name="BusBookingSearchDetail",),
    ]
