# Generated by Django 5.0.6 on 2025-03-25 10:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0004_delete_busbooking_delete_busbookingfaredetail_and_more"),
        ("shared", "0036_alter_paymentdetail_payment_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("session_id", models.CharField(max_length=100)),
                ("display_id", models.CharField(max_length=30)),
                ("segment_id", models.CharField(default="", max_length=100)),
                (
                    "gst_details",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("pax_count", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(max_length=50)),
                ("error", models.CharField(blank=True, max_length=4000, null=True)),
                ("contact", models.CharField(max_length=500)),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modified_busbooking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "bus_booking",},
        ),
        migrations.CreateModel(
            name="BusBookingPaxDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("first_name", models.CharField(blank=True, max_length=300, null=True)),
                ("last_name", models.CharField(blank=True, max_length=300, null=True)),
                ("dob", models.CharField(blank=True, max_length=300, null=True)),
                ("seat_id", models.CharField(blank=True, max_length=300, null=True)),
                ("seat_type", models.CharField(blank=True, max_length=300, null=True)),
                ("pax_type", models.CharField(blank=True, max_length=300, null=True)),
                ("gender", models.CharField(blank=True, max_length=300, null=True)),
                ("misc", models.JSONField(blank=True, null=True)),
                (
                    "booking_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buses.busbooking",
                    ),
                ),
            ],
            options={"db_table": "bus_booking_pax_detail",},
        ),
        migrations.CreateModel(
            name="BusBookingFareDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("published_fare", models.FloatField(default=0)),
                ("offered_fare", models.FloatField(default=0)),
                ("organization_discount", models.FloatField(default=0)),
                ("dist_agent_markup", models.FloatField(default=0)),
                ("dist_agent_cashback", models.FloatField(default=0)),
                (
                    "fare_breakdown",
                    models.CharField(blank=True, max_length=4000, null=True),
                ),
                ("tax", models.FloatField(default=0)),
                (
                    "pax_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buses.busbookingpaxdetail",
                    ),
                ),
            ],
            options={"db_table": "bus_booking_fare_detail",},
        ),
        migrations.CreateModel(
            name="BusBookingPaymentDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("wallet", "wallet"),
                            ("stripe", "stripe"),
                            ("razor_pay", "razor_pay"),
                        ],
                        max_length=100,
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("timestamp", models.BigIntegerField(editable=False, null=True)),
                ("new_published_fare", models.FloatField(default=0)),
                ("new_offered_fare", models.FloatField(default=0)),
                ("supplier_published_fare", models.FloatField(default=0)),
                ("supplier_offered_fare", models.FloatField(default=0)),
                (
                    "payment_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared.paymentdetail",
                    ),
                ),
            ],
            options={"db_table": "bus_booking_payment_detail",},
        ),
        migrations.AddField(
            model_name="busbooking",
            name="bus_payment_details",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="buses.busbookingpaymentdetail",
            ),
        ),
        migrations.CreateModel(
            name="BusBookingSearchDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("travel_date", models.CharField(blank=True, max_length=50, null=True)),
                ("pickup_id", models.CharField(max_length=100)),
                ("pickup_name", models.CharField(max_length=100)),
                ("pickup_time", models.CharField(max_length=100)),
                ("pickup_address", models.CharField(max_length=100)),
                ("pickup_contact", models.CharField(max_length=100)),
                ("dropoff_id", models.CharField(max_length=100)),
                ("dropoff_name", models.CharField(max_length=100)),
                ("dropoff_time", models.CharField(max_length=100)),
                ("dropoff_address", models.CharField(max_length=100)),
                ("dropoff_contact", models.CharField(max_length=100)),
                (
                    "from_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup",
                        to="buses.buscity",
                    ),
                ),
                (
                    "to_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dropoff",
                        to="buses.buscity",
                    ),
                ),
            ],
            options={"db_table": "bus_booking_search_detail",},
        ),
        migrations.AddField(
            model_name="busbooking",
            name="search_details",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="buses.busbookingsearchdetail",
            ),
        ),
    ]
