# Generated by Django 5.0.6 on 2025-03-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0005_busbooking_busbookingpaxdetail_busbookingfaredetail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="busbooking",
            name="misc",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
