# Generated by Django 5.0.6 on 2025-03-25 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0006_busbooking_misc"),
        ("shared", "0036_alter_paymentdetail_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busbookingpaymentdetail",
            name="payment_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shared.paymentdetail",
            ),
        ),
    ]
