# Generated by Django 5.0.6 on 2025-03-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0008_busbooking_booked_at_busbooking_cancelled_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="busbooking",
            name="arrival_time",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="busbooking",
            name="bus_type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="busbooking",
            name="departure_time",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="busbooking",
            name="operator",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="busbooking",
            name="provider",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="busbookingpaxdetail",
            name="seat_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
