# Generated by Django 5.0.6 on 2025-03-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0009_busbooking_arrival_time_busbooking_bus_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="busbooking", old_name="user_id", new_name="user",
        ),
        migrations.RenameField(
            model_name="busbookingsearchdetail",
            old_name="to_id",
            new_name="destination",
        ),
        migrations.RenameField(
            model_name="busbookingsearchdetail", old_name="from_id", new_name="origin",
        ),
    ]
