# Generated by Django 5.0.6 on 2025-03-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0010_rename_user_id_busbooking_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="busbookingfaredetail",
            old_name="pax_id",
            new_name="pax",
        ),
        migrations.RenameField(
            model_name="busbookingpaxdetail",
            old_name="booking_id",
            new_name="booking",
        ),
    ]
