# Generated by Django 5.0.6 on 2025-03-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0011_rename_pax_id_busbookingfaredetail_pax_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="busbooking",
            old_name="search_details",
            new_name="search_detail",
        ),
    ]
