# Generated by Django 5.0.6 on 2025-03-26 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0012_rename_search_details_busbooking_search_detail"),
        ("suppliers", "0024_alter_supplierintegration_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="busbooking",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="suppliers.supplierintegration",
            ),
        ),
    ]
