# Generated by Django 5.0.6 on 2025-03-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0013_busbooking_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="busbooking",
            name="invoice_amount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="busbooking",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="busbooking",
            name="pnr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="busbooking",
            name="ticket_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
