# Generated by Django 5.0.6 on 2025-03-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0014_busbooking_invoice_amount_busbooking_invoice_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="busbooking",
            name="cancellation_details",
            field=models.JSONField(default=dict),
        ),
    ]
