# Generated by Django 5.0.6 on 2025-02-04 07:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferBookingPaymentDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("wallet", "wallet"),
                            ("stripe", "stripe"),
                            ("razor_pay", "razor_pay"),
                        ],
                        max_length=100,
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("timestamp", models.BigIntegerField(editable=False, null=True)),
                ("new_published_fare", models.FloatField(default=0)),
                ("new_offered_fare", models.FloatField(default=0)),
                ("supplier_published_fare", models.FloatField(default=0)),
                ("supplier_offered_fare", models.FloatField(default=0)),
            ],
            options={
                "db_table": "transfer_booking_payment_detail",
            },
        ),
        migrations.CreateModel(
            name="TransferBookingSearchDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                (
                    "transfer_time",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "transfer_date",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("pax_count", models.IntegerField(blank=True, null=True)),
                ("preferred_language", models.IntegerField(blank=True, null=True)),
                ("alternate_language", models.IntegerField(blank=True, null=True)),
                ("pickup_code", models.IntegerField(blank=True, null=True)),
                (
                    "pickup_point_code",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("city_id", models.IntegerField(blank=True, null=True)),
                ("dropoff_code", models.IntegerField(blank=True, null=True)),
                (
                    "dropoff_point_code",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "country_code",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "preferred_currency",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "transfer_booking_search_detail",
            },
        ),
        migrations.CreateModel(
            name="TransferBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("display_id", models.CharField(max_length=300)),
                ("session_id", models.CharField(max_length=300)),
                ("pax_count", models.IntegerField(blank=True, null=True)),
                ("pax_data", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "confirmation_number",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("booking_ref_no", models.CharField(max_length=300)),
                ("booking_id", models.CharField(blank=True, max_length=500, null=True)),
                ("status", models.CharField(max_length=100)),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modified_transferbooking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transfers_booking.transferbookingpaymentdetail",
                    ),
                ),
                (
                    "search_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transfers_booking.transferbookingsearchdetail",
                    ),
                ),
            ],
            options={
                "db_table": "transfer_booking",
            },
        ),
        migrations.CreateModel(
            name="TransferBookingContactDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("pax_id", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("first_name", models.CharField(blank=True, max_length=300, null=True)),
                ("last_name", models.CharField(blank=True, max_length=300, null=True)),
                ("pan", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "booking_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transfers_booking.transferbooking",
                    ),
                ),
            ],
            options={
                "db_table": "transfer_booking_contact_detail",
            },
        ),
        migrations.CreateModel(
            name="TransferBookingFareDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("published_fare", models.FloatField(default=0)),
                ("offered_fare", models.FloatField(default=0)),
                ("organization_discount", models.FloatField(default=0)),
                ("dist_agent_markup", models.FloatField(default=0)),
                ("dist_agent_cashback", models.FloatField(default=0)),
                (
                    "fare_breakdown",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "booking_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transfers_booking.transferbooking",
                    ),
                ),
            ],
            options={
                "db_table": "transfer_booking_fare_detail",
            },
        ),
        migrations.CreateModel(
            name="TransferBookingLocationDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("type", models.IntegerField()),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                ("date", models.CharField(blank=True, max_length=300, null=True)),
                ("time", models.CharField(blank=True, max_length=300, null=True)),
                ("code", models.CharField(blank=True, max_length=400, null=True)),
                ("point_code", models.CharField(blank=True, max_length=500, null=True)),
                ("details", models.CharField(blank=True, max_length=600, null=True)),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[("pickup", "pickup"), ("drop", "drop")], max_length=300
                    ),
                ),
                (
                    "booking_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transfers_booking.transferbooking",
                    ),
                ),
            ],
            options={
                "db_table": "transfer_booking_location_detail",
            },
        ),
    ]
