# Generated by Django 5.0.6 on 2025-02-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers_booking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transferbookinglocationdetail",
            name="point_code",
        ),
        migrations.AlterField(
            model_name="transferbookinglocationdetail",
            name="transfer_type",
            field=models.CharField(
                choices=[("pickup", "pickup"), ("drop", "drop")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="transferbookinglocationdetail",
            name="type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
