# Generated by Django 5.0.6 on 2025-03-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transfers_booking",
            "0002_remove_transferbookinglocationdetail_point_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transferbooking",
            name="segment_id",
            field=models.CharField(default="", max_length=300),
        ),
    ]
