# Generated by Django 5.0.6 on 2025-03-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers_booking", "0003_transferbooking_segment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferbookinglocationdetail",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="transferbookinglocationdetail",
            name="date",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="transferbookinglocationdetail",
            name="time",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
