# Generated by Django 5.0.6 on 2025-03-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers_booking", "0004_alter_transferbookinglocationdetail_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferbookinglocationdetail",
            name="ZipCode",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
