# Generated by Django 5.0.6 on 2025-03-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers_booking", "0005_transferbookinglocationdetail_zipcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferbooking",
            name="transfer_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="transferbooking",
            name="booking_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="transferbooking",
            name="booking_ref_no",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="transferbooking",
            name="confirmation_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="transferbooking",
            name="display_id",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="transferbooking",
            name="segment_id",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="transferbooking",
            name="session_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="transferbooking",
            name="status",
            field=models.CharField(max_length=50),
        ),
    ]
