# Generated by Django 5.0.6 on 2025-03-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers_booking", "0006_transferbooking_transfer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferbooking",
            name="error",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
