# Generated by Django 5.0.6 on 2025-03-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers_booking", "0007_transferbooking_error"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transferbookingsearchdetail",
            name="dropoff_code",
        ),
        migrations.RemoveField(
            model_name="transferbookingsearchdetail",
            name="pickup_code",
        ),
        migrations.AddField(
            model_name="transferbookingsearchdetail",
            name="adult_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transferbookingsearchdetail",
            name="dropoff_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="transferbookingsearchdetail",
            name="pickup_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="transferbookingsearchdetail",
            name="country_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="transferbookingsearchdetail",
            name="dropoff_point_code",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="transferbookingsearchdetail",
            name="pickup_point_code",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="transferbookingsearchdetail",
            name="preferred_currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="transferbookingsearchdetail",
            name="transfer_date",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="transferbookingsearchdetail",
            name="transfer_time",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
