# Generated by Django 5.0.6 on 2025-03-11 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "transfers_booking",
            "0008_remove_transferbookingsearchdetail_dropoff_code_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transferbookingsearchdetail",
            name="adult_count",
        ),
    ]
