# Generated by Django 5.0.6 on 2025-03-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers_booking", "0009_remove_transferbookingsearchdetail_adult_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferbookinglocationdetail",
            name="AddressLine1",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="transferbookinglocationdetail",
            name="AddressLine2",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="transferbookinglocationdetail",
            name="city_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transferbookinglocationdetail",
            name="country",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
