# Generated by Django 5.0.6 on 2025-03-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transfers_booking",
            "0010_transferbookinglocationdetail_addressline1_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferbookinglocationdetail",
            name="details",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
