# Generated by Django 5.0.6 on 2025-03-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers_booking", "0011_alter_transferbookinglocationdetail_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferbookingfaredetail",
            name="fare_breakdown",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
