# Generated by Django 5.0.6 on 2025-03-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers_booking", "0012_alter_transferbookingfaredetail_fare_breakdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferbooking",
            name="category",
            field=models.CharField(default=" ", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transferbooking",
            name="max_bags",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transferbooking",
            name="max_passengers",
            field=models.CharField(default=".", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transferbooking",
            name="error",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
