# Generated by Django 5.0.6 on 2025-03-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transfers_booking",
            "0013_transferbooking_category_transferbooking_max_bags_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transferbooking",
            name="url",
            field=models.CharField(default=".", max_length=100),
            preserve_default=False,
        ),
    ]
