# Generated by Django 5.0.6 on 2025-03-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers_booking", "0014_transferbooking_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferbooking",
            name="category",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="transferbooking",
            name="max_bags",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="transferbooking",
            name="max_passengers",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="transferbooking",
            name="url",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
