# Generated by Django 5.0.6 on 2025-03-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers_booking", "0015_alter_transferbooking_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferbookingfaredetail",
            name="tax",
            field=models.FloatField(default=0),
        ),
    ]
