# Generated by Django 5.0.6 on 2025-03-20 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0036_alter_paymentdetail_payment_method"),
        ("transfers_booking", "0016_transferbookingfaredetail_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferbookingpaymentdetail",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shared.paymentdetail",
            ),
        ),
    ]
