# Generated by Django 5.0.6 on 2025-03-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers_booking", "0017_transferbookingpaymentdetail_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferbooking",
            name="booking_remarks",
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
