# Generated by Django 5.0.6 on 2025-03-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transfers_booking", "0018_transferbooking_booking_remarks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transferbooking",
            old_name="payment_details",
            new_name="payment_detail",
        ),
        migrations.RenameField(
            model_name="transferbooking",
            old_name="search_details",
            new_name="search_detail",
        ),
        migrations.RenameField(
            model_name="transferbooking",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="transferbookingcontactdetail",
            old_name="booking_id",
            new_name="booking",
        ),
        migrations.RenameField(
            model_name="transferbookingfaredetail",
            old_name="booking_id",
            new_name="booking",
        ),
        migrations.RenameField(
            model_name="transferbookinglocationdetail",
            old_name="booking_id",
            new_name="booking",
        ),
    ]
