# Generated by Django 5.0.6 on 2025-03-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transfers_booking",
            "0019_rename_payment_details_transferbooking_payment_detail_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transferbookingfaredetail",
            name="cancellation_details",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
