# Generated by Django 5.0.6 on 2025-04-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers_booking", "0020_transferbookingfaredetail_cancellation_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferbookingcontactdetail",
            name="email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
