# Generated by Django 5.0.6 on 2025-04-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers_booking", "0021_transferbookingcontactdetail_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferbookingcontactdetail",
            name="country_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
