# Generated by Django 5.0.6 on 2025-04-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers_booking", "0022_transferbookingcontactdetail_country_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferbookinglocationdetail",
            name="ZipCode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
