# Generated by Django 5.0.6 on 2025-03-27 07:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0145_lookuppermission_bus_booking1space1history_create_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceAsegoCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category_code",
                    models.UUIDField(
                        db_column="Category Code",
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(db_column="Description", max_length=255),
                ),
            ],
            options={
                "db_table": "insurance_asego_category",
            },
        ),
        migrations.CreateModel(
            name="InsuranceAsegoDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_code",
                    models.IntegerField(db_column="Document Code", unique=True),
                ),
                ("title", models.CharField(db_column="Title", max_length=255)),
                ("age_limit", models.IntegerField(db_column="Age Limit")),
                (
                    "authorization_required",
                    models.BooleanField(db_column="Authorization Required"),
                ),
            ],
            options={
                "db_table": "insurance_asego_documents",
            },
        ),
        migrations.CreateModel(
            name="InsuranceAsegoRiderMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rider_code",
                    models.UUIDField(
                        db_column="Rider Code",
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "amount",
                    models.CharField(
                        blank=True, db_column="Amount", max_length=255, null=True
                    ),
                ),
                (
                    "restricted_amount",
                    models.CharField(
                        blank=True,
                        db_column="RestrictedAmount",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "deductibles",
                    models.CharField(
                        blank=True, db_column="Deductibles", max_length=255, null=True
                    ),
                ),
                ("deductible_text", models.BooleanField(db_column="DeductibleText")),
                (
                    "currency",
                    models.CharField(
                        blank=True, db_column="Currency", max_length=30, null=True
                    ),
                ),
            ],
            options={
                "db_table": "insurance_asego_rider_master",
            },
        ),
        migrations.CreateModel(
            name="InsuranceAsegoVisitingCountry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(db_column="Description", max_length=255),
                ),
                ("reference", models.CharField(db_column="Reference", max_length=255)),
                (
                    "country",
                    models.ForeignKey(
                        db_column="Country Code",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.country",
                    ),
                ),
            ],
            options={
                "db_table": "insurance_asego_visiting_countries",
            },
        ),
        migrations.CreateModel(
            name="InsuranceAsegoPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_code",
                    models.UUIDField(
                        db_column="Plan Code",
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_column="Name", max_length=255)),
                ("day_plan", models.BooleanField(db_column="Day Plan")),
                (
                    "trawelltag_option",
                    models.BooleanField(db_column="Trawell Tag Option"),
                ),
                ("annual_plan", models.BooleanField(db_column="Annual Plan")),
                (
                    "category",
                    models.ForeignKey(
                        db_column="Category Code",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurance.insuranceasegocategory",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        db_column="Country Code",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurance.insuranceasegovisitingcountry",
                    ),
                ),
            ],
            options={
                "db_table": "insurance_asego_plan",
            },
        ),
        migrations.CreateModel(
            name="InsuranceAsegoPlanDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        db_column="Document Code",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurance.insuranceasegodocument",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        db_column="Plan Code",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurance.insuranceasegoplan",
                    ),
                ),
            ],
            options={
                "db_table": "insurance_asego_plan_documents",
                "unique_together": {("plan", "document")},
            },
        ),
        migrations.CreateModel(
            name="InsuranceAsegoPremiumChart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("age_limit", models.IntegerField(db_column="Age Limit")),
                ("day_limit", models.IntegerField(db_column="Day Limit")),
                (
                    "premium",
                    models.DecimalField(
                        db_column="Premium", decimal_places=2, max_digits=10
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurance.insuranceasegoplan",
                    ),
                ),
            ],
            options={
                "db_table": "insurance_asego_premium_chart",
                "unique_together": {("plan", "age_limit", "day_limit")},
            },
        ),
        migrations.CreateModel(
            name="InsuranceAsegoPlanRider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trawell_assist_charges_percent",
                    models.DecimalField(
                        db_column="Trawell Assist Charges Percent",
                        decimal_places=2,
                        max_digits=5,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurance.insuranceasegoplan",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurance.insuranceasegoridermaster",
                    ),
                ),
            ],
            options={
                "db_table": "insurance_asego_plan_riders",
                "unique_together": {("plan", "rider")},
            },
        ),
    ]
