# Generated by Django 5.0.6 on 2025-03-30 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsuranceAsegoDocument',
        ),
        migrations.DeleteModel(
            name='InsuranceAsegoPlanDocument',
        ),
    ]
