# Generated by Django 5.0.6 on 2025-04-02 12:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0002_remove_insuranceasegoplandocument_document_and_more"),
        ("shared", "0036_alter_paymentdetail_payment_method"),
        ("suppliers", "0025_alter_lookupsupplierintegration_integration_type_and_more"),
        (
            "users",
            "0151_lookuppermission_transfers_queues_cancelled1space1bookings_create_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceBookingSearchDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                (
                    "arrival_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "departure_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "insurance_booking_search_detail",
            },
        ),
        migrations.CreateModel(
            name="InsuranceBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("session_id", models.CharField(max_length=100)),
                ("display_id", models.CharField(max_length=30)),
                ("status", models.CharField(max_length=50)),
                ("error", models.CharField(blank=True, max_length=4000, null=True)),
                ("booked_at", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suppliers.supplierintegration",
                    ),
                ),
            ],
            options={
                "db_table": "insurance_booking",
            },
        ),
        migrations.CreateModel(
            name="InsuranceBookingPaxDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("first_name", models.CharField(blank=True, max_length=300, null=True)),
                ("last_name", models.CharField(blank=True, max_length=300, null=True)),
                ("dob", models.CharField(blank=True, max_length=300, null=True)),
                ("gender", models.CharField(blank=True, max_length=300, null=True)),
                ("misc", models.JSONField(blank=True, null=True)),
                ("address1", models.CharField(blank=True, max_length=1000, null=True)),
                ("address2", models.CharField(blank=True, max_length=1000, null=True)),
                ("passport", models.CharField(blank=True, max_length=300, null=True)),
                ("city", models.CharField(blank=True, max_length=300, null=True)),
                ("district", models.CharField(blank=True, max_length=300, null=True)),
                ("state", models.CharField(blank=True, max_length=300, null=True)),
                ("pincode", models.CharField(blank=True, max_length=300, null=True)),
                ("phone_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "nominee_name",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("relation", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "past_illness",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("addons", models.JSONField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurance.insurancebooking",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        db_column="Country Code",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.country",
                    ),
                ),
            ],
            options={
                "db_table": "insurance_booking_pax_detail",
            },
        ),
        migrations.CreateModel(
            name="InsuranceBookingFareDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("published_fare", models.FloatField(default=0)),
                ("offered_fare", models.FloatField(default=0)),
                ("organization_discount", models.FloatField(default=0)),
                ("dist_agent_markup", models.FloatField(default=0)),
                ("dist_agent_cashback", models.FloatField(default=0)),
                (
                    "fare_breakdown",
                    models.CharField(blank=True, max_length=4000, null=True),
                ),
                ("tax", models.FloatField(default=0)),
                (
                    "pax",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurance.insurancebookingpaxdetail",
                    ),
                ),
            ],
            options={
                "db_table": "insurance_booking_fare_detail",
            },
        ),
        migrations.CreateModel(
            name="InsuranceBookingPaymentDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("wallet", "wallet"),
                            ("stripe", "stripe"),
                            ("razor_pay", "razor_pay"),
                        ],
                        max_length=100,
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("timestamp", models.BigIntegerField(editable=False, null=True)),
                ("new_published_fare", models.FloatField(default=0)),
                ("new_offered_fare", models.FloatField(default=0)),
                ("supplier_published_fare", models.FloatField(default=0)),
                ("supplier_offered_fare", models.FloatField(default=0)),
                (
                    "payment_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared.paymentdetail",
                    ),
                ),
            ],
            options={
                "db_table": "insurance_booking_payment_detail",
            },
        ),
        migrations.AddField(
            model_name="insurancebooking",
            name="insurance_payment_details",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="insurance.insurancebookingpaymentdetail",
            ),
        ),
        migrations.AddField(
            model_name="insurancebooking",
            name="search_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="insurance.insurancebookingsearchdetail",
            ),
        ),
    ]
