# Generated by Django 5.0.6 on 2025-04-03 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0003_insurancebookingsearchdetail_insurancebooking_and_more"),
        ("users", "0152_remove_faremanagement_unique_uniqueconstraint_priority"),
    ]

    operations = [
        migrations.RenameField(
            model_name="insurancebookingsearchdetail",
            old_name="arrival_date",
            new_name="commensing_date",
        ),
        migrations.RenameField(
            model_name="insurancebookingsearchdetail",
            old_name="departure_date",
            new_name="end_date",
        ),
        migrations.AlterField(
            model_name="insurancebookingpaxdetail",
            name="country",
            field=models.ForeignKey(
                db_column="Country Code",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.lookupcountry",
            ),
        ),
    ]
