# Generated by Django 5.0.6 on 2025-04-04 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "insurance",
            "0004_rename_arrival_date_insurancebookingsearchdetail_commensing_date_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="insurancebooking",
            name="cancelled_at",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insurancebooking",
            name="cancelled_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insurance_cancelled_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="insurancebooking",
            name="misc",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insurancebooking",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insurance_modified_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="insurancebooking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insurance_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
