# Generated by Django 5.0.6 on 2025-04-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0005_insurancebooking_cancelled_at_and_more"),
        ("users", "0152_remove_faremanagement_unique_uniqueconstraint_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurancebookingpaxdetail",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.lookupcountry"
            ),
        ),
    ]
