# Generated by Django 5.0.6 on 2025-04-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0006_alter_insurancebookingpaxdetail_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insurancebookingpaxdetail",
            name="mobile_number",
        ),
    ]
