# Generated by Django 5.0.6 on 2025-04-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0007_remove_insurancebookingpaxdetail_mobile_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurancebookingpaxdetail",
            name="claimcode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="insurancebookingpaxdetail",
            name="document",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name="insurancebookingpaxdetail",
            name="policy",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="insurancebookingpaxdetail",
            name="reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
