# Generated by Django 5.0.6 on 2025-04-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0008_insurancebookingpaxdetail_claimcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurancebookingpaxdetail",
            name="status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
