# Generated by Django 5.0.6 on 2025-03-13 05:37

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0021_remove_supplierintegration_custom_filter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('hotel_code', models.CharField(max_length=100, unique=True)),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amenities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotelPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=10)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('order_api_endpoint', models.CharField(blank=True, max_length=250, null=True)),
                ('order_api_payload', models.JSONField(default=dict)),
                ('order_api_response', models.JSONField(default=dict)),
                ('is_callback_recieved', models.BooleanField(default=False)),
                ('callback_payload', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('status', models.CharField(choices=[('enquiry', 'enquiry'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('partially_cancelled', 'partially_cancelled'), ('cancelled', 'cancelled')], default='pending', max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplierintegration')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.hoteldetails')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_booking', to='hotels.hotelpayment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('room_code', models.CharField(max_length=300)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('booking_data', models.JSONField(default=dict)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.hoteldetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotelBookedRoomPax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('first_name', models.CharField(blank=True, max_length=300, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10)),
                ('last_name', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('pan', models.CharField(blank=True, max_length=300, null=True)),
                ('mobile_country_code', models.CharField(blank=True, max_length=300, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=300, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.roomdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotelBookedRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('no_of_rooms', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor_booking_endpoint', models.CharField(blank=True, max_length=250, null=True)),
                ('vendor_booking_payload', models.JSONField(default=dict)),
                ('vendor_booking_response', models.JSONField(default=dict)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotelbooking')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.roomdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
