# Generated by Django 5.0.6 on 2025-03-13 06:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomDetails',
            new_name='HotelRoom',
        ),
        migrations.AlterField(
            model_name='hotelbookedroompax',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.hotelbookedroom'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='status',
            field=models.CharField(choices=[('enquiry', 'enquiry'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('partially_confirmed', 'partially_confirmed'), ('failed', 'failed'), ('partially_cancelled', 'partially_cancelled'), ('cancelled', 'cancelled')], default='pending', max_length=100),
        ),
        migrations.AlterModelTable(
            name='hotelbookedroom',
            table='hotel_booked_rooms',
        ),
        migrations.AlterModelTable(
            name='hotelbookedroompax',
            table='hotel_booked_room_paxes',
        ),
        migrations.AlterModelTable(
            name='hotelbooking',
            table='hotel_bookings',
        ),
        migrations.AlterModelTable(
            name='hoteldetails',
            table='hotel_details',
        ),
        migrations.AlterModelTable(
            name='hotelpayment',
            table='hotel_payment',
        ),
        migrations.AlterModelTable(
            name='hotelroom',
            table='hotel_rooms',
        ),
        migrations.CreateModel(
            name='HotelBookingCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('first_name', models.CharField(blank=True, max_length=300, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10)),
                ('last_name', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('pan', models.CharField(blank=True, max_length=300, null=True)),
                ('mobile_country_code', models.CharField(blank=True, max_length=300, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=300, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.hotelbooking')),
            ],
            options={
                'db_table': 'hotel_booking_customers',
            },
        ),
    ]
