# Generated by Django 5.0.6 on 2025-03-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_rename_roomdetails_hotelroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hoteldetails',
            name='latitude',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hoteldetails',
            name='longitude',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
