# Generated by Django 5.0.6 on 2025-03-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hoteldetails_address_hoteldetails_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='booking',
            new_name='payment',
        ),
    ]
