# Generated by Django 5.0.6 on 2025-03-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_remove_hotelbookingcustomer_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbookedroompax',
            name='gender',
        ),
        migrations.AddField(
            model_name='hotelbookedroompax',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.')], default='Mr.', max_length=10),
            preserve_default=False,
        ),
    ]
