# Generated by Django 5.0.6 on 2025-03-18 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_remove_hotelbookedroompax_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_booking', to='hotels.hotelpayment'),
        ),
    ]
