# Generated by Django 5.0.6 on 2025-03-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_alter_hotelbooking_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
