# Generated by Django 5.0.6 on 2025-03-19 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_hotelbooking_total_amount'),
        ('shared', '0033_distributoragentfareadjustment_cashback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelpayment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='hotelpayment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_payment', to='shared.payments'),
        ),
        migrations.AddField(
            model_name='hotelpayment',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'wallet'), ('upi', 'upi'), ('credit_card', 'credit_card'), ('debit_card', 'debit_card')], default='upi', max_length=100),
        ),
    ]
