# Generated by Django 5.0.6 on 2025-03-19 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_remove_hotelpayment_transaction_id_and_more'),
        ('shared', '0034_paymentdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_booking', to='shared.paymentdetail'),
        ),
        migrations.DeleteModel(
            name='HotelPayment',
        ),
    ]
