# Generated by Django 5.0.6 on 2025-03-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_alter_hotelbooking_payment_delete_hotelpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldetails',
            name='review_rating',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hoteldetails',
            name='star_rating',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
