# Generated by Django 5.0.6 on 2025-03-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_hoteldetails_review_rating_hoteldetails_star_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbookedroom',
            name='booking_data',
            field=models.JSONField(default=dict),
        ),
    ]
