# Generated by Django 5.0.6 on 2025-03-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_hotelbookedroom_booking_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbookedroompax',
            name='type',
            field=models.CharField(blank=True, choices=[('ADULT', 'ADULT'), ('CHILD.', 'CHILD')], max_length=300, null=True),
        ),
    ]
