# Generated by Django 5.0.6 on 2025-03-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_hotelbookedroompax_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbookingcustomer',
            name='client_nationality',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hotelbookingcustomer',
            name='pan_company_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
