# Generated by Django 5.0.6 on 2025-03-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_hotelbookingcustomer_client_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbookedroom',
            name='no_of_adults',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelbookedroom',
            name='no_of_children',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
