# Generated by Django 5.0.6 on 2025-03-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_hotelbookedroom_no_of_adults_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='vendor_booking_endpoint',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='vendor_booking_payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='vendor_booking_response',
            field=models.JSONField(default=dict),
        ),
    ]
