# Generated by Django 5.0.6 on 2025-04-02 07:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_hotelbooking_vendor_booking_endpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrnDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('code', models.CharField(max_length=300, unique=True)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'grn_destinations',
            },
        ),
        migrations.CreateModel(
            name='GrnCity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('code', models.CharField(max_length=300, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.grndestination')),
            ],
            options={
                'db_table': 'grn_cities',
            },
        ),
        migrations.CreateModel(
            name='GrnHotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('code', models.CharField(max_length=300, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.grncity')),
            ],
            options={
                'db_table': 'grn_hotels',
            },
        ),
    ]
