# Generated by Django 5.0.6 on 2025-04-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_grndestination_grncity_grnhotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
