# Generated by Django 5.0.6 on 2025-04-04 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0018_hotelbooking_voucher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnhotel',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.grndestination'),
        ),
    ]
