# Generated by Django 5.0.6 on 2025-04-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0019_grnhotel_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='voucher_code',
            new_name='display_id',
        ),
    ]
