# Generated by Django 5.0.6 on 2025-04-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0020_rename_voucher_code_hotelbooking_display_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbookedroompax',
            name='age',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
