# Generated by Django 5.0.6 on 2025-04-10 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0021_hotelbookedroompax_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelEasylinkBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300)),
                ('value', models.CharField(max_length=300)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotelbooking')),
            ],
            options={
                'db_table': 'hotel_easylink_data',
            },
        ),
    ]
