# Generated by Django 5.0.6 on 2025-04-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0022_hoteleasylinkbilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='vendor_booking_reference',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
