# Generated by Django 5.0.6 on 2024-06-19 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LookUpNotificationKeys',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('name', models.CharField(max_length=2000, unique=True)),
                ('type', models.CharField(choices=[('memory', 'memory'), ('event', 'event')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('integeration_type', models.CharField(max_length=200)),
                ('heading', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('event', models.CharField(max_length=200)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.notificationtemplates')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
