# Generated by Django 5.0.6 on 2024-06-20 06:37

from django.db import migrations

def add_default_values(apps, schema_editor):
    obj = apps.get_model('template', 'LookUpNotificationKeys')
    obj.objects.create(name="SEND_LOGIN_OTP", type="event")
    
class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_values),
    ]
