# Generated by Django 5.0.6 on 2024-06-20 06:50

from django.db import migrations



def add_default_values(apps, schema_editor):
    obj = apps.get_model('template', 'LookUpNotificationKeys')
    obj.objects.create(name="otp", type="memory")

class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_look_up_notification_key'),
    ]

    operations = [
        migrations.RunPython(add_default_values),
    ]