# Generated by Django 5.0.6 on 2024-06-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_look_up_notification_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lookupnotificationkeys',
            options={'verbose_name': 'lookup_notification_keys', 'verbose_name_plural': 'lookup_notification_keys'},
        ),
        migrations.AlterModelTable(
            name='lookupnotificationkeys',
            table='lookup_notification_keys',
        ),
    ]
