# Generated by Django 5.0.6 on 2024-06-24 06:38

from django.db import migrations



def add_default_values(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('template', '0004_alter_lookupnotificationkeys_options_and_more'),
    ]

    operations = [
        migrations.RunPython(add_default_values),
    ]
