# Generated by Django 5.0.6 on 2024-06-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0005_look_up_notification_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
