# Generated by Django 5.0.6 on 2024-07-26 08:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0007_notificationtemplates_recived_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationtemplates",
            name="recived_cc",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=600),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
