# Generated by Django 5.0.6 on 2024-07-31 08:54

from django.db import migrations

def add_default_values(apps, schema_editor):
    obj = apps.get_model('template', 'LookUpNotificationKeys')
    obj.objects.create(name="customer_email", type="memory")
class Migration(migrations.Migration):

    dependencies = [
        ("template", "0008_notificationtemplates_recived_cc"),
    ]

    operations = [
         migrations.RunPython(add_default_values)
    ]
