# Generated by Django 5.0.6 on 2024-08-01 06:51

from django.db import migrations



def add_default_values(apps, schema_editor):
    obj = apps.get_model('template', 'LookUpNotificationKeys')
    obj.objects.create(name="GENERATE_FIRST_TIME_LOGIN_PASSWORD", type="event")
class Migration(migrations.Migration):


    dependencies = [
        ("template", "0009_auto_20240731_0854"),
    ]

    operations = [
        migrations.RunPython(add_default_values)
    ]
