# Generated by Django 5.0.6 on 2024-08-01 07:40

from django.db import migrations




def add_default_values(apps, schema_editor):
    obj = apps.get_model('template', 'LookUpNotificationKeys')
    obj.objects.create(name="one_time_password", type="memory")
    
    
class Migration(migrations.Migration):

    dependencies = [
        ("template", "0010_auto_20240801_0651"),
    ]

    operations = [
        
    ]
