# Generated by Django 5.0.6 on 2024-08-01 08:58

from django.db import migrations

def add_default_values(apps, schema_editor):
    LookUpNotificationKeys = apps.get_model('notification', 'LookUpIntegerationNotification')
    LookUpNotificationKeys.objects.create(name='VoicenSMS', integeration_type='sms',keys=["senderid"], icon_url="https://www.srisaiacupunctureillam.com/image/call.gif")



class Migration(migrations.Migration):

    dependencies = [
        ("template", "0011_auto_20240801_0740"),
    ]

    operations = [
        # migrations.RunPython(add_default_values)
    ]
