# Generated by Django 5.0.6 on 2024-08-10 10:38

from django.db import migrations


def add_default_values(apps, schema_editor):
    obj = apps.get_model('template', 'LookUpNotificationKeys')
    if not obj.objects.filter(name="SEND_LOGIN_OTP", type="event"):
        obj.objects.create(name="SEND_LOGIN_OTP", type="event")

class Migration(migrations.Migration):

    dependencies = [
        ("template", "0014_auto_20240809_0632"),
    ]

    operations = [
     migrations.RunPython(add_default_values)
    ]
