# Generated by Django 5.0.6 on 2024-09-06 10:43
# Generated by Django 5.0.6 on 2024-09-06 10:03


from django.db import migrations


def add_default_values(apps, schema_editor):
    obj = apps.get_model('template', 'LookUpNotificationKeys')
    obj.objects.create(name="organization_name", type="memory")

    
 
    
class Migration(migrations.Migration):

    dependencies = [
        ('template', '0020_auto_20240906_1028'),
    ]
    operations = [
     migrations.RunPython(add_default_values)
    ]
