# Generated by Django 5.0.6 on 2024-09-24 08:33

from django.db import migrations

def add_default_values(apps, schema_editor):
    obj = apps.get_model('template', 'LookUpNotificationKeys')
    obj.objects.create(name="UNCONFIRMED_REGISTRATION", type="event")
class Migration(migrations.Migration):

    dependencies = [
        ('template', '0021_auto_20240906_1043'),
    ]

    operations = [
        migrations.RunPython(add_default_values)
    ]
