# Generated by Django 5.0.6 on 2024-09-24 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0022_auto_20240924_0833'),
    ]

    operations = [
    ]
