# Generated by Django 5.0.6 on 2024-10-09 05:31

from django.db import migrations

def add_default_values(apps, schema_editor):
    obj = apps.get_model('template', 'LookUpNotificationKeys')
    obj.objects.create(name="UPON_APPROVAL_ORGANIZATION", type="event")
    obj.objects.create(name="UPON_CREDIT_UPDATION", type="event")
   
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('template', '0023_auto_20240924_0840'),
    ]

    operations = [
        migrations.RunPython(add_default_values)
    ]
