# Generated by Django 5.0.6 on 2024-10-29 07:34

from django.db import migrations

def add_default_values(apps, schema_editor):
    obj = apps.get_model('template', 'LookUpNotificationKeys')
    obj.objects.create(name="organization_owner_email", type="memory")

class Migration(migrations.Migration):

    dependencies = [
        ('template', '0024_auto_20241009_0531'),
    ]

    operations = [
        migrations.RunPython(add_default_values)
    ]
