# Generated by Django 5.0.6 on 2024-10-29 08:15

from django.db import migrations

def add_default_values(apps, schema_editor):
    obj = apps.get_model('template', 'LookUpNotificationKeys')
    obj.objects.create(name="CANCEL_TICKET_REQUEST", type="event")
    obj.objects.create(name="MODIFY_BOOKING_REQUEST", type="event")
    obj.objects.create(name="BOOKING_FAILED", type="event")
    obj.objects.create(name="BOOKING_CONFIRMED", type="event")
    obj.objects.create(name="ON_HOLD", type="event")
    
    obj.objects.create(name="operations_email", type="memory")

class Migration(migrations.Migration):

    dependencies = [
        ('template', '0025_auto_20241029_0734'),
    ]

    operations = [
        migrations.RunPython(add_default_values)
    ]
