# Generated by Django 5.0.6 on 2024-11-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0026_auto_20241029_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lookupnotificationkeys',
            options={'ordering': ['-created_at'], 'verbose_name': 'lookup_notification_keys', 'verbose_name_plural': 'lookup_notification_keys'},
        ),
    ]
