# Generated by Django 5.0.6 on 2024-08-08 07:32

import ckeditor.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("holiday_app", "0001_initial"),
        ("users", "0023_lookuppermission_admin1space1panel_delete_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisaCategoryMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("name", models.CharField(max_length=500)),
                (
                    "icon_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.gallery",
                    ),
                ),
            ],
            options={"db_table": "visa_category_master",},
        ),
        migrations.CreateModel(
            name="VisaSKU",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("slug", models.SlugField(max_length=500, unique=True)),
                ("name", models.CharField(max_length=500)),
                ("stay_duration", models.CharField(max_length=300)),
                (
                    "validity",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500), size=None
                    ),
                ),
                ("entry_type", models.CharField(max_length=300)),
                ("processing_time", models.CharField(max_length=300)),
                ("info", ckeditor.fields.RichTextField()),
                ("documents_required", models.JSONField()),
                ("faq", models.JSONField()),
                ("status", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visa_app.visacategorymaster",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_visa_sku",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visa_from_country",
                        to="users.lookupcountry",
                    ),
                ),
                (
                    "to_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visa_to_country",
                        to="users.lookupcountry",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_visa_sku",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "visa_sku",},
        ),
        migrations.CreateModel(
            name="VisaSKUImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                (
                    "gallery_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.gallery",
                    ),
                ),
                (
                    "sku_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visa_app.visasku",
                    ),
                ),
            ],
            options={"db_table": "visa_sku_image",},
        ),
        migrations.CreateModel(
            name="VisaSKUPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "country_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.lookupcountry",
                    ),
                ),
                (
                    "sku_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visa_app.visasku",
                    ),
                ),
            ],
            options={"db_table": "visa_sku_price",},
        ),
        migrations.CreateModel(
            name="VisaTypeMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("name", models.CharField(max_length=500)),
                (
                    "icon_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.gallery",
                    ),
                ),
            ],
            options={"db_table": "visa_type_master",},
        ),
        migrations.AddField(
            model_name="visasku",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="visa_app.visatypemaster",
            ),
        ),
    ]
