# Generated by Django 4.2.6 on 2024-08-19 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("visa_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visacategorymaster",
            name="icon_url",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.gallery"
            ),
        ),
        migrations.AlterField(
            model_name="visaskuimage",
            name="gallery_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.gallery"
            ),
        ),
        migrations.AlterField(
            model_name="visatypemaster",
            name="icon_url",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.gallery"
            ),
        ),
    ]
