# Generated by Django 5.0.6 on 2024-08-30 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_rename_company_address_organization_address_and_more"),
        ("visa_app", "0002_alter_visacategorymaster_icon_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visaskuprice",
            name="country_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.country"
            ),
        ),
    ]
