# Generated by Django 5.0.6 on 2024-09-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visa_app", "0003_alter_visaskuprice_country_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visasku",
            name="validity",
            field=models.CharField(max_length=500),
        ),
    ]
