# Generated by Django 5.0.6 on 2024-09-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visa_app", "0004_alter_visasku_validity"),
    ]

    operations = [
        migrations.RemoveField(model_name="visasku", name="validity",),
    ]
