# Generated by Django 5.0.6 on 2024-09-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visa_app", "0005_remove_visasku_validity"),
    ]

    operations = [
        migrations.AddField(
            model_name="visasku",
            name="validity",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
