# Generated by Django 5.0.6 on 2024-09-17 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0036_alter_countrydefault_country_id"),
        ("visa_app", "0006_visasku_validity"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisaFavourite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                (
                    "country_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.country"
                    ),
                ),
                (
                    "sku_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visa_app.visasku",
                    ),
                ),
            ],
            options={"db_table": "visa_favourite",},
        ),
    ]
