# Generated by Django 5.0.6 on 2024-09-18 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0038_rename_account_code_organization_easy_link_account_code_and_more",
        ),
        ("visa_app", "0007_visafavourite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisaEnquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("name", models.CharField(max_length=500)),
                ("gender", models.CharField(max_length=300)),
                ("dob", models.DateField(blank=True, null=True)),
                ("place_of_birth", models.CharField(max_length=500)),
                ("email", models.CharField(max_length=500)),
                ("phone_number", models.IntegerField()),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                (
                    "marital_status",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "current_address",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                (
                    "passport_number",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("date_of_issue", models.DateField(blank=True, null=True)),
                ("date_of_expiry", models.DateField(blank=True, null=True)),
                (
                    "place_of_issue",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                ("visa_type", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "purpose_of_visit",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("duration", models.CharField(blank=True, max_length=400, null=True)),
                ("date_of_entry", models.DateField(blank=True, null=True)),
                ("date_of_exit", models.DateField(blank=True, null=True)),
                ("visa_ref_id", models.TextField()),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.country"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visa_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visa_app.visasku",
                    ),
                ),
            ],
            options={"db_table": "visa_enquiry",},
        ),
    ]
