# Generated by Django 5.0.6 on 2024-09-19 04:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visa_app", "0008_visaenquiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisaEnquiryStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("name", models.CharField(max_length=5000, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"db_table": "visa_enquiry_status",},
        ),
    ]
