# Generated by Django 5.0.6 on 2024-09-19 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visa_app", "0009_visaenquirystatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="visaenquiry",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="visa_app.visaenquirystatus",
            ),
        ),
    ]
