# Generated by Django 5.0.6 on 2024-09-19 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visa_app", "0010_visaenquiry_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="visaenquiry", name="country",),
    ]
