# Generated by Django 5.0.6 on 2024-09-19 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0041_errorlogadvanced_os_name_errorlogadvanced_user_agent"),
        ("visa_app", "0011_remove_visaenquiry_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="visaenquiry",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.lookupcountry",
            ),
        ),
    ]
