# Generated by Django 5.0.6 on 2024-09-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visa_app", "0012_visaenquiry_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="visasku",
            name="description",
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
