# Generated by Django 5.0.6 on 2024-09-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa_app', '0013_visasku_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaenquiry',
            name='nationality',
        ),
    ]
