# Generated by Django 5.0.6 on 2024-09-24 04:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visa_app", "0014_remove_visaenquiry_nationality"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisaEnquiryHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("updated_at", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visa_app.visaenquirystatus",
                    ),
                ),
                (
                    "visa_enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visa_app.visasku",
                    ),
                ),
            ],

            options={"abstract": False,},

        ),
    ]
