# Generated by Django 5.0.6 on 2024-09-24 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visa_app", "0015_visaenquiryhistory"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="visaenquiryhistory", table="visa_enquiry_history",
        ),
    ]
