# Generated by Django 5.0.6 on 2024-09-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visa_app", "0016_alter_visaenquiryhistory_table"),
    ]

    operations = [
        migrations.RemoveField(model_name="visaenquiry", name="status",),
        migrations.RemoveField(model_name="visaenquiryhistory", name="updated_at",),
    ]
