# Generated by Django 5.0.6 on 2024-09-24 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visa_app", "0017_remove_visaenquiry_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="visaenquiryhistory", name="visa_enquiry",),
    ]
