# Generated by Django 5.0.6 on 2024-09-24 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visa_app", "0018_remove_visaenquiryhistory_visa_enquiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="visaenquiryhistory",
            name="visa_enquiry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="visa_app.visaenquiry",
            ),
        ),
    ]
