# Generated by Django 5.0.6 on 2024-09-26 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visa_app", "0019_visaenquiryhistory_visa_enquiry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VisaEnquiryStatus", new_name="LookupVisaEnquiryStatus",
        ),
        migrations.RemoveField(model_name="visaenquiry", name="phone_number",),
        migrations.AddField(
            model_name="visaenquiry",
            name="pax_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="visaenquiry",
            name="phone",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="visaenquiryhistory",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="lookupvisaenquirystatus", table="lookup_visa_enquiry_status",
        ),
    ]
