# Generated by Django 5.0.6 on 2024-09-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visa_app", "0020_rename_visaenquirystatus_lookupvisaenquirystatus_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visaenquiry", old_name="phone", new_name="phone_number",
        ),
    ]
