# Generated by Django 5.0.6 on 2024-09-27 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visa_app", "0021_rename_phone_visaenquiry_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visaenquiryhistory", old_name="status", new_name="status_id",
        ),
    ]
