# Generated by Django 5.0.6 on 2024-11-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visa_app", "0022_rename_status_visaenquiryhistory_status_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visaenquiry",
            name="phone_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
