# Generated by Django 5.0.6 on 2024-11-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visa_app", "0023_alter_visaenquiry_phone_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="visaenquiry", name="phone_number",),
    ]
