# Generated by Django 5.0.6 on 2024-11-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visa_app", "0024_remove_visaenquiry_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="visaenquiry",
            name="phone_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
