# Generated by Django 5.0.6 on 2024-11-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa_app', '0025_visaenquiry_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lookupvisaenquirystatus',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='visacategorymaster',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='visaenquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='visaenquiryhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='visafavourite',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='visasku',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='visaskuimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='visaskuprice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='visatypemaster',
            options={'ordering': ['-created_at']},
        ),
    ]
