# Generated by Django 5.0.6 on 2024-11-27 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visa_app", "0026_alter_lookupvisaenquirystatus_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="visasku", name="description",),
    ]
