# Generated by Django 5.0.6 on 2024-11-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visa_app", "0027_remove_visasku_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="visasku",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
