# Generated by Django 5.0.6 on 2024-12-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visa_app", "0028_visasku_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookupvisaenquirystatus",
            name="progression_order",
            field=models.IntegerField(default=0),
        ),
    ]
