# Generated by Django 5.0.6 on 2025-03-17 19:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0135_lookuppermission_transfers_search_create_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RailOrganizationDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("agency_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("pan", models.CharField(max_length=15)),
                ("dob", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=500)),
                ("landmark", models.CharField(max_length=500)),
                ("country", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("pincode", models.IntegerField()),
                ("agent_id", models.CharField(max_length=50)),
                ("irctc_id", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=False)),
                ("status", models.CharField(default="Pending", max_length=50)),
                ("timestamp", models.BigIntegerField(editable=False, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modified_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rail Organization Detail",
                "db_table": "rail_organization_details",
                "ordering": ["timestamp"],
            },
        ),
    ]
