# Generated by Django 5.0.6 on 2025-03-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rail_booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="railorganizationdetails",
            name="agent_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="railorganizationdetails",
            name="irctc_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
