# Generated by Django 5.0.6 on 2025-03-28 05:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rail_booking", "0002_alter_railorganizationdetails_agent_id_and_more"),
        ("users", "0145_lookuppermission_bus_booking1space1history_create_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RailTransactions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(default="Enquiry", max_length=20)),
                ("merchantCode", models.CharField(max_length=50)),
                ("reservationId", models.CharField(max_length=50)),
                ("txnAmount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currencyType", models.CharField(max_length=10)),
                ("appCode", models.CharField(max_length=10)),
                ("pymtMode", models.CharField(max_length=20)),
                ("txnDate", models.CharField(max_length=8)),
                ("securityId", models.CharField(max_length=50)),
                ("RU", models.URLField()),
                ("userID", models.CharField(max_length=50)),
                ("ownerID", models.CharField(max_length=50)),
                ("fixedCharge", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "variableCharge",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("Cgst", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Sgst", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Igst", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "totalTxnAmount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("class_field", models.CharField(max_length=10)),
                ("noOfPax", models.PositiveIntegerField()),
                (
                    "maxAgentFeeinclGST",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "maxPGChargeinclGST",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "ticketPrintRate",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("wsUserLogin", models.CharField(max_length=50)),
                ("CheckSum", models.CharField(max_length=100)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rail Transaction Detail",
                "db_table": "rail_transactions",
            },
        ),
    ]
