# Generated by Django 5.0.6 on 2025-03-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rail_booking", "0003_railtransactions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="railtransactions",
            name="Cgst",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="CheckSum",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="Igst",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="RU",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="Sgst",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="appCode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="class_field",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="currencyType",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="fixedCharge",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="maxAgentFeeinclGST",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="maxPGChargeinclGST",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="merchantCode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="noOfPax",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="ownerID",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="pymtMode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="reservationId",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="securityId",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="ticketPrintRate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="totalTxnAmount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="txnAmount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="txnDate",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="userID",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="variableCharge",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="railtransactions",
            name="wsUserLogin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
