# Generated by Django 5.0.6 on 2025-03-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rail_booking", "0004_alter_railtransactions_cgst_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RailLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_stamp",
                    models.DateTimeField(blank=True, db_column="TimeStamp", null=True),
                ),
                (
                    "previousID",
                    models.CharField(
                        blank=True, db_column="previousID", max_length=255, null=True
                    ),
                ),
                (
                    "previousBal",
                    models.CharField(
                        blank=True, db_column="previousBal", max_length=255, null=True
                    ),
                ),
                (
                    "refrerenceID",
                    models.CharField(
                        blank=True, db_column="refrerenceID", max_length=255, null=True
                    ),
                ),
                (
                    "userID",
                    models.CharField(
                        blank=True, db_column="userID", max_length=255, null=True
                    ),
                ),
                (
                    "ownerID",
                    models.CharField(
                        blank=True, db_column="ownerID", max_length=255, null=True
                    ),
                ),
                (
                    "accountID",
                    models.CharField(
                        blank=True, db_column="accountID", max_length=255, null=True
                    ),
                ),
                (
                    "itemID",
                    models.CharField(
                        blank=True, db_column="itemID", max_length=255, null=True
                    ),
                ),
                (
                    "supplierRef",
                    models.CharField(
                        blank=True, db_column="supplierRef", max_length=255, null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, db_column="description", null=True),
                ),
                (
                    "item_amt",
                    models.CharField(
                        blank=True, db_column="item_amt", max_length=255, null=True
                    ),
                ),
                (
                    "charges",
                    models.CharField(
                        blank=True, db_column="charges", max_length=255, null=True
                    ),
                ),
                (
                    "SGST",
                    models.CharField(
                        blank=True, db_column="SGST", max_length=255, null=True
                    ),
                ),
                (
                    "CGST",
                    models.CharField(
                        blank=True, db_column="CGST", max_length=255, null=True
                    ),
                ),
                (
                    "IGST",
                    models.CharField(
                        blank=True, db_column="IGST", max_length=255, null=True
                    ),
                ),
                (
                    "commission",
                    models.CharField(
                        blank=True, db_column="commission", max_length=255, null=True
                    ),
                ),
                (
                    "TDS",
                    models.CharField(
                        blank=True, db_column="TDS", max_length=255, null=True
                    ),
                ),
                (
                    "amt_cr",
                    models.CharField(
                        blank=True, db_column="amt_cr", max_length=255, null=True
                    ),
                ),
                (
                    "amt_dr",
                    models.CharField(
                        blank=True, db_column="amt_dr", max_length=255, null=True
                    ),
                ),
                (
                    "balanceAmt",
                    models.CharField(
                        blank=True, db_column="balanceAmt", max_length=255, null=True
                    ),
                ),
                (
                    "WH_Status",
                    models.CharField(
                        blank=True, db_column="WH_Status", max_length=255, null=True
                    ),
                ),
                (
                    "supplierRef1",
                    models.CharField(
                        blank=True, db_column="supplierRef1", max_length=255, null=True
                    ),
                ),
                (
                    "attempt",
                    models.CharField(
                        blank=True, db_column="attempt", max_length=255, null=True
                    ),
                ),
                (
                    "mongo_id",
                    models.CharField(
                        blank=True, db_column="_id", max_length=255, null=True
                    ),
                ),
                (
                    "journalID",
                    models.CharField(
                        blank=True, db_column="journalID", max_length=255, null=True
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, db_column="__v", max_length=255, null=True
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True, db_column="tag", max_length=255, null=True
                    ),
                ),
                (
                    "CheckSum",
                    models.CharField(
                        blank=True, db_column="CheckSum", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Rail Ledger",
                "db_table": "rail_ledger",
            },
        ),
    ]
