# Generated by Django 5.0.6 on 2025-04-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rail_booking", "0006_railledger_organization_railledger_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="railledger",
            name="Last_blockBalance",
            field=models.CharField(
                blank=True, db_column="Last_blockBalance", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="railledger",
            name="partnerTxnID",
            field=models.CharField(
                blank=True, db_column="partnerTxnID", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="railledger",
            name="previous_blockBalance",
            field=models.CharField(
                blank=True, db_column="previous_blockBalance", max_length=255, null=True
            ),
        ),
    ]
