# Generated by Django 5.0.6 on 2025-04-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rail_booking",
            "0007_railledger_last_blockbalance_railledger_partnertxnid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="railledger",
            name="display_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
