# Generated by Django 5.0.6 on 2025-04-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rail_booking", "0008_railledger_display_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="railledger",
            name="display_id",
        ),
        migrations.AddField(
            model_name="railtransactions",
            name="display_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
