# Generated by Django 5.0.6 on 2024-10-09 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_alter_creditlog_log_message'),
        ('users', '0049_lookupairline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorAgentFareAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('cashback', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('markup', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('module', models.CharField(choices=[('flight', 'flight'), ('hotel', 'hotel'), ('holiday', 'holiday'), ('visa', 'visa')], default='flight', max_length=200)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationFareAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('cashback', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('markup', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('module', models.CharField(choices=[('flight', 'flight'), ('hotel', 'hotel'), ('holiday', 'holiday'), ('visa', 'visa')], default='flight', max_length=200)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
