# Generated by Django 5.0.6 on 2024-10-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_distributoragentfareadjustment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributoragentfareadjustment',
            old_name='issued_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='distributoragentfareadjustment',
            name='organization',
        ),
        migrations.AddField(
            model_name='organizationfareadjustment',
            name='parting_percentage',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterModelTable(
            name='distributoragentfareadjustment',
            table='distributor_agent_fare_adjustment',
        ),
        migrations.AlterModelTable(
            name='organizationfareadjustment',
            table='organization_fare_adjustment',
        ),
    ]
