# Generated by Django 5.0.6 on 2024-10-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_rename_issued_by_distributoragentfareadjustment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationfareadjustment',
            name='cancellation_chyarges',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='organizationfareadjustment',
            name='cashback',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='organizationfareadjustment',
            name='markup',
            field=models.FloatField(default=0.0),
        ),
    ]
