# Generated by Django 5.0.6 on 2024-10-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_organizationfareadjustment_cancellation_chyarges_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationfareadjustment',
            old_name='cancellation_chyarges',
            new_name='cancellation_charges',
        ),
    ]
