# Generated by Django 5.0.6 on 2024-10-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_rename_cancellation_chyarges_organizationfareadjustment_cancellation_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributoragentfareadjustment',
            name='cancellation_charges',
            field=models.FloatField(default=0.0),
        ),
    ]
