# Generated by Django 5.0.6 on 2024-11-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_distributoragentfareadjustment_cancellation_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributoragentfareadjustment',
            name='wallet_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
