# Generated by Django 5.0.6 on 2024-11-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_distributoragentfareadjustment_wallet_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributoragentfareadjustment',
            old_name='wallet_balance',
            new_name='available_balance',
        ),
        migrations.AddField(
            model_name='distributoragentfareadjustment',
            name='credit_limit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='distributoragentfareadjustment',
            name='parting_percentage',
            field=models.FloatField(default=100.0),
        ),
    ]
