# Generated by Django 5.0.6 on 2024-11-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0010_rename_wallet_balance_distributoragentfareadjustment_available_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributoragentfareadjustment',
            name='available_balance',
        ),
        migrations.RemoveField(
            model_name='distributoragentfareadjustment',
            name='cancellation_charges',
        ),
        migrations.RemoveField(
            model_name='distributoragentfareadjustment',
            name='cashback',
        ),
        migrations.RemoveField(
            model_name='distributoragentfareadjustment',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='distributoragentfareadjustment',
            name='markup',
        ),
        migrations.RemoveField(
            model_name='distributoragentfareadjustment',
            name='module',
        ),
        migrations.RemoveField(
            model_name='distributoragentfareadjustment',
            name='parting_percentage',
        ),
    ]
