# Generated by Django 5.0.6 on 2024-11-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0011_remove_distributoragentfareadjustment_available_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributoragentfareadjustment',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='distributoragentfareadjustment',
            name='booking_type',
            field=models.CharField(choices=[('new_ticketing', 'new_ticketing'), ('cancellation', 'cancellation')], default='new_ticketing', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributoragentfareadjustment',
            name='cancellation_charges',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='distributoragentfareadjustment',
            name='module',
            field=models.CharField(choices=[('flight', 'flight'), ('hotel', 'hotel'), ('holiday', 'holiday'), ('visa', 'visa')], default='flight', max_length=200),
        ),
        migrations.AddField(
            model_name='distributoragentfareadjustment',
            name='transtransaction_type',
            field=models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], default='credit', max_length=200),
            preserve_default=False,
        ),
    ]
