# Generated by Django 5.0.6 on 2024-11-06 10:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0012_distributoragentfareadjustment_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributoragentfareadjustment',
            old_name='amount',
            new_name='available_balance',
        ),
        migrations.RemoveField(
            model_name='distributoragentfareadjustment',
            name='booking_type',
        ),
        migrations.RemoveField(
            model_name='distributoragentfareadjustment',
            name='transtransaction_type',
        ),
        migrations.AddField(
            model_name='distributoragentfareadjustment',
            name='cashback',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='distributoragentfareadjustment',
            name='credit_limit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='distributoragentfareadjustment',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='distributoragentfareadjustment',
            name='parting_percentage',
            field=models.FloatField(default=100.0),
        ),
        migrations.CreateModel(
            name='DistributorAgentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('transtransaction_type', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], max_length=200)),
                ('module', models.CharField(choices=[('flight', 'flight'), ('hotel', 'hotel'), ('holiday', 'holiday'), ('visa', 'visa')], default='flight', max_length=200)),
                ('booking_type', models.CharField(choices=[('new_ticketing', 'new_ticketing'), ('cancellation', 'cancellation')], max_length=200)),
                ('cancellation_charges', models.FloatField(default=0.0)),
                ('amount', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'distributor_agent_transactions',
            },
        ),
    ]
