# Generated by Django 5.0.6 on 2024-11-07 12:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0013_rename_amount_distributoragentfareadjustment_available_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorAgentFareAdjustmentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('old_credit_limit', models.FloatField(default=0.0)),
                ('old_available_balance', models.FloatField(default=0.0)),
                ('new_credit_limit', models.FloatField(default=0.0)),
                ('new_available_balance', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
