# Generated by Django 5.0.6 on 2024-11-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0014_distributoragentfareadjustmentlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributoragentfareadjustment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='distributoragenttransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='organizationfareadjustment',
            options={'ordering': ['-created_at']},
        ),
    ]
