# Generated by Django 5.0.6 on 2024-11-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0015_alter_distributoragentfareadjustment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributoragenttransaction',
            name='booking_type',
            field=models.CharField(choices=[('new_ticketing', 'new_ticketing'), ('cancellation', 'cancellation')], max_length=200, null=True),
        ),
    ]
