# Generated by Django 5.0.6 on 2024-11-16 07:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0016_alter_distributoragenttransaction_booking_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="LookupCreditCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("card_type", models.CharField(max_length=50)),
                ("card_number", models.CharField(max_length=16, unique=True)),
            ],
            options={
                "verbose_name": "Credit Card",
                "verbose_name_plural": "Credit Cards",
                "db_table": "lookup_credit_card",
                "ordering": ["card_type"],
            },
        ),
    ]
