# Generated by Django 5.0.6 on 2024-11-16 09:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0017_lookupcreditcard"),
    ]

    operations = [
        migrations.CreateModel(
            name="LookupEasyLinkSupplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("display_id", models.CharField(max_length=200)),
                ("supplier_id", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Easy Link Supplier",
                "verbose_name_plural": "Easy Link Suppliers",
                "db_table": "lookup_easylink_supplier",
                "ordering": ["display_id"],
            },
        ),
    ]
