# Generated by Django 5.0.6 on 2024-11-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0018_lookupeasylinksupplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="lookupcreditcard",
            name="internal_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="lookupcreditcard",
            name="card_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
