# Generated by Django 5.0.6 on 2024-11-27 09:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0019_lookupcreditcard_internal_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentUpdates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('agency_name', models.CharField(blank=True, max_length=100, null=True)),
                ('agency_id', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment_url', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approve', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'payment-updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
