# Generated by Django 5.0.6 on 2024-11-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0020_paymentupdates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentupdates',
            name='approve',
        ),
        migrations.RemoveField(
            model_name='paymentupdates',
            name='reject',
        ),
        migrations.AddField(
            model_name='paymentupdates',
            name='choice',
            field=models.CharField(choices=[('pending', 'pending'), ('approve', 'approve'), ('reject', 'reject')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentupdates',
            name='date',
            field=models.DateField(),
        ),
    ]
