# Generated by Django 5.0.6 on 2024-11-28 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0022_alter_paymentupdates_agency_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentupdates',
            old_name='agency_id',
            new_name='agency',
        ),
    ]
