# Generated by Django 5.0.6 on 2024-11-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0023_rename_agency_id_paymentupdates_agency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentupdates',
            old_name='choice',
            new_name='status',
        ),
    ]
