# Generated by Django 5.0.6 on 2024-12-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0025_rechargepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rechargepayment',
            old_name='payment_link_id',
            new_name='payment_id_link',
        ),
    ]
