# Generated by Django 5.0.6 on 2024-12-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0027_payments_delete_rechargepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_types',
            field=models.CharField(choices=[('recharge', 'recharge'), ('booking', 'booking')], default='recharge', max_length=20),
        ),
    ]
