# Generated by Django 5.0.6 on 2024-12-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0028_alter_payments_payment_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
