# Generated by Django 5.0.6 on 2024-12-17 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight_booking", "0022_flightbookingpaymentdetails_amount"),
        ("shared", "0029_payments_razorpay_payment_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="distributoragenttransaction",
            name="cancellation_charges",
        ),
        migrations.AddField(
            model_name="distributoragenttransaction",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distributor_agent_transaction",
                to="flight_booking.booking",
            ),
        ),
    ]
