# Generated by Django 5.0.6 on 2024-12-18 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "shared",
            "0030_remove_distributoragenttransaction_cancellation_charges_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditlog",
            name="notes",
        ),
    ]
