# Generated by Django 5.0.6 on 2024-12-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0032_remove_distributoragentfareadjustment_cashback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributoragentfareadjustment",
            name="cashback",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="distributoragentfareadjustment",
            name="markup",
            field=models.FloatField(default=0.0),
        ),
    ]
