# Generated by Django 5.0.6 on 2025-03-19 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0033_distributoragentfareadjustment_cashback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(editable=False, null=True)),
                ('modified_at', models.BigIntegerField(editable=False, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('wallet', 'wallet'), ('upi', 'upi'), ('credit_card', 'credit_card'), ('debit_card', 'debit_card')], max_length=100, null=True)),
                ('payment_handler', models.CharField(choices=[('HotelManager', 'HotelManager'), ('FlightManager', 'FlightManager'), ('BusManager', 'BusManager'), ('TransfersManager', 'TransfersManager'), ('RailManager', 'RailManager')], max_length=100)),
                ('order_api_endpoint', models.CharField(blank=True, max_length=250, null=True)),
                ('order_api_payload', models.JSONField(default=dict)),
                ('order_api_response', models.JSONField(default=dict)),
                ('is_callback_recieved', models.BooleanField(default=False)),
                ('callback_payload', models.JSONField(default=dict)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_detail', to='shared.payments')),
            ],
            options={
                'db_table': 'payment_details',
            },
        ),
    ]
