# Generated by Django 5.0.6 on 2025-03-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0035_paymentdetail_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('wallet', 'wallet'), ('upi', 'upi'), ('credit_card', 'credit_card'), ('debit_card', 'debit_card'), ('net_banking', 'net_banking')], max_length=100, null=True),
        ),
    ]
