# Generated by Django 4.2.6 on 2024-08-19 05:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("name", models.CharField(max_length=500)),
                ("url", models.ImageField(upload_to="btob/gallery")),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("flight", "flight"),
                            ("hotel", "hotel"),
                            ("holiday", "holiday"),
                        ],
                        max_length=400,
                    ),
                ),
            ],
            options={
                "db_table": "gallery_bta",
            },
        ),
    ]
