# Generated by Django 4.2.6 on 2024-08-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="alternative_text",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
