# Generated by Django 5.0.6 on 2024-09-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_gallery_alternative_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="module",
            field=models.CharField(
                choices=[
                    ("flight", "flight"),
                    ("hotel", "hotel"),
                    ("holiday", "holiday"),
                    ("visa", "visa"),
                ],
                max_length=400,
            ),
        ),
    ]
