# Generated by Django 5.0.6 on 2024-11-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_gallery_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_at']},
        ),
    ]
