# Generated by Django 5.0.6 on 2025-01-21 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_gallery_options"),
        (
            "users",
            "0118_lookuppermission_reports_finance1space1team1space1performance_create_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientWebService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(editable=False, null=True)),
                ("modified_at", models.BigIntegerField(editable=False, null=True)),
                ("alert_sequence_no", models.CharField(max_length=400)),
                (
                    "virtual_account",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                ("account_number", models.CharField(max_length=400)),
                ("debit_credit", models.CharField(max_length=400)),
                ("amount", models.CharField(max_length=400)),
                (
                    "remitter_name",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "remitter_account",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "remitter_bank",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "remitter_IFSC",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                ("cheque_no", models.CharField(blank=True, max_length=400, null=True)),
                (
                    "user_reference_number",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "mnemonic_code",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                ("value_date", models.CharField(blank=True, max_length=400, null=True)),
                (
                    "transaction_description",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "transaction_date",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.organization",
                    ),
                ),
            ],
            options={"db_table": "client_web_service",},
        ),
    ]
