# Generated by Django 5.0.6 on 2025-01-29 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_clientwebservice"),
        (
            "users",
            "0118_lookuppermission_reports_finance1space1team1space1performance_create_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClientWebService", new_name="VirtualAccountTransaction",
        ),
        migrations.AlterModelTable(
            name="virtualaccounttransaction", table="virtual_account_transaction",
        ),
    ]
