# Generated by Django 5.0.6 on 2025-01-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_rename_clientwebservice_virtualaccounttransaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualaccounttransaction",
            name="easylink_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="virtualaccounttransaction",
            name="alert_sequence_no",
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
