# Generated by Django 5.0.6 on 2025-01-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_virtualaccounttransaction_easylink_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="virtualaccounttransaction", name="easylink_status",
        ),
    ]
