# Generated by Django 5.0.6 on 2025-01-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_remove_virtualaccounttransaction_easylink_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualaccounttransaction",
            name="easylink_status",
            field=models.BooleanField(default=False),
        ),
    ]
