# Generated by Django 5.0.6 on 2025-02-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_virtualaccounttransaction_easylink_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("flight", "flight"),
                            ("hotel", "hotel"),
                            ("holiday", "holiday"),
                            ("visa", "visa"),
                            ("transfers", "transfers"),
                        ],
                        default="flight",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "db_table": "daily_counter",
            },
        ),
    ]
