# Generated by Django 5.0.6 on 2025-03-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0010_dailycounter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailycounter",
            name="date",
            field=models.DateField(db_index=True),
        ),
    ]
