# Generated by Django 5.0.6 on 2025-03-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_alter_dailycounter_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailycounter",
            name="module",
            field=models.CharField(
                choices=[
                    ("flight", "flight"),
                    ("hotel", "hotel"),
                    ("holiday", "holiday"),
                    ("visa", "visa"),
                    ("transfers", "transfers"),
                    ("Rail", "Rail"),
                    ("Bus", "Bus"),
                    ("Insurance", "Insurance"),
                ],
                default="flight",
                max_length=200,
            ),
        ),
    ]
