# Generated by Django 5.0.6 on 2025-03-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0012_alter_dailycounter_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailycounter",
            name="module",
            field=models.CharField(
                choices=[
                    ("flight", "flight"),
                    ("hotel", "hotel"),
                    ("holiday", "holiday"),
                    ("visa", "visa"),
                    ("transfers", "transfers"),
                    ("rail", "rail"),
                    ("bus", "bus"),
                    ("insurance", "insurance"),
                ],
                default="flight",
                max_length=200,
            ),
        ),
    ]
